// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::aoe_shape_row_type::AoeShapeRow;
use super::vec_3_row_type::Vec3Row;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct AoeRegion {
    pub id: u64,
    pub caster: u64,
    pub spell_id: String,
    pub center: Vec3Row,
    pub direction: Vec3Row,
    pub radius: f32,
    pub shape: AoeShapeRow,
    pub remaining_seconds: f32,
    pub pending_delay_seconds: f32,
    pub affected: Vec<u64>,
    pub damage: f32,
    pub healing: f32,
}

impl __sdk::InModule for AoeRegion {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `AoeRegion`.
///
/// Provides typed access to columns for query building.
pub struct AoeRegionCols {
    pub id: __sdk::__query_builder::Col<AoeRegion, u64>,
    pub caster: __sdk::__query_builder::Col<AoeRegion, u64>,
    pub spell_id: __sdk::__query_builder::Col<AoeRegion, String>,
    pub center: __sdk::__query_builder::Col<AoeRegion, Vec3Row>,
    pub direction: __sdk::__query_builder::Col<AoeRegion, Vec3Row>,
    pub radius: __sdk::__query_builder::Col<AoeRegion, f32>,
    pub shape: __sdk::__query_builder::Col<AoeRegion, AoeShapeRow>,
    pub remaining_seconds: __sdk::__query_builder::Col<AoeRegion, f32>,
    pub pending_delay_seconds: __sdk::__query_builder::Col<AoeRegion, f32>,
    pub affected: __sdk::__query_builder::Col<AoeRegion, Vec<u64>>,
    pub damage: __sdk::__query_builder::Col<AoeRegion, f32>,
    pub healing: __sdk::__query_builder::Col<AoeRegion, f32>,
}

impl __sdk::__query_builder::HasCols for AoeRegion {
    type Cols = AoeRegionCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        AoeRegionCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            caster: __sdk::__query_builder::Col::new(table_name, "caster"),
            spell_id: __sdk::__query_builder::Col::new(table_name, "spell_id"),
            center: __sdk::__query_builder::Col::new(table_name, "center"),
            direction: __sdk::__query_builder::Col::new(table_name, "direction"),
            radius: __sdk::__query_builder::Col::new(table_name, "radius"),
            shape: __sdk::__query_builder::Col::new(table_name, "shape"),
            remaining_seconds: __sdk::__query_builder::Col::new(table_name, "remaining_seconds"),
            pending_delay_seconds: __sdk::__query_builder::Col::new(
                table_name,
                "pending_delay_seconds",
            ),
            affected: __sdk::__query_builder::Col::new(table_name, "affected"),
            damage: __sdk::__query_builder::Col::new(table_name, "damage"),
            healing: __sdk::__query_builder::Col::new(table_name, "healing"),
        }
    }
}

/// Indexed column accessor struct for the table `AoeRegion`.
///
/// Provides typed access to indexed columns for query building.
pub struct AoeRegionIxCols {
    pub id: __sdk::__query_builder::IxCol<AoeRegion, u64>,
}

impl __sdk::__query_builder::HasIxCols for AoeRegion {
    type IxCols = AoeRegionIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        AoeRegionIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for AoeRegion {}
