// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::aoe_region_type::AoeRegion;
use super::aoe_shape_row_type::AoeShapeRow;
use super::vec_3_row_type::Vec3Row;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `aoe_region`.
///
/// Obtain a handle from the [`AoeRegionTableAccess::aoe_region`] method on [`super::RemoteTables`],
/// like `ctx.db.aoe_region()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.aoe_region().on_insert(...)`.
pub struct AoeRegionTableHandle<'ctx> {
    imp: __sdk::TableHandle<AoeRegion>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `aoe_region`.
pub struct AoeRegionTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for AoeRegionTableAccessor {
    type Row = AoeRegion;
    type Handle<'db> = AoeRegionTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.aoe_region()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `aoe_region`.
///
/// Implemented for [`super::RemoteTables`].
pub trait AoeRegionTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`AoeRegionTableHandle`], which mediates access to the table `aoe_region`.
    fn aoe_region(&self) -> AoeRegionTableHandle<'_>;
}

impl AoeRegionTableAccess for super::RemoteTables {
    fn aoe_region(&self) -> AoeRegionTableHandle<'_> {
        AoeRegionTableHandle {
            imp: self.imp.get_table::<AoeRegion>("aoe_region"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct AoeRegionInsertCallbackId(__sdk::CallbackId);
pub struct AoeRegionDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for AoeRegionTableHandle<'ctx> {
    type Row = AoeRegion;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = AoeRegion> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for AoeRegionTableHandle<'ctx> {
    type Row = AoeRegion;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = AoeRegion> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = AoeRegionInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AoeRegionInsertCallbackId {
        AoeRegionInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: AoeRegionInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = AoeRegionDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AoeRegionDeleteCallbackId {
        AoeRegionDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: AoeRegionDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for AoeRegionTableHandle<'ctx> {
    type InsertCallbackId = AoeRegionInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AoeRegionInsertCallbackId {
        AoeRegionInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: AoeRegionInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for AoeRegionTableHandle<'ctx> {
    type DeleteCallbackId = AoeRegionDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AoeRegionDeleteCallbackId {
        AoeRegionDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: AoeRegionDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct AoeRegionUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for AoeRegionTableHandle<'ctx> {
    type UpdateCallbackId = AoeRegionUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> AoeRegionUpdateCallbackId {
        AoeRegionUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: AoeRegionUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for AoeRegionTableHandle<'ctx> {
    type UpdateCallbackId = AoeRegionUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> AoeRegionUpdateCallbackId {
        AoeRegionUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: AoeRegionUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `aoe_region`,
/// which allows point queries on the field of the same name
/// via the [`AoeRegionIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.aoe_region().id().find(...)`.
pub struct AoeRegionIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<AoeRegion, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> AoeRegionTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `aoe_region`.
    pub fn id(&self) -> AoeRegionIdUnique<'ctx> {
        AoeRegionIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> AoeRegionIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<AoeRegion> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<AoeRegion>("aoe_region");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<AoeRegion>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<AoeRegion>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `AoeRegion`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait aoe_regionQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `AoeRegion`.
    fn aoe_region(&self) -> __sdk::__query_builder::Table<AoeRegion>;
}

impl aoe_regionQueryTableAccess for __sdk::QueryTableAccessor {
    fn aoe_region(&self) -> __sdk::__query_builder::Table<AoeRegion> {
        __sdk::__query_builder::Table::new("aoe_region")
    }
}
