// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ApiKey {
    pub id: __sdk::Uuid,
    pub account_id: u64,
    pub key_hash: String,
    pub name: String,
    pub prefix: String,
    pub created_at: __sdk::Timestamp,
    pub last_used_at: Option<__sdk::Timestamp>,
}

impl __sdk::InModule for ApiKey {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `ApiKey`.
///
/// Provides typed access to columns for query building.
pub struct ApiKeyCols {
    pub id: __sdk::__query_builder::Col<ApiKey, __sdk::Uuid>,
    pub account_id: __sdk::__query_builder::Col<ApiKey, u64>,
    pub key_hash: __sdk::__query_builder::Col<ApiKey, String>,
    pub name: __sdk::__query_builder::Col<ApiKey, String>,
    pub prefix: __sdk::__query_builder::Col<ApiKey, String>,
    pub created_at: __sdk::__query_builder::Col<ApiKey, __sdk::Timestamp>,
    pub last_used_at: __sdk::__query_builder::Col<ApiKey, Option<__sdk::Timestamp>>,
}

impl __sdk::__query_builder::HasCols for ApiKey {
    type Cols = ApiKeyCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ApiKeyCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            account_id: __sdk::__query_builder::Col::new(table_name, "account_id"),
            key_hash: __sdk::__query_builder::Col::new(table_name, "key_hash"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            prefix: __sdk::__query_builder::Col::new(table_name, "prefix"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            last_used_at: __sdk::__query_builder::Col::new(table_name, "last_used_at"),
        }
    }
}

/// Indexed column accessor struct for the table `ApiKey`.
///
/// Provides typed access to indexed columns for query building.
pub struct ApiKeyIxCols {
    pub account_id: __sdk::__query_builder::IxCol<ApiKey, u64>,
    pub id: __sdk::__query_builder::IxCol<ApiKey, __sdk::Uuid>,
    pub key_hash: __sdk::__query_builder::IxCol<ApiKey, String>,
}

impl __sdk::__query_builder::HasIxCols for ApiKey {
    type IxCols = ApiKeyIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ApiKeyIxCols {
            account_id: __sdk::__query_builder::IxCol::new(table_name, "account_id"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            key_hash: __sdk::__query_builder::IxCol::new(table_name, "key_hash"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ApiKey {}
