// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::boss_phase_row_type::BossPhaseRow;
use super::boss_state_type::BossState;
use super::vec_3_row_type::Vec3Row;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `boss_state`.
///
/// Obtain a handle from the [`BossStateTableAccess::boss_state`] method on [`super::RemoteTables`],
/// like `ctx.db.boss_state()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.boss_state().on_insert(...)`.
pub struct BossStateTableHandle<'ctx> {
    imp: __sdk::TableHandle<BossState>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `boss_state`.
pub struct BossStateTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for BossStateTableAccessor {
    type Row = BossState;
    type Handle<'db> = BossStateTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.boss_state()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `boss_state`.
///
/// Implemented for [`super::RemoteTables`].
pub trait BossStateTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`BossStateTableHandle`], which mediates access to the table `boss_state`.
    fn boss_state(&self) -> BossStateTableHandle<'_>;
}

impl BossStateTableAccess for super::RemoteTables {
    fn boss_state(&self) -> BossStateTableHandle<'_> {
        BossStateTableHandle {
            imp: self.imp.get_table::<BossState>("boss_state"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct BossStateInsertCallbackId(__sdk::CallbackId);
pub struct BossStateDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for BossStateTableHandle<'ctx> {
    type Row = BossState;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = BossState> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for BossStateTableHandle<'ctx> {
    type Row = BossState;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = BossState> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = BossStateInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BossStateInsertCallbackId {
        BossStateInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: BossStateInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = BossStateDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BossStateDeleteCallbackId {
        BossStateDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: BossStateDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for BossStateTableHandle<'ctx> {
    type InsertCallbackId = BossStateInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BossStateInsertCallbackId {
        BossStateInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: BossStateInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for BossStateTableHandle<'ctx> {
    type DeleteCallbackId = BossStateDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BossStateDeleteCallbackId {
        BossStateDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: BossStateDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct BossStateUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for BossStateTableHandle<'ctx> {
    type UpdateCallbackId = BossStateUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> BossStateUpdateCallbackId {
        BossStateUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: BossStateUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for BossStateTableHandle<'ctx> {
    type UpdateCallbackId = BossStateUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> BossStateUpdateCallbackId {
        BossStateUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: BossStateUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `entity_id` unique index on the table `boss_state`,
/// which allows point queries on the field of the same name
/// via the [`BossStateEntityIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.boss_state().entity_id().find(...)`.
pub struct BossStateEntityIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<BossState, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> BossStateTableHandle<'ctx> {
    /// Get a handle on the `entity_id` unique index on the table `boss_state`.
    pub fn entity_id(&self) -> BossStateEntityIdUnique<'ctx> {
        BossStateEntityIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("entity_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> BossStateEntityIdUnique<'ctx> {
    /// Find the subscribed row whose `entity_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<BossState> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<BossState>("boss_state");
    _table.add_unique_constraint::<u64>("entity_id", |row| &row.entity_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<BossState>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<BossState>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `BossState`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait boss_stateQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `BossState`.
    fn boss_state(&self) -> __sdk::__query_builder::Table<BossState>;
}

impl boss_stateQueryTableAccess for __sdk::QueryTableAccessor {
    fn boss_state(&self) -> __sdk::__query_builder::Table<BossState> {
        __sdk::__query_builder::Table::new("boss_state")
    }
}
