// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::cast_kind_row_type::CastKindRow;
use super::cast_source_row_type::CastSourceRow;
use super::cast_state_type::CastState;
use super::vec_3_row_type::Vec3Row;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `cast_state`.
///
/// Obtain a handle from the [`CastStateTableAccess::cast_state`] method on [`super::RemoteTables`],
/// like `ctx.db.cast_state()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.cast_state().on_insert(...)`.
pub struct CastStateTableHandle<'ctx> {
    imp: __sdk::TableHandle<CastState>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `cast_state`.
pub struct CastStateTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for CastStateTableAccessor {
    type Row = CastState;
    type Handle<'db> = CastStateTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.cast_state()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `cast_state`.
///
/// Implemented for [`super::RemoteTables`].
pub trait CastStateTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`CastStateTableHandle`], which mediates access to the table `cast_state`.
    fn cast_state(&self) -> CastStateTableHandle<'_>;
}

impl CastStateTableAccess for super::RemoteTables {
    fn cast_state(&self) -> CastStateTableHandle<'_> {
        CastStateTableHandle {
            imp: self.imp.get_table::<CastState>("cast_state"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct CastStateInsertCallbackId(__sdk::CallbackId);
pub struct CastStateDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for CastStateTableHandle<'ctx> {
    type Row = CastState;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = CastState> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for CastStateTableHandle<'ctx> {
    type Row = CastState;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = CastState> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = CastStateInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CastStateInsertCallbackId {
        CastStateInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: CastStateInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = CastStateDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CastStateDeleteCallbackId {
        CastStateDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: CastStateDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for CastStateTableHandle<'ctx> {
    type InsertCallbackId = CastStateInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CastStateInsertCallbackId {
        CastStateInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: CastStateInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for CastStateTableHandle<'ctx> {
    type DeleteCallbackId = CastStateDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CastStateDeleteCallbackId {
        CastStateDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: CastStateDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct CastStateUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for CastStateTableHandle<'ctx> {
    type UpdateCallbackId = CastStateUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> CastStateUpdateCallbackId {
        CastStateUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: CastStateUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for CastStateTableHandle<'ctx> {
    type UpdateCallbackId = CastStateUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> CastStateUpdateCallbackId {
        CastStateUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: CastStateUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `entity_id` unique index on the table `cast_state`,
/// which allows point queries on the field of the same name
/// via the [`CastStateEntityIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.cast_state().entity_id().find(...)`.
pub struct CastStateEntityIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<CastState, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> CastStateTableHandle<'ctx> {
    /// Get a handle on the `entity_id` unique index on the table `cast_state`.
    pub fn entity_id(&self) -> CastStateEntityIdUnique<'ctx> {
        CastStateEntityIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("entity_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> CastStateEntityIdUnique<'ctx> {
    /// Find the subscribed row whose `entity_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<CastState> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<CastState>("cast_state");
    _table.add_unique_constraint::<u64>("entity_id", |row| &row.entity_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<CastState>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<CastState>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `CastState`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait cast_stateQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `CastState`.
    fn cast_state(&self) -> __sdk::__query_builder::Table<CastState>;
}

impl cast_stateQueryTableAccess for __sdk::QueryTableAccessor {
    fn cast_state(&self) -> __sdk::__query_builder::Table<CastState> {
        __sdk::__query_builder::Table::new("cast_state")
    }
}
