// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::vec_3_row_type::Vec3Row;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CastWeaponArgs {
    pub slot: String,
    pub target_entity: Option<u64>,
    pub target_position: Option<Vec3Row>,
}

impl From<CastWeaponArgs> for super::Reducer {
    fn from(args: CastWeaponArgs) -> Self {
        Self::CastWeapon {
            slot: args.slot,
            target_entity: args.target_entity,
            target_position: args.target_position,
        }
    }
}

impl __sdk::InModule for CastWeaponArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `cast_weapon`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait cast_weapon {
    /// Request that the remote module invoke the reducer `cast_weapon` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`cast_weapon:cast_weapon_then`] to run a callback after the reducer completes.
    fn cast_weapon(
        &self,
        slot: String,
        target_entity: Option<u64>,
        target_position: Option<Vec3Row>,
    ) -> __sdk::Result<()> {
        self.cast_weapon_then(slot, target_entity, target_position, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `cast_weapon` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn cast_weapon_then(
        &self,
        slot: String,
        target_entity: Option<u64>,
        target_position: Option<Vec3Row>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl cast_weapon for super::RemoteReducers {
    fn cast_weapon_then(
        &self,
        slot: String,
        target_entity: Option<u64>,
        target_position: Option<Vec3Row>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            CastWeaponArgs {
                slot,
                target_entity,
                target_position,
            },
            callback,
        )
    }
}
