// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::cast_kind_row_type::CastKindRow;
use super::vec_3_row_type::Vec3Row;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct CastState {
    pub entity_id: u64,
    pub spell_id: String,
    pub kind: CastKindRow,
    pub elapsed_seconds: f32,
    pub required_seconds: f32,
    pub start_position: Vec3Row,
    pub target_position: Option<Vec3Row>,
    pub target_entity: Option<u64>,
    pub channel_tick_accumulator: f32,
    pub tick_interval_seconds: f32,
}

impl __sdk::InModule for CastState {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `CastState`.
///
/// Provides typed access to columns for query building.
pub struct CastStateCols {
    pub entity_id: __sdk::__query_builder::Col<CastState, u64>,
    pub spell_id: __sdk::__query_builder::Col<CastState, String>,
    pub kind: __sdk::__query_builder::Col<CastState, CastKindRow>,
    pub elapsed_seconds: __sdk::__query_builder::Col<CastState, f32>,
    pub required_seconds: __sdk::__query_builder::Col<CastState, f32>,
    pub start_position: __sdk::__query_builder::Col<CastState, Vec3Row>,
    pub target_position: __sdk::__query_builder::Col<CastState, Option<Vec3Row>>,
    pub target_entity: __sdk::__query_builder::Col<CastState, Option<u64>>,
    pub channel_tick_accumulator: __sdk::__query_builder::Col<CastState, f32>,
    pub tick_interval_seconds: __sdk::__query_builder::Col<CastState, f32>,
}

impl __sdk::__query_builder::HasCols for CastState {
    type Cols = CastStateCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        CastStateCols {
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
            spell_id: __sdk::__query_builder::Col::new(table_name, "spell_id"),
            kind: __sdk::__query_builder::Col::new(table_name, "kind"),
            elapsed_seconds: __sdk::__query_builder::Col::new(table_name, "elapsed_seconds"),
            required_seconds: __sdk::__query_builder::Col::new(table_name, "required_seconds"),
            start_position: __sdk::__query_builder::Col::new(table_name, "start_position"),
            target_position: __sdk::__query_builder::Col::new(table_name, "target_position"),
            target_entity: __sdk::__query_builder::Col::new(table_name, "target_entity"),
            channel_tick_accumulator: __sdk::__query_builder::Col::new(
                table_name,
                "channel_tick_accumulator",
            ),
            tick_interval_seconds: __sdk::__query_builder::Col::new(
                table_name,
                "tick_interval_seconds",
            ),
        }
    }
}

/// Indexed column accessor struct for the table `CastState`.
///
/// Provides typed access to indexed columns for query building.
pub struct CastStateIxCols {
    pub entity_id: __sdk::__query_builder::IxCol<CastState, u64>,
}

impl __sdk::__query_builder::HasIxCols for CastState {
    type IxCols = CastStateIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        CastStateIxCols {
            entity_id: __sdk::__query_builder::IxCol::new(table_name, "entity_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for CastState {}
