// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ClaimNpcItemArgs {
    pub npc_entity_id: u64,
    pub item_id: String,
}

impl From<ClaimNpcItemArgs> for super::Reducer {
    fn from(args: ClaimNpcItemArgs) -> Self {
        Self::ClaimNpcItem {
            npc_entity_id: args.npc_entity_id,
            item_id: args.item_id,
        }
    }
}

impl __sdk::InModule for ClaimNpcItemArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `claim_npc_item`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait claim_npc_item {
    /// Request that the remote module invoke the reducer `claim_npc_item` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`claim_npc_item:claim_npc_item_then`] to run a callback after the reducer completes.
    fn claim_npc_item(&self, npc_entity_id: u64, item_id: String) -> __sdk::Result<()> {
        self.claim_npc_item_then(npc_entity_id, item_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `claim_npc_item` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn claim_npc_item_then(
        &self,
        npc_entity_id: u64,
        item_id: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl claim_npc_item for super::RemoteReducers {
    fn claim_npc_item_then(
        &self,
        npc_entity_id: u64,
        item_id: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            ClaimNpcItemArgs {
                npc_entity_id,
                item_id,
            },
            callback,
        )
    }
}
