// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::craft_session_type::CraftSession;
use super::vec_3_row_type::Vec3Row;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `craft_session`.
///
/// Obtain a handle from the [`CraftSessionTableAccess::craft_session`] method on [`super::RemoteTables`],
/// like `ctx.db.craft_session()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.craft_session().on_insert(...)`.
pub struct CraftSessionTableHandle<'ctx> {
    imp: __sdk::TableHandle<CraftSession>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `craft_session`.
pub struct CraftSessionTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for CraftSessionTableAccessor {
    type Row = CraftSession;
    type Handle<'db> = CraftSessionTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.craft_session()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `craft_session`.
///
/// Implemented for [`super::RemoteTables`].
pub trait CraftSessionTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`CraftSessionTableHandle`], which mediates access to the table `craft_session`.
    fn craft_session(&self) -> CraftSessionTableHandle<'_>;
}

impl CraftSessionTableAccess for super::RemoteTables {
    fn craft_session(&self) -> CraftSessionTableHandle<'_> {
        CraftSessionTableHandle {
            imp: self.imp.get_table::<CraftSession>("craft_session"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct CraftSessionInsertCallbackId(__sdk::CallbackId);
pub struct CraftSessionDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for CraftSessionTableHandle<'ctx> {
    type Row = CraftSession;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = CraftSession> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for CraftSessionTableHandle<'ctx> {
    type Row = CraftSession;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = CraftSession> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = CraftSessionInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CraftSessionInsertCallbackId {
        CraftSessionInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: CraftSessionInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = CraftSessionDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CraftSessionDeleteCallbackId {
        CraftSessionDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: CraftSessionDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for CraftSessionTableHandle<'ctx> {
    type InsertCallbackId = CraftSessionInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CraftSessionInsertCallbackId {
        CraftSessionInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: CraftSessionInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for CraftSessionTableHandle<'ctx> {
    type DeleteCallbackId = CraftSessionDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CraftSessionDeleteCallbackId {
        CraftSessionDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: CraftSessionDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct CraftSessionUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for CraftSessionTableHandle<'ctx> {
    type UpdateCallbackId = CraftSessionUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> CraftSessionUpdateCallbackId {
        CraftSessionUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: CraftSessionUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for CraftSessionTableHandle<'ctx> {
    type UpdateCallbackId = CraftSessionUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> CraftSessionUpdateCallbackId {
        CraftSessionUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: CraftSessionUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `entity_id` unique index on the table `craft_session`,
/// which allows point queries on the field of the same name
/// via the [`CraftSessionEntityIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.craft_session().entity_id().find(...)`.
pub struct CraftSessionEntityIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<CraftSession, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> CraftSessionTableHandle<'ctx> {
    /// Get a handle on the `entity_id` unique index on the table `craft_session`.
    pub fn entity_id(&self) -> CraftSessionEntityIdUnique<'ctx> {
        CraftSessionEntityIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("entity_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> CraftSessionEntityIdUnique<'ctx> {
    /// Find the subscribed row whose `entity_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<CraftSession> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<CraftSession>("craft_session");
    _table.add_unique_constraint::<u64>("entity_id", |row| &row.entity_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<CraftSession>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<CraftSession>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `CraftSession`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait craft_sessionQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `CraftSession`.
    fn craft_session(&self) -> __sdk::__query_builder::Table<CraftSession>;
}

impl craft_sessionQueryTableAccess for __sdk::QueryTableAccessor {
    fn craft_session(&self) -> __sdk::__query_builder::Table<CraftSession> {
        __sdk::__query_builder::Table::new("craft_session")
    }
}
