// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct DamageEventRow {
    pub target: u64,
    pub amount: f32,
    pub is_healing: bool,
    pub killed: bool,
}

impl __sdk::InModule for DamageEventRow {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `DamageEventRow`.
///
/// Provides typed access to columns for query building.
pub struct DamageEventRowCols {
    pub target: __sdk::__query_builder::Col<DamageEventRow, u64>,
    pub amount: __sdk::__query_builder::Col<DamageEventRow, f32>,
    pub is_healing: __sdk::__query_builder::Col<DamageEventRow, bool>,
    pub killed: __sdk::__query_builder::Col<DamageEventRow, bool>,
}

impl __sdk::__query_builder::HasCols for DamageEventRow {
    type Cols = DamageEventRowCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        DamageEventRowCols {
            target: __sdk::__query_builder::Col::new(table_name, "target"),
            amount: __sdk::__query_builder::Col::new(table_name, "amount"),
            is_healing: __sdk::__query_builder::Col::new(table_name, "is_healing"),
            killed: __sdk::__query_builder::Col::new(table_name, "killed"),
        }
    }
}

/// Indexed column accessor struct for the table `DamageEventRow`.
///
/// Provides typed access to indexed columns for query building.
pub struct DamageEventRowIxCols {}

impl __sdk::__query_builder::HasIxCols for DamageEventRow {
    type IxCols = DamageEventRowIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        DamageEventRowIxCols {}
    }
}
