// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::equipment_table_type::EquipmentTable;
use super::item_instance_row_type::ItemInstanceRow;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `equipment`.
///
/// Obtain a handle from the [`EquipmentTableAccess::equipment`] method on [`super::RemoteTables`],
/// like `ctx.db.equipment()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.equipment().on_insert(...)`.
pub struct EquipmentTableHandle<'ctx> {
    imp: __sdk::TableHandle<EquipmentTable>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `equipment`.
pub struct EquipmentTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for EquipmentTableAccessor {
    type Row = EquipmentTable;
    type Handle<'db> = EquipmentTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.equipment()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `equipment`.
///
/// Implemented for [`super::RemoteTables`].
pub trait EquipmentTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`EquipmentTableHandle`], which mediates access to the table `equipment`.
    fn equipment(&self) -> EquipmentTableHandle<'_>;
}

impl EquipmentTableAccess for super::RemoteTables {
    fn equipment(&self) -> EquipmentTableHandle<'_> {
        EquipmentTableHandle {
            imp: self.imp.get_table::<EquipmentTable>("equipment"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct EquipmentInsertCallbackId(__sdk::CallbackId);
pub struct EquipmentDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for EquipmentTableHandle<'ctx> {
    type Row = EquipmentTable;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = EquipmentTable> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for EquipmentTableHandle<'ctx> {
    type Row = EquipmentTable;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = EquipmentTable> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = EquipmentInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> EquipmentInsertCallbackId {
        EquipmentInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: EquipmentInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = EquipmentDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> EquipmentDeleteCallbackId {
        EquipmentDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: EquipmentDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for EquipmentTableHandle<'ctx> {
    type InsertCallbackId = EquipmentInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> EquipmentInsertCallbackId {
        EquipmentInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: EquipmentInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for EquipmentTableHandle<'ctx> {
    type DeleteCallbackId = EquipmentDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> EquipmentDeleteCallbackId {
        EquipmentDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: EquipmentDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct EquipmentUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for EquipmentTableHandle<'ctx> {
    type UpdateCallbackId = EquipmentUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> EquipmentUpdateCallbackId {
        EquipmentUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: EquipmentUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for EquipmentTableHandle<'ctx> {
    type UpdateCallbackId = EquipmentUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> EquipmentUpdateCallbackId {
        EquipmentUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: EquipmentUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `identity` unique index on the table `equipment`,
/// which allows point queries on the field of the same name
/// via the [`EquipmentIdentityUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.equipment().identity().find(...)`.
pub struct EquipmentIdentityUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<EquipmentTable, __sdk::Identity>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> EquipmentTableHandle<'ctx> {
    /// Get a handle on the `identity` unique index on the table `equipment`.
    pub fn identity(&self) -> EquipmentIdentityUnique<'ctx> {
        EquipmentIdentityUnique {
            imp: self
                .imp
                .get_unique_constraint::<__sdk::Identity>("identity"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> EquipmentIdentityUnique<'ctx> {
    /// Find the subscribed row whose `identity` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &__sdk::Identity) -> Option<EquipmentTable> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<EquipmentTable>("equipment");
    _table.add_unique_constraint::<__sdk::Identity>("identity", |row| &row.identity);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<EquipmentTable>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<EquipmentTable>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `EquipmentTable`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait equipmentQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `EquipmentTable`.
    fn equipment(&self) -> __sdk::__query_builder::Table<EquipmentTable>;
}

impl equipmentQueryTableAccess for __sdk::QueryTableAccessor {
    fn equipment(&self) -> __sdk::__query_builder::Table<EquipmentTable> {
        __sdk::__query_builder::Table::new("equipment")
    }
}
