// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::item_instance_row_type::ItemInstanceRow;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct EquipmentTable {
    pub identity: __sdk::Identity,
    pub slots: Vec<Option<ItemInstanceRow>>,
}

impl __sdk::InModule for EquipmentTable {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `EquipmentTable`.
///
/// Provides typed access to columns for query building.
pub struct EquipmentTableCols {
    pub identity: __sdk::__query_builder::Col<EquipmentTable, __sdk::Identity>,
    pub slots: __sdk::__query_builder::Col<EquipmentTable, Vec<Option<ItemInstanceRow>>>,
}

impl __sdk::__query_builder::HasCols for EquipmentTable {
    type Cols = EquipmentTableCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        EquipmentTableCols {
            identity: __sdk::__query_builder::Col::new(table_name, "identity"),
            slots: __sdk::__query_builder::Col::new(table_name, "slots"),
        }
    }
}

/// Indexed column accessor struct for the table `EquipmentTable`.
///
/// Provides typed access to indexed columns for query building.
pub struct EquipmentTableIxCols {
    pub identity: __sdk::__query_builder::IxCol<EquipmentTable, __sdk::Identity>,
}

impl __sdk::__query_builder::HasIxCols for EquipmentTable {
    type IxCols = EquipmentTableIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        EquipmentTableIxCols {
            identity: __sdk::__query_builder::IxCol::new(table_name, "identity"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for EquipmentTable {}
