// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::vec_3_row_type::Vec3Row;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct GatherSession {
    pub entity_id: u64,
    pub node_entity_id: u64,
    pub placement_id: String,
    pub elapsed_seconds: f32,
    pub required_seconds: f32,
    pub start_position: Vec3Row,
}

impl __sdk::InModule for GatherSession {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `GatherSession`.
///
/// Provides typed access to columns for query building.
pub struct GatherSessionCols {
    pub entity_id: __sdk::__query_builder::Col<GatherSession, u64>,
    pub node_entity_id: __sdk::__query_builder::Col<GatherSession, u64>,
    pub placement_id: __sdk::__query_builder::Col<GatherSession, String>,
    pub elapsed_seconds: __sdk::__query_builder::Col<GatherSession, f32>,
    pub required_seconds: __sdk::__query_builder::Col<GatherSession, f32>,
    pub start_position: __sdk::__query_builder::Col<GatherSession, Vec3Row>,
}

impl __sdk::__query_builder::HasCols for GatherSession {
    type Cols = GatherSessionCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        GatherSessionCols {
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
            node_entity_id: __sdk::__query_builder::Col::new(table_name, "node_entity_id"),
            placement_id: __sdk::__query_builder::Col::new(table_name, "placement_id"),
            elapsed_seconds: __sdk::__query_builder::Col::new(table_name, "elapsed_seconds"),
            required_seconds: __sdk::__query_builder::Col::new(table_name, "required_seconds"),
            start_position: __sdk::__query_builder::Col::new(table_name, "start_position"),
        }
    }
}

/// Indexed column accessor struct for the table `GatherSession`.
///
/// Provides typed access to indexed columns for query building.
pub struct GatherSessionIxCols {
    pub entity_id: __sdk::__query_builder::IxCol<GatherSession, u64>,
}

impl __sdk::__query_builder::HasIxCols for GatherSession {
    type IxCols = GatherSessionIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        GatherSessionIxCols {
            entity_id: __sdk::__query_builder::IxCol::new(table_name, "entity_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for GatherSession {}
