// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct GmClearPropOverrideArgs {
    pub map_id: String,
    pub prop_id: String,
}

impl From<GmClearPropOverrideArgs> for super::Reducer {
    fn from(args: GmClearPropOverrideArgs) -> Self {
        Self::GmClearPropOverride {
            map_id: args.map_id,
            prop_id: args.prop_id,
        }
    }
}

impl __sdk::InModule for GmClearPropOverrideArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `gm_clear_prop_override`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait gm_clear_prop_override {
    /// Request that the remote module invoke the reducer `gm_clear_prop_override` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`gm_clear_prop_override:gm_clear_prop_override_then`] to run a callback after the reducer completes.
    fn gm_clear_prop_override(&self, map_id: String, prop_id: String) -> __sdk::Result<()> {
        self.gm_clear_prop_override_then(map_id, prop_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `gm_clear_prop_override` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn gm_clear_prop_override_then(
        &self,
        map_id: String,
        prop_id: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl gm_clear_prop_override for super::RemoteReducers {
    fn gm_clear_prop_override_then(
        &self,
        map_id: String,
        prop_id: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(GmClearPropOverrideArgs { map_id, prop_id }, callback)
    }
}
