// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct GmGrantGoldArgs {
    pub display_name: String,
    pub amount: u64,
}

impl From<GmGrantGoldArgs> for super::Reducer {
    fn from(args: GmGrantGoldArgs) -> Self {
        Self::GmGrantGold {
            display_name: args.display_name,
            amount: args.amount,
        }
    }
}

impl __sdk::InModule for GmGrantGoldArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `gm_grant_gold`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait gm_grant_gold {
    /// Request that the remote module invoke the reducer `gm_grant_gold` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`gm_grant_gold:gm_grant_gold_then`] to run a callback after the reducer completes.
    fn gm_grant_gold(&self, display_name: String, amount: u64) -> __sdk::Result<()> {
        self.gm_grant_gold_then(display_name, amount, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `gm_grant_gold` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn gm_grant_gold_then(
        &self,
        display_name: String,
        amount: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl gm_grant_gold for super::RemoteReducers {
    fn gm_grant_gold_then(
        &self,
        display_name: String,
        amount: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            GmGrantGoldArgs {
                display_name,
                amount,
            },
            callback,
        )
    }
}
