// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::vec_3_row_type::Vec3Row;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct GmSetPropOverrideArgs {
    pub map_id: String,
    pub prop_id: String,
    pub position: Option<Vec3Row>,
    pub rotation_y: Option<f32>,
    pub scale: Option<Vec3Row>,
    pub removed: bool,
}

impl From<GmSetPropOverrideArgs> for super::Reducer {
    fn from(args: GmSetPropOverrideArgs) -> Self {
        Self::GmSetPropOverride {
            map_id: args.map_id,
            prop_id: args.prop_id,
            position: args.position,
            rotation_y: args.rotation_y,
            scale: args.scale,
            removed: args.removed,
        }
    }
}

impl __sdk::InModule for GmSetPropOverrideArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `gm_set_prop_override`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait gm_set_prop_override {
    /// Request that the remote module invoke the reducer `gm_set_prop_override` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`gm_set_prop_override:gm_set_prop_override_then`] to run a callback after the reducer completes.
    fn gm_set_prop_override(
        &self,
        map_id: String,
        prop_id: String,
        position: Option<Vec3Row>,
        rotation_y: Option<f32>,
        scale: Option<Vec3Row>,
        removed: bool,
    ) -> __sdk::Result<()> {
        self.gm_set_prop_override_then(
            map_id,
            prop_id,
            position,
            rotation_y,
            scale,
            removed,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `gm_set_prop_override` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn gm_set_prop_override_then(
        &self,
        map_id: String,
        prop_id: String,
        position: Option<Vec3Row>,
        rotation_y: Option<f32>,
        scale: Option<Vec3Row>,
        removed: bool,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl gm_set_prop_override for super::RemoteReducers {
    fn gm_set_prop_override_then(
        &self,
        map_id: String,
        prop_id: String,
        position: Option<Vec3Row>,
        rotation_y: Option<f32>,
        scale: Option<Vec3Row>,
        removed: bool,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            GmSetPropOverrideArgs {
                map_id,
                prop_id,
                position,
                rotation_y,
                scale,
                removed,
            },
            callback,
        )
    }
}
