// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::hotbar_row_type::HotbarRow;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Hotbar {
    pub identity: __sdk::Identity,
    pub slots: HotbarRow,
}

impl __sdk::InModule for Hotbar {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Hotbar`.
///
/// Provides typed access to columns for query building.
pub struct HotbarCols {
    pub identity: __sdk::__query_builder::Col<Hotbar, __sdk::Identity>,
    pub slots: __sdk::__query_builder::Col<Hotbar, HotbarRow>,
}

impl __sdk::__query_builder::HasCols for Hotbar {
    type Cols = HotbarCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        HotbarCols {
            identity: __sdk::__query_builder::Col::new(table_name, "identity"),
            slots: __sdk::__query_builder::Col::new(table_name, "slots"),
        }
    }
}

/// Indexed column accessor struct for the table `Hotbar`.
///
/// Provides typed access to indexed columns for query building.
pub struct HotbarIxCols {
    pub identity: __sdk::__query_builder::IxCol<Hotbar, __sdk::Identity>,
}

impl __sdk::__query_builder::HasIxCols for Hotbar {
    type IxCols = HotbarIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        HotbarIxCols {
            identity: __sdk::__query_builder::IxCol::new(table_name, "identity"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Hotbar {}
