// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::known_glyphs_table_type::KnownGlyphsTable;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `known_glyphs`.
///
/// Obtain a handle from the [`KnownGlyphsTableAccess::known_glyphs`] method on [`super::RemoteTables`],
/// like `ctx.db.known_glyphs()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.known_glyphs().on_insert(...)`.
pub struct KnownGlyphsTableHandle<'ctx> {
    imp: __sdk::TableHandle<KnownGlyphsTable>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `known_glyphs`.
pub struct KnownGlyphsTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for KnownGlyphsTableAccessor {
    type Row = KnownGlyphsTable;
    type Handle<'db> = KnownGlyphsTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.known_glyphs()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `known_glyphs`.
///
/// Implemented for [`super::RemoteTables`].
pub trait KnownGlyphsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`KnownGlyphsTableHandle`], which mediates access to the table `known_glyphs`.
    fn known_glyphs(&self) -> KnownGlyphsTableHandle<'_>;
}

impl KnownGlyphsTableAccess for super::RemoteTables {
    fn known_glyphs(&self) -> KnownGlyphsTableHandle<'_> {
        KnownGlyphsTableHandle {
            imp: self.imp.get_table::<KnownGlyphsTable>("known_glyphs"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct KnownGlyphsInsertCallbackId(__sdk::CallbackId);
pub struct KnownGlyphsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for KnownGlyphsTableHandle<'ctx> {
    type Row = KnownGlyphsTable;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = KnownGlyphsTable> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for KnownGlyphsTableHandle<'ctx> {
    type Row = KnownGlyphsTable;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = KnownGlyphsTable> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = KnownGlyphsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> KnownGlyphsInsertCallbackId {
        KnownGlyphsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: KnownGlyphsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = KnownGlyphsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> KnownGlyphsDeleteCallbackId {
        KnownGlyphsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: KnownGlyphsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for KnownGlyphsTableHandle<'ctx> {
    type InsertCallbackId = KnownGlyphsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> KnownGlyphsInsertCallbackId {
        KnownGlyphsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: KnownGlyphsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for KnownGlyphsTableHandle<'ctx> {
    type DeleteCallbackId = KnownGlyphsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> KnownGlyphsDeleteCallbackId {
        KnownGlyphsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: KnownGlyphsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct KnownGlyphsUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for KnownGlyphsTableHandle<'ctx> {
    type UpdateCallbackId = KnownGlyphsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> KnownGlyphsUpdateCallbackId {
        KnownGlyphsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: KnownGlyphsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for KnownGlyphsTableHandle<'ctx> {
    type UpdateCallbackId = KnownGlyphsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> KnownGlyphsUpdateCallbackId {
        KnownGlyphsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: KnownGlyphsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<KnownGlyphsTable>("known_glyphs");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<KnownGlyphsTable>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<KnownGlyphsTable>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `KnownGlyphsTable`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait known_glyphsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `KnownGlyphsTable`.
    fn known_glyphs(&self) -> __sdk::__query_builder::Table<KnownGlyphsTable>;
}

impl known_glyphsQueryTableAccess for __sdk::QueryTableAccessor {
    fn known_glyphs(&self) -> __sdk::__query_builder::Table<KnownGlyphsTable> {
        __sdk::__query_builder::Table::new("known_glyphs")
    }
}
