// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct KnownAncientLanguageTable {
    pub identity: __sdk::Identity,
    pub root_words: Vec<String>,
    pub ancient_words: Vec<String>,
    pub base_abilities: Vec<String>,
}

impl __sdk::InModule for KnownAncientLanguageTable {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `KnownAncientLanguageTable`.
///
/// Provides typed access to columns for query building.
pub struct KnownAncientLanguageTableCols {
    pub identity: __sdk::__query_builder::Col<KnownAncientLanguageTable, __sdk::Identity>,
    pub root_words: __sdk::__query_builder::Col<KnownAncientLanguageTable, Vec<String>>,
    pub ancient_words: __sdk::__query_builder::Col<KnownAncientLanguageTable, Vec<String>>,
    pub base_abilities: __sdk::__query_builder::Col<KnownAncientLanguageTable, Vec<String>>,
}

impl __sdk::__query_builder::HasCols for KnownAncientLanguageTable {
    type Cols = KnownAncientLanguageTableCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        KnownAncientLanguageTableCols {
            identity: __sdk::__query_builder::Col::new(table_name, "identity"),
            root_words: __sdk::__query_builder::Col::new(table_name, "root_words"),
            ancient_words: __sdk::__query_builder::Col::new(table_name, "ancient_words"),
            base_abilities: __sdk::__query_builder::Col::new(table_name, "base_abilities"),
        }
    }
}

/// Indexed column accessor struct for the table `KnownAncientLanguageTable`.
///
/// Provides typed access to indexed columns for query building.
pub struct KnownAncientLanguageTableIxCols {
    pub identity: __sdk::__query_builder::IxCol<KnownAncientLanguageTable, __sdk::Identity>,
}

impl __sdk::__query_builder::HasIxCols for KnownAncientLanguageTable {
    type IxCols = KnownAncientLanguageTableIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        KnownAncientLanguageTableIxCols {
            identity: __sdk::__query_builder::IxCol::new(table_name, "identity"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for KnownAncientLanguageTable {}
