// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::item_instance_row_type::ItemInstanceRow;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct MarketSellOrder {
    pub id: u64,
    pub market_id: String,
    pub seller_character_id: __sdk::Uuid,
    pub item_id: String,
    pub item: ItemInstanceRow,
    pub price_gold: u64,
    pub created_at: __sdk::Timestamp,
}

impl __sdk::InModule for MarketSellOrder {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `MarketSellOrder`.
///
/// Provides typed access to columns for query building.
pub struct MarketSellOrderCols {
    pub id: __sdk::__query_builder::Col<MarketSellOrder, u64>,
    pub market_id: __sdk::__query_builder::Col<MarketSellOrder, String>,
    pub seller_character_id: __sdk::__query_builder::Col<MarketSellOrder, __sdk::Uuid>,
    pub item_id: __sdk::__query_builder::Col<MarketSellOrder, String>,
    pub item: __sdk::__query_builder::Col<MarketSellOrder, ItemInstanceRow>,
    pub price_gold: __sdk::__query_builder::Col<MarketSellOrder, u64>,
    pub created_at: __sdk::__query_builder::Col<MarketSellOrder, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for MarketSellOrder {
    type Cols = MarketSellOrderCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        MarketSellOrderCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            market_id: __sdk::__query_builder::Col::new(table_name, "market_id"),
            seller_character_id: __sdk::__query_builder::Col::new(
                table_name,
                "seller_character_id",
            ),
            item_id: __sdk::__query_builder::Col::new(table_name, "item_id"),
            item: __sdk::__query_builder::Col::new(table_name, "item"),
            price_gold: __sdk::__query_builder::Col::new(table_name, "price_gold"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
        }
    }
}

/// Indexed column accessor struct for the table `MarketSellOrder`.
///
/// Provides typed access to indexed columns for query building.
pub struct MarketSellOrderIxCols {
    pub id: __sdk::__query_builder::IxCol<MarketSellOrder, u64>,
    pub seller_character_id: __sdk::__query_builder::IxCol<MarketSellOrder, __sdk::Uuid>,
}

impl __sdk::__query_builder::HasIxCols for MarketSellOrder {
    type IxCols = MarketSellOrderIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        MarketSellOrderIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            seller_character_id: __sdk::__query_builder::IxCol::new(
                table_name,
                "seller_character_id",
            ),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for MarketSellOrder {}
