// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Market {
    pub id: String,
    pub display_name: String,
    pub fee_bps: u16,
}

impl __sdk::InModule for Market {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Market`.
///
/// Provides typed access to columns for query building.
pub struct MarketCols {
    pub id: __sdk::__query_builder::Col<Market, String>,
    pub display_name: __sdk::__query_builder::Col<Market, String>,
    pub fee_bps: __sdk::__query_builder::Col<Market, u16>,
}

impl __sdk::__query_builder::HasCols for Market {
    type Cols = MarketCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        MarketCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            display_name: __sdk::__query_builder::Col::new(table_name, "display_name"),
            fee_bps: __sdk::__query_builder::Col::new(table_name, "fee_bps"),
        }
    }
}

/// Indexed column accessor struct for the table `Market`.
///
/// Provides typed access to indexed columns for query building.
pub struct MarketIxCols {
    pub id: __sdk::__query_builder::IxCol<Market, String>,
}

impl __sdk::__query_builder::HasIxCols for Market {
    type IxCols = MarketIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        MarketIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Market {}
