// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::item_instance_row_type::ItemInstanceRow;
use super::market_sell_order_type::MarketSellOrder;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `market_sell_order`.
///
/// Obtain a handle from the [`MarketSellOrderTableAccess::market_sell_order`] method on [`super::RemoteTables`],
/// like `ctx.db.market_sell_order()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.market_sell_order().on_insert(...)`.
pub struct MarketSellOrderTableHandle<'ctx> {
    imp: __sdk::TableHandle<MarketSellOrder>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `market_sell_order`.
pub struct MarketSellOrderTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for MarketSellOrderTableAccessor {
    type Row = MarketSellOrder;
    type Handle<'db> = MarketSellOrderTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.market_sell_order()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `market_sell_order`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MarketSellOrderTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MarketSellOrderTableHandle`], which mediates access to the table `market_sell_order`.
    fn market_sell_order(&self) -> MarketSellOrderTableHandle<'_>;
}

impl MarketSellOrderTableAccess for super::RemoteTables {
    fn market_sell_order(&self) -> MarketSellOrderTableHandle<'_> {
        MarketSellOrderTableHandle {
            imp: self.imp.get_table::<MarketSellOrder>("market_sell_order"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MarketSellOrderInsertCallbackId(__sdk::CallbackId);
pub struct MarketSellOrderDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for MarketSellOrderTableHandle<'ctx> {
    type Row = MarketSellOrder;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = MarketSellOrder> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for MarketSellOrderTableHandle<'ctx> {
    type Row = MarketSellOrder;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = MarketSellOrder> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MarketSellOrderInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MarketSellOrderInsertCallbackId {
        MarketSellOrderInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MarketSellOrderInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MarketSellOrderDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MarketSellOrderDeleteCallbackId {
        MarketSellOrderDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MarketSellOrderDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for MarketSellOrderTableHandle<'ctx> {
    type InsertCallbackId = MarketSellOrderInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MarketSellOrderInsertCallbackId {
        MarketSellOrderInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MarketSellOrderInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for MarketSellOrderTableHandle<'ctx> {
    type DeleteCallbackId = MarketSellOrderDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MarketSellOrderDeleteCallbackId {
        MarketSellOrderDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MarketSellOrderDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct MarketSellOrderUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for MarketSellOrderTableHandle<'ctx> {
    type UpdateCallbackId = MarketSellOrderUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> MarketSellOrderUpdateCallbackId {
        MarketSellOrderUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: MarketSellOrderUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for MarketSellOrderTableHandle<'ctx> {
    type UpdateCallbackId = MarketSellOrderUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> MarketSellOrderUpdateCallbackId {
        MarketSellOrderUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: MarketSellOrderUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `market_sell_order`,
/// which allows point queries on the field of the same name
/// via the [`MarketSellOrderIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.market_sell_order().id().find(...)`.
pub struct MarketSellOrderIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<MarketSellOrder, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> MarketSellOrderTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `market_sell_order`.
    pub fn id(&self) -> MarketSellOrderIdUnique<'ctx> {
        MarketSellOrderIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> MarketSellOrderIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<MarketSellOrder> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<MarketSellOrder>("market_sell_order");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<MarketSellOrder>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<MarketSellOrder>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `MarketSellOrder`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait market_sell_orderQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `MarketSellOrder`.
    fn market_sell_order(&self) -> __sdk::__query_builder::Table<MarketSellOrder>;
}

impl market_sell_orderQueryTableAccess for __sdk::QueryTableAccessor {
    fn market_sell_order(&self) -> __sdk::__query_builder::Table<MarketSellOrder> {
        __sdk::__query_builder::Table::new("market_sell_order")
    }
}
