// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.8.1 (commit 4d9aa49594d59bf09f949b83c30413e43bf0805a).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

pub mod ability_selection_row_type;
pub mod active_status_table;
pub mod active_status_type;
pub mod aoe_region_table;
pub mod aoe_region_type;
pub mod aoe_shape_row_type;
pub mod aoe_targeting_row_type;
pub mod armor_cast_reducer;
pub mod armor_inscription_row_type;
pub mod award_resonance_xp_reducer;
pub mod boss_phase_row_type;
pub mod boss_state_table;
pub mod boss_state_type;
pub mod cast_ended_event_type;
pub mod cast_ended_table;
pub mod cast_kind_row_type;
pub mod cast_source_row_type;
pub mod cast_spell_reducer;
pub mod cast_state_table;
pub mod cast_state_type;
pub mod claim_npc_item_reducer;
pub mod color_row_type;
pub mod cooldown_table;
pub mod cooldown_type;
pub mod crowd_control_kind_row_type;
pub mod crowd_control_table;
pub mod crowd_control_type;
pub mod damage_event_row_type;
pub mod damage_event_table;
pub mod destroy_item_reducer;
pub mod effect_payload_filter_row_type;
pub mod effect_payload_kind_row_type;
pub mod effect_payload_row_type;
pub mod effect_payload_selection_row_type;
pub mod eidolon_cast_reducer;
pub mod entity_kind_row_type;
pub mod entity_state_row_type;
pub mod entity_stats_table;
pub mod entity_stats_type;
pub mod equip_item_reducer;
pub mod equipment_table;
pub mod equipment_table_type;
pub mod game_entity_table;
pub mod game_entity_type;
pub mod gm_clear_prop_override_reducer;
pub mod gm_reseed_world_reducer;
pub mod gm_set_prop_override_reducer;
pub mod heartbeat_reducer;
pub mod hotbar_row_type;
pub mod hotbar_table;
pub mod hotbar_type;
pub mod inscription_row_type;
pub mod inventory_table;
pub mod inventory_table_type;
pub mod item_instance_row_type;
pub mod join_reducer;
pub mod known_ancient_language_table;
pub mod known_ancient_language_table_type;
pub mod known_glyphs_table;
pub mod known_glyphs_table_type;
pub mod leave_reducer;
pub mod modifier_kind_row_type;
pub mod move_item_reducer;
pub mod move_to_reducer;
pub mod periodic_effect_table;
pub mod periodic_effect_type;
pub mod player_message_event_type;
pub mod player_message_table;
pub mod player_stats_table;
pub mod player_stats_type;
pub mod player_table;
pub mod player_type;
pub mod projectile_table;
pub mod projectile_type;
pub mod prop_override_table;
pub mod prop_override_type;
pub mod release_cast_reducer;
pub mod resonance_table;
pub mod resonance_type;
pub mod respawn_reducer;
pub mod secondary_word_row_type;
pub mod set_ability_selection_reducer;
pub mod set_armor_inscription_reducer;
pub mod set_hotbar_spell_reducer;
pub mod set_inscription_reducer;
pub mod set_resonance_xp_reducer;
pub mod set_root_inscription_reducer;
pub mod slot_inscription_row_type;
pub mod spell_visual_effect_event_type;
pub mod spell_visual_effect_table;
pub mod stat_modifier_table;
pub mod stat_modifier_type;
pub mod stats_row_type;
pub mod stop_reducer;
pub mod threat_table;
pub mod threat_type;
pub mod tick_schedule_type;
pub mod tick_stats_table;
pub mod tick_stats_type;
pub mod unequip_item_reducer;
pub mod vec_3_row_type;
pub mod weapon_inscription_row_type;
pub mod weapon_inscriptions_row_type;

pub use ability_selection_row_type::AbilitySelectionRow;
pub use active_status_table::*;
pub use active_status_type::ActiveStatus;
pub use aoe_region_table::*;
pub use aoe_region_type::AoeRegion;
pub use aoe_shape_row_type::AoeShapeRow;
pub use aoe_targeting_row_type::AoeTargetingRow;
pub use armor_cast_reducer::armor_cast;
pub use armor_inscription_row_type::ArmorInscriptionRow;
pub use award_resonance_xp_reducer::award_resonance_xp;
pub use boss_phase_row_type::BossPhaseRow;
pub use boss_state_table::*;
pub use boss_state_type::BossState;
pub use cast_ended_event_type::CastEndedEvent;
pub use cast_ended_table::*;
pub use cast_kind_row_type::CastKindRow;
pub use cast_source_row_type::CastSourceRow;
pub use cast_spell_reducer::cast_spell;
pub use cast_state_table::*;
pub use cast_state_type::CastState;
pub use claim_npc_item_reducer::claim_npc_item;
pub use color_row_type::ColorRow;
pub use cooldown_table::*;
pub use cooldown_type::Cooldown;
pub use crowd_control_kind_row_type::CrowdControlKindRow;
pub use crowd_control_table::*;
pub use crowd_control_type::CrowdControl;
pub use damage_event_row_type::DamageEventRow;
pub use damage_event_table::*;
pub use destroy_item_reducer::destroy_item;
pub use effect_payload_filter_row_type::EffectPayloadFilterRow;
pub use effect_payload_kind_row_type::EffectPayloadKindRow;
pub use effect_payload_row_type::EffectPayloadRow;
pub use effect_payload_selection_row_type::EffectPayloadSelectionRow;
pub use eidolon_cast_reducer::eidolon_cast;
pub use entity_kind_row_type::EntityKindRow;
pub use entity_state_row_type::EntityStateRow;
pub use entity_stats_table::*;
pub use entity_stats_type::EntityStats;
pub use equip_item_reducer::equip_item;
pub use equipment_table::*;
pub use equipment_table_type::EquipmentTable;
pub use game_entity_table::*;
pub use game_entity_type::GameEntity;
pub use gm_clear_prop_override_reducer::gm_clear_prop_override;
pub use gm_reseed_world_reducer::gm_reseed_world;
pub use gm_set_prop_override_reducer::gm_set_prop_override;
pub use heartbeat_reducer::heartbeat;
pub use hotbar_row_type::HotbarRow;
pub use hotbar_table::*;
pub use hotbar_type::Hotbar;
pub use inscription_row_type::InscriptionRow;
pub use inventory_table::*;
pub use inventory_table_type::InventoryTable;
pub use item_instance_row_type::ItemInstanceRow;
pub use join_reducer::join;
pub use known_ancient_language_table::*;
pub use known_ancient_language_table_type::KnownAncientLanguageTable;
pub use known_glyphs_table::*;
pub use known_glyphs_table_type::KnownGlyphsTable;
pub use leave_reducer::leave;
pub use modifier_kind_row_type::ModifierKindRow;
pub use move_item_reducer::move_item;
pub use move_to_reducer::move_to;
pub use periodic_effect_table::*;
pub use periodic_effect_type::PeriodicEffect;
pub use player_message_event_type::PlayerMessageEvent;
pub use player_message_table::*;
pub use player_stats_table::*;
pub use player_stats_type::PlayerStats;
pub use player_table::*;
pub use player_type::Player;
pub use projectile_table::*;
pub use projectile_type::Projectile;
pub use prop_override_table::*;
pub use prop_override_type::PropOverride;
pub use release_cast_reducer::release_cast;
pub use resonance_table::*;
pub use resonance_type::Resonance;
pub use respawn_reducer::respawn;
pub use secondary_word_row_type::SecondaryWordRow;
pub use set_ability_selection_reducer::set_ability_selection;
pub use set_armor_inscription_reducer::set_armor_inscription;
pub use set_hotbar_spell_reducer::set_hotbar_spell;
pub use set_inscription_reducer::set_inscription;
pub use set_resonance_xp_reducer::set_resonance_xp;
pub use set_root_inscription_reducer::set_root_inscription;
pub use slot_inscription_row_type::SlotInscriptionRow;
pub use spell_visual_effect_event_type::SpellVisualEffectEvent;
pub use spell_visual_effect_table::*;
pub use stat_modifier_table::*;
pub use stat_modifier_type::StatModifier;
pub use stats_row_type::StatsRow;
pub use stop_reducer::stop;
pub use threat_table::*;
pub use threat_type::Threat;
pub use tick_schedule_type::TickSchedule;
pub use tick_stats_table::*;
pub use tick_stats_type::TickStats;
pub use unequip_item_reducer::unequip_item;
pub use vec_3_row_type::Vec3Row;
pub use weapon_inscription_row_type::WeaponInscriptionRow;
pub use weapon_inscriptions_row_type::WeaponInscriptionsRow;

#[derive(Clone, PartialEq, Debug)]

/// One of the reducers defined by this module.
///
/// Contained within a [`__sdk::ReducerEvent`] in [`EventContext`]s for reducer events
/// to indicate which reducer caused the event.

pub enum Reducer {
    ArmorCast {
        armor_slot: String,
        target_entity: Option<u64>,
        target_position: Option<Vec3Row>,
    },
    AwardResonanceXp {
        root_word_id: String,
        xp_amount: u64,
    },
    CastSpell {
        spell_id: String,
        target_entity: Option<u64>,
        target_position: Option<Vec3Row>,
    },
    ClaimNpcItem {
        npc_entity_id: u64,
        item_id: String,
    },
    DestroyItem {
        instance_id: u64,
    },
    EidolonCast {
        slot: String,
        target_entity: Option<u64>,
        target_position: Option<Vec3Row>,
    },
    EquipItem {
        slot_index: u8,
    },
    GmClearPropOverride {
        map_id: String,
        prop_id: String,
    },
    GmReseedWorld,
    GmSetPropOverride {
        map_id: String,
        prop_id: String,
        position: Option<Vec3Row>,
        rotation_y: Option<f32>,
        scale: Option<Vec3Row>,
        removed: bool,
    },
    Heartbeat,
    Join {
        display_name: String,
    },
    Leave,
    MoveItem {
        from: u8,
        to: u8,
    },
    MoveTo {
        x: f32,
        y: f32,
        z: f32,
    },
    ReleaseCast {
        spell_id: String,
    },
    Respawn,
    SetAbilitySelection {
        slot: String,
        ability_id: String,
    },
    SetArmorInscription {
        slot: String,
        root_word: Option<String>,
        secondary_words: Vec<String>,
    },
    SetHotbarSpell {
        slot: String,
        spell_id: Option<String>,
    },
    SetInscription {
        slot: String,
        essence: Option<String>,
        modifiers: Vec<String>,
        ancient_word: Option<String>,
    },
    SetResonanceXp {
        root_word_id: String,
        xp: u64,
        level: u32,
    },
    SetRootInscription {
        root_word: Option<String>,
        primary_words: Vec<String>,
        secondary_words: Vec<String>,
        ultimate_words: Vec<String>,
    },
    Stop,
    UnequipItem {
        slot: String,
    },
}

impl __sdk::InModule for Reducer {
    type Module = RemoteModule;
}

impl __sdk::Reducer for Reducer {
    fn reducer_name(&self) -> &'static str {
        match self {
            Reducer::ArmorCast { .. } => "armor_cast",
            Reducer::AwardResonanceXp { .. } => "award_resonance_xp",
            Reducer::CastSpell { .. } => "cast_spell",
            Reducer::ClaimNpcItem { .. } => "claim_npc_item",
            Reducer::DestroyItem { .. } => "destroy_item",
            Reducer::EidolonCast { .. } => "eidolon_cast",
            Reducer::EquipItem { .. } => "equip_item",
            Reducer::GmClearPropOverride { .. } => "gm_clear_prop_override",
            Reducer::GmReseedWorld => "gm_reseed_world",
            Reducer::GmSetPropOverride { .. } => "gm_set_prop_override",
            Reducer::Heartbeat => "heartbeat",
            Reducer::Join { .. } => "join",
            Reducer::Leave => "leave",
            Reducer::MoveItem { .. } => "move_item",
            Reducer::MoveTo { .. } => "move_to",
            Reducer::ReleaseCast { .. } => "release_cast",
            Reducer::Respawn => "respawn",
            Reducer::SetAbilitySelection { .. } => "set_ability_selection",
            Reducer::SetArmorInscription { .. } => "set_armor_inscription",
            Reducer::SetHotbarSpell { .. } => "set_hotbar_spell",
            Reducer::SetInscription { .. } => "set_inscription",
            Reducer::SetResonanceXp { .. } => "set_resonance_xp",
            Reducer::SetRootInscription { .. } => "set_root_inscription",
            Reducer::Stop => "stop",
            Reducer::UnequipItem { .. } => "unequip_item",
            _ => unreachable!(),
        }
    }
    #[allow(clippy::clone_on_copy)]
    fn args_bsatn(&self) -> Result<Vec<u8>, __sats::bsatn::EncodeError> {
        match self {
            Reducer::ArmorCast {
                armor_slot,
                target_entity,
                target_position,
            } => __sats::bsatn::to_vec(&armor_cast_reducer::ArmorCastArgs {
                armor_slot: armor_slot.clone(),
                target_entity: target_entity.clone(),
                target_position: target_position.clone(),
            }),
            Reducer::AwardResonanceXp {
                root_word_id,
                xp_amount,
            } => __sats::bsatn::to_vec(&award_resonance_xp_reducer::AwardResonanceXpArgs {
                root_word_id: root_word_id.clone(),
                xp_amount: xp_amount.clone(),
            }),
            Reducer::CastSpell {
                spell_id,
                target_entity,
                target_position,
            } => __sats::bsatn::to_vec(&cast_spell_reducer::CastSpellArgs {
                spell_id: spell_id.clone(),
                target_entity: target_entity.clone(),
                target_position: target_position.clone(),
            }),
            Reducer::ClaimNpcItem {
                npc_entity_id,
                item_id,
            } => __sats::bsatn::to_vec(&claim_npc_item_reducer::ClaimNpcItemArgs {
                npc_entity_id: npc_entity_id.clone(),
                item_id: item_id.clone(),
            }),
            Reducer::DestroyItem { instance_id } => {
                __sats::bsatn::to_vec(&destroy_item_reducer::DestroyItemArgs {
                    instance_id: instance_id.clone(),
                })
            }
            Reducer::EidolonCast {
                slot,
                target_entity,
                target_position,
            } => __sats::bsatn::to_vec(&eidolon_cast_reducer::EidolonCastArgs {
                slot: slot.clone(),
                target_entity: target_entity.clone(),
                target_position: target_position.clone(),
            }),
            Reducer::EquipItem { slot_index } => {
                __sats::bsatn::to_vec(&equip_item_reducer::EquipItemArgs {
                    slot_index: slot_index.clone(),
                })
            }
            Reducer::GmClearPropOverride { map_id, prop_id } => {
                __sats::bsatn::to_vec(&gm_clear_prop_override_reducer::GmClearPropOverrideArgs {
                    map_id: map_id.clone(),
                    prop_id: prop_id.clone(),
                })
            }
            Reducer::GmReseedWorld => {
                __sats::bsatn::to_vec(&gm_reseed_world_reducer::GmReseedWorldArgs {})
            }
            Reducer::GmSetPropOverride {
                map_id,
                prop_id,
                position,
                rotation_y,
                scale,
                removed,
            } => __sats::bsatn::to_vec(&gm_set_prop_override_reducer::GmSetPropOverrideArgs {
                map_id: map_id.clone(),
                prop_id: prop_id.clone(),
                position: position.clone(),
                rotation_y: rotation_y.clone(),
                scale: scale.clone(),
                removed: removed.clone(),
            }),
            Reducer::Heartbeat => __sats::bsatn::to_vec(&heartbeat_reducer::HeartbeatArgs {}),
            Reducer::Join { display_name } => __sats::bsatn::to_vec(&join_reducer::JoinArgs {
                display_name: display_name.clone(),
            }),
            Reducer::Leave => __sats::bsatn::to_vec(&leave_reducer::LeaveArgs {}),
            Reducer::MoveItem { from, to } => {
                __sats::bsatn::to_vec(&move_item_reducer::MoveItemArgs {
                    from: from.clone(),
                    to: to.clone(),
                })
            }
            Reducer::MoveTo { x, y, z } => __sats::bsatn::to_vec(&move_to_reducer::MoveToArgs {
                x: x.clone(),
                y: y.clone(),
                z: z.clone(),
            }),
            Reducer::ReleaseCast { spell_id } => {
                __sats::bsatn::to_vec(&release_cast_reducer::ReleaseCastArgs {
                    spell_id: spell_id.clone(),
                })
            }
            Reducer::Respawn => __sats::bsatn::to_vec(&respawn_reducer::RespawnArgs {}),
            Reducer::SetAbilitySelection { slot, ability_id } => {
                __sats::bsatn::to_vec(&set_ability_selection_reducer::SetAbilitySelectionArgs {
                    slot: slot.clone(),
                    ability_id: ability_id.clone(),
                })
            }
            Reducer::SetArmorInscription {
                slot,
                root_word,
                secondary_words,
            } => __sats::bsatn::to_vec(&set_armor_inscription_reducer::SetArmorInscriptionArgs {
                slot: slot.clone(),
                root_word: root_word.clone(),
                secondary_words: secondary_words.clone(),
            }),
            Reducer::SetHotbarSpell { slot, spell_id } => {
                __sats::bsatn::to_vec(&set_hotbar_spell_reducer::SetHotbarSpellArgs {
                    slot: slot.clone(),
                    spell_id: spell_id.clone(),
                })
            }
            Reducer::SetInscription {
                slot,
                essence,
                modifiers,
                ancient_word,
            } => __sats::bsatn::to_vec(&set_inscription_reducer::SetInscriptionArgs {
                slot: slot.clone(),
                essence: essence.clone(),
                modifiers: modifiers.clone(),
                ancient_word: ancient_word.clone(),
            }),
            Reducer::SetResonanceXp {
                root_word_id,
                xp,
                level,
            } => __sats::bsatn::to_vec(&set_resonance_xp_reducer::SetResonanceXpArgs {
                root_word_id: root_word_id.clone(),
                xp: xp.clone(),
                level: level.clone(),
            }),
            Reducer::SetRootInscription {
                root_word,
                primary_words,
                secondary_words,
                ultimate_words,
            } => __sats::bsatn::to_vec(&set_root_inscription_reducer::SetRootInscriptionArgs {
                root_word: root_word.clone(),
                primary_words: primary_words.clone(),
                secondary_words: secondary_words.clone(),
                ultimate_words: ultimate_words.clone(),
            }),
            Reducer::Stop => __sats::bsatn::to_vec(&stop_reducer::StopArgs {}),
            Reducer::UnequipItem { slot } => {
                __sats::bsatn::to_vec(&unequip_item_reducer::UnequipItemArgs { slot: slot.clone() })
            }
            _ => unreachable!(),
        }
    }
}

#[derive(Default, Debug)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct DbUpdate {
    active_status: __sdk::TableUpdate<ActiveStatus>,
    aoe_region: __sdk::TableUpdate<AoeRegion>,
    boss_state: __sdk::TableUpdate<BossState>,
    cast_ended: __sdk::TableUpdate<CastEndedEvent>,
    cast_state: __sdk::TableUpdate<CastState>,
    cooldown: __sdk::TableUpdate<Cooldown>,
    crowd_control: __sdk::TableUpdate<CrowdControl>,
    damage_event: __sdk::TableUpdate<DamageEventRow>,
    entity_stats: __sdk::TableUpdate<EntityStats>,
    equipment: __sdk::TableUpdate<EquipmentTable>,
    game_entity: __sdk::TableUpdate<GameEntity>,
    hotbar: __sdk::TableUpdate<Hotbar>,
    inventory: __sdk::TableUpdate<InventoryTable>,
    known_ancient_language: __sdk::TableUpdate<KnownAncientLanguageTable>,
    known_glyphs: __sdk::TableUpdate<KnownGlyphsTable>,
    periodic_effect: __sdk::TableUpdate<PeriodicEffect>,
    player: __sdk::TableUpdate<Player>,
    player_message: __sdk::TableUpdate<PlayerMessageEvent>,
    player_stats: __sdk::TableUpdate<PlayerStats>,
    projectile: __sdk::TableUpdate<Projectile>,
    prop_override: __sdk::TableUpdate<PropOverride>,
    resonance: __sdk::TableUpdate<Resonance>,
    spell_visual_effect: __sdk::TableUpdate<SpellVisualEffectEvent>,
    stat_modifier: __sdk::TableUpdate<StatModifier>,
    threat: __sdk::TableUpdate<Threat>,
    tick_stats: __sdk::TableUpdate<TickStats>,
}

impl TryFrom<__ws::v2::TransactionUpdate> for DbUpdate {
    type Error = __sdk::Error;
    fn try_from(raw: __ws::v2::TransactionUpdate) -> Result<Self, Self::Error> {
        let mut db_update = DbUpdate::default();
        for table_update in __sdk::transaction_update_iter_table_updates(raw) {
            match &table_update.table_name[..] {
                "active_status" => db_update
                    .active_status
                    .append(active_status_table::parse_table_update(table_update)?),
                "aoe_region" => db_update
                    .aoe_region
                    .append(aoe_region_table::parse_table_update(table_update)?),
                "boss_state" => db_update
                    .boss_state
                    .append(boss_state_table::parse_table_update(table_update)?),
                "cast_ended" => db_update
                    .cast_ended
                    .append(cast_ended_table::parse_table_update(table_update)?),
                "cast_state" => db_update
                    .cast_state
                    .append(cast_state_table::parse_table_update(table_update)?),
                "cooldown" => db_update
                    .cooldown
                    .append(cooldown_table::parse_table_update(table_update)?),
                "crowd_control" => db_update
                    .crowd_control
                    .append(crowd_control_table::parse_table_update(table_update)?),
                "damage_event" => db_update
                    .damage_event
                    .append(damage_event_table::parse_table_update(table_update)?),
                "entity_stats" => db_update
                    .entity_stats
                    .append(entity_stats_table::parse_table_update(table_update)?),
                "equipment" => db_update
                    .equipment
                    .append(equipment_table::parse_table_update(table_update)?),
                "game_entity" => db_update
                    .game_entity
                    .append(game_entity_table::parse_table_update(table_update)?),
                "hotbar" => db_update
                    .hotbar
                    .append(hotbar_table::parse_table_update(table_update)?),
                "inventory" => db_update
                    .inventory
                    .append(inventory_table::parse_table_update(table_update)?),
                "known_ancient_language" => db_update.known_ancient_language.append(
                    known_ancient_language_table::parse_table_update(table_update)?,
                ),
                "known_glyphs" => db_update
                    .known_glyphs
                    .append(known_glyphs_table::parse_table_update(table_update)?),
                "periodic_effect" => db_update
                    .periodic_effect
                    .append(periodic_effect_table::parse_table_update(table_update)?),
                "player" => db_update
                    .player
                    .append(player_table::parse_table_update(table_update)?),
                "player_message" => db_update
                    .player_message
                    .append(player_message_table::parse_table_update(table_update)?),
                "player_stats" => db_update
                    .player_stats
                    .append(player_stats_table::parse_table_update(table_update)?),
                "projectile" => db_update
                    .projectile
                    .append(projectile_table::parse_table_update(table_update)?),
                "prop_override" => db_update
                    .prop_override
                    .append(prop_override_table::parse_table_update(table_update)?),
                "resonance" => db_update
                    .resonance
                    .append(resonance_table::parse_table_update(table_update)?),
                "spell_visual_effect" => db_update
                    .spell_visual_effect
                    .append(spell_visual_effect_table::parse_table_update(table_update)?),
                "stat_modifier" => db_update
                    .stat_modifier
                    .append(stat_modifier_table::parse_table_update(table_update)?),
                "threat" => db_update
                    .threat
                    .append(threat_table::parse_table_update(table_update)?),
                "tick_stats" => db_update
                    .tick_stats
                    .append(tick_stats_table::parse_table_update(table_update)?),

                unknown => {
                    return Err(__sdk::InternalError::unknown_name(
                        "table",
                        unknown,
                        "DatabaseUpdate",
                    )
                    .into());
                }
            }
        }
        Ok(db_update)
    }
}

impl __sdk::InModule for DbUpdate {
    type Module = RemoteModule;
}

impl __sdk::DbUpdate for DbUpdate {
    fn apply_to_client_cache(
        &self,
        cache: &mut __sdk::ClientCache<RemoteModule>,
    ) -> AppliedDiff<'_> {
        let mut diff = AppliedDiff::default();

        diff.active_status = cache
            .apply_diff_to_table::<ActiveStatus>("active_status", &self.active_status)
            .with_updates_by_pk(|row| &row.id);
        diff.aoe_region = cache
            .apply_diff_to_table::<AoeRegion>("aoe_region", &self.aoe_region)
            .with_updates_by_pk(|row| &row.id);
        diff.boss_state = cache
            .apply_diff_to_table::<BossState>("boss_state", &self.boss_state)
            .with_updates_by_pk(|row| &row.entity_id);
        diff.cast_ended = self.cast_ended.into_event_diff();
        diff.cast_state = cache
            .apply_diff_to_table::<CastState>("cast_state", &self.cast_state)
            .with_updates_by_pk(|row| &row.entity_id);
        diff.cooldown = cache
            .apply_diff_to_table::<Cooldown>("cooldown", &self.cooldown)
            .with_updates_by_pk(|row| &row.id);
        diff.crowd_control = cache
            .apply_diff_to_table::<CrowdControl>("crowd_control", &self.crowd_control)
            .with_updates_by_pk(|row| &row.id);
        diff.damage_event = self.damage_event.into_event_diff();
        diff.entity_stats = cache
            .apply_diff_to_table::<EntityStats>("entity_stats", &self.entity_stats)
            .with_updates_by_pk(|row| &row.entity_id);
        diff.equipment = cache
            .apply_diff_to_table::<EquipmentTable>("equipment", &self.equipment)
            .with_updates_by_pk(|row| &row.identity);
        diff.game_entity = cache
            .apply_diff_to_table::<GameEntity>("game_entity", &self.game_entity)
            .with_updates_by_pk(|row| &row.entity_id);
        diff.hotbar = cache
            .apply_diff_to_table::<Hotbar>("hotbar", &self.hotbar)
            .with_updates_by_pk(|row| &row.identity);
        diff.inventory = cache
            .apply_diff_to_table::<InventoryTable>("inventory", &self.inventory)
            .with_updates_by_pk(|row| &row.identity);
        diff.known_ancient_language = cache
            .apply_diff_to_table::<KnownAncientLanguageTable>(
                "known_ancient_language",
                &self.known_ancient_language,
            )
            .with_updates_by_pk(|row| &row.identity);
        diff.known_glyphs = cache
            .apply_diff_to_table::<KnownGlyphsTable>("known_glyphs", &self.known_glyphs)
            .with_updates_by_pk(|row| &row.identity);
        diff.periodic_effect = cache
            .apply_diff_to_table::<PeriodicEffect>("periodic_effect", &self.periodic_effect)
            .with_updates_by_pk(|row| &row.id);
        diff.player = cache
            .apply_diff_to_table::<Player>("player", &self.player)
            .with_updates_by_pk(|row| &row.identity);
        diff.player_message = self.player_message.into_event_diff();
        diff.player_stats = cache
            .apply_diff_to_table::<PlayerStats>("player_stats", &self.player_stats)
            .with_updates_by_pk(|row| &row.identity);
        diff.projectile = cache
            .apply_diff_to_table::<Projectile>("projectile", &self.projectile)
            .with_updates_by_pk(|row| &row.id);
        diff.prop_override = cache
            .apply_diff_to_table::<PropOverride>("prop_override", &self.prop_override)
            .with_updates_by_pk(|row| &row.id);
        diff.resonance = cache
            .apply_diff_to_table::<Resonance>("resonance", &self.resonance)
            .with_updates_by_pk(|row| &row.id);
        diff.spell_visual_effect = self.spell_visual_effect.into_event_diff();
        diff.stat_modifier = cache
            .apply_diff_to_table::<StatModifier>("stat_modifier", &self.stat_modifier)
            .with_updates_by_pk(|row| &row.id);
        diff.threat = cache
            .apply_diff_to_table::<Threat>("threat", &self.threat)
            .with_updates_by_pk(|row| &row.id);
        diff.tick_stats = cache
            .apply_diff_to_table::<TickStats>("tick_stats", &self.tick_stats)
            .with_updates_by_pk(|row| &row.id);

        diff
    }
    fn parse_initial_rows(raw: __ws::v2::QueryRows) -> __sdk::Result<Self> {
        let mut db_update = DbUpdate::default();
        for table_rows in raw.tables {
            match &table_rows.table[..] {
                "active_status" => db_update
                    .active_status
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "aoe_region" => db_update
                    .aoe_region
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "boss_state" => db_update
                    .boss_state
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "cast_ended" => db_update
                    .cast_ended
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "cast_state" => db_update
                    .cast_state
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "cooldown" => db_update
                    .cooldown
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "crowd_control" => db_update
                    .crowd_control
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "damage_event" => db_update
                    .damage_event
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "entity_stats" => db_update
                    .entity_stats
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "equipment" => db_update
                    .equipment
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "game_entity" => db_update
                    .game_entity
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "hotbar" => db_update
                    .hotbar
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "inventory" => db_update
                    .inventory
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "known_ancient_language" => db_update
                    .known_ancient_language
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "known_glyphs" => db_update
                    .known_glyphs
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "periodic_effect" => db_update
                    .periodic_effect
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "player" => db_update
                    .player
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "player_message" => db_update
                    .player_message
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "player_stats" => db_update
                    .player_stats
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "projectile" => db_update
                    .projectile
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "prop_override" => db_update
                    .prop_override
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "resonance" => db_update
                    .resonance
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "spell_visual_effect" => db_update
                    .spell_visual_effect
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "stat_modifier" => db_update
                    .stat_modifier
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "threat" => db_update
                    .threat
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "tick_stats" => db_update
                    .tick_stats
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                unknown => {
                    return Err(
                        __sdk::InternalError::unknown_name("table", unknown, "QueryRows").into(),
                    );
                }
            }
        }
        Ok(db_update)
    }
    fn parse_unsubscribe_rows(raw: __ws::v2::QueryRows) -> __sdk::Result<Self> {
        let mut db_update = DbUpdate::default();
        for table_rows in raw.tables {
            match &table_rows.table[..] {
                "active_status" => db_update
                    .active_status
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "aoe_region" => db_update
                    .aoe_region
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "boss_state" => db_update
                    .boss_state
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "cast_ended" => db_update
                    .cast_ended
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "cast_state" => db_update
                    .cast_state
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "cooldown" => db_update
                    .cooldown
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "crowd_control" => db_update
                    .crowd_control
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "damage_event" => db_update
                    .damage_event
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "entity_stats" => db_update
                    .entity_stats
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "equipment" => db_update
                    .equipment
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "game_entity" => db_update
                    .game_entity
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "hotbar" => db_update
                    .hotbar
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "inventory" => db_update
                    .inventory
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "known_ancient_language" => db_update
                    .known_ancient_language
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "known_glyphs" => db_update
                    .known_glyphs
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "periodic_effect" => db_update
                    .periodic_effect
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "player" => db_update
                    .player
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "player_message" => db_update
                    .player_message
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "player_stats" => db_update
                    .player_stats
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "projectile" => db_update
                    .projectile
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "prop_override" => db_update
                    .prop_override
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "resonance" => db_update
                    .resonance
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "spell_visual_effect" => db_update
                    .spell_visual_effect
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "stat_modifier" => db_update
                    .stat_modifier
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "threat" => db_update
                    .threat
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "tick_stats" => db_update
                    .tick_stats
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                unknown => {
                    return Err(
                        __sdk::InternalError::unknown_name("table", unknown, "QueryRows").into(),
                    );
                }
            }
        }
        Ok(db_update)
    }
}

#[derive(Default)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct AppliedDiff<'r> {
    active_status: __sdk::TableAppliedDiff<'r, ActiveStatus>,
    aoe_region: __sdk::TableAppliedDiff<'r, AoeRegion>,
    boss_state: __sdk::TableAppliedDiff<'r, BossState>,
    cast_ended: __sdk::TableAppliedDiff<'r, CastEndedEvent>,
    cast_state: __sdk::TableAppliedDiff<'r, CastState>,
    cooldown: __sdk::TableAppliedDiff<'r, Cooldown>,
    crowd_control: __sdk::TableAppliedDiff<'r, CrowdControl>,
    damage_event: __sdk::TableAppliedDiff<'r, DamageEventRow>,
    entity_stats: __sdk::TableAppliedDiff<'r, EntityStats>,
    equipment: __sdk::TableAppliedDiff<'r, EquipmentTable>,
    game_entity: __sdk::TableAppliedDiff<'r, GameEntity>,
    hotbar: __sdk::TableAppliedDiff<'r, Hotbar>,
    inventory: __sdk::TableAppliedDiff<'r, InventoryTable>,
    known_ancient_language: __sdk::TableAppliedDiff<'r, KnownAncientLanguageTable>,
    known_glyphs: __sdk::TableAppliedDiff<'r, KnownGlyphsTable>,
    periodic_effect: __sdk::TableAppliedDiff<'r, PeriodicEffect>,
    player: __sdk::TableAppliedDiff<'r, Player>,
    player_message: __sdk::TableAppliedDiff<'r, PlayerMessageEvent>,
    player_stats: __sdk::TableAppliedDiff<'r, PlayerStats>,
    projectile: __sdk::TableAppliedDiff<'r, Projectile>,
    prop_override: __sdk::TableAppliedDiff<'r, PropOverride>,
    resonance: __sdk::TableAppliedDiff<'r, Resonance>,
    spell_visual_effect: __sdk::TableAppliedDiff<'r, SpellVisualEffectEvent>,
    stat_modifier: __sdk::TableAppliedDiff<'r, StatModifier>,
    threat: __sdk::TableAppliedDiff<'r, Threat>,
    tick_stats: __sdk::TableAppliedDiff<'r, TickStats>,
    __unused: std::marker::PhantomData<&'r ()>,
}

impl __sdk::InModule for AppliedDiff<'_> {
    type Module = RemoteModule;
}

impl<'r> __sdk::AppliedDiff<'r> for AppliedDiff<'r> {
    fn invoke_row_callbacks(
        &self,
        event: &EventContext,
        callbacks: &mut __sdk::DbCallbacks<RemoteModule>,
    ) {
        callbacks.invoke_table_row_callbacks::<ActiveStatus>(
            "active_status",
            &self.active_status,
            event,
        );
        callbacks.invoke_table_row_callbacks::<AoeRegion>("aoe_region", &self.aoe_region, event);
        callbacks.invoke_table_row_callbacks::<BossState>("boss_state", &self.boss_state, event);
        callbacks.invoke_table_row_callbacks::<CastEndedEvent>(
            "cast_ended",
            &self.cast_ended,
            event,
        );
        callbacks.invoke_table_row_callbacks::<CastState>("cast_state", &self.cast_state, event);
        callbacks.invoke_table_row_callbacks::<Cooldown>("cooldown", &self.cooldown, event);
        callbacks.invoke_table_row_callbacks::<CrowdControl>(
            "crowd_control",
            &self.crowd_control,
            event,
        );
        callbacks.invoke_table_row_callbacks::<DamageEventRow>(
            "damage_event",
            &self.damage_event,
            event,
        );
        callbacks.invoke_table_row_callbacks::<EntityStats>(
            "entity_stats",
            &self.entity_stats,
            event,
        );
        callbacks.invoke_table_row_callbacks::<EquipmentTable>("equipment", &self.equipment, event);
        callbacks.invoke_table_row_callbacks::<GameEntity>("game_entity", &self.game_entity, event);
        callbacks.invoke_table_row_callbacks::<Hotbar>("hotbar", &self.hotbar, event);
        callbacks.invoke_table_row_callbacks::<InventoryTable>("inventory", &self.inventory, event);
        callbacks.invoke_table_row_callbacks::<KnownAncientLanguageTable>(
            "known_ancient_language",
            &self.known_ancient_language,
            event,
        );
        callbacks.invoke_table_row_callbacks::<KnownGlyphsTable>(
            "known_glyphs",
            &self.known_glyphs,
            event,
        );
        callbacks.invoke_table_row_callbacks::<PeriodicEffect>(
            "periodic_effect",
            &self.periodic_effect,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Player>("player", &self.player, event);
        callbacks.invoke_table_row_callbacks::<PlayerMessageEvent>(
            "player_message",
            &self.player_message,
            event,
        );
        callbacks.invoke_table_row_callbacks::<PlayerStats>(
            "player_stats",
            &self.player_stats,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Projectile>("projectile", &self.projectile, event);
        callbacks.invoke_table_row_callbacks::<PropOverride>(
            "prop_override",
            &self.prop_override,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Resonance>("resonance", &self.resonance, event);
        callbacks.invoke_table_row_callbacks::<SpellVisualEffectEvent>(
            "spell_visual_effect",
            &self.spell_visual_effect,
            event,
        );
        callbacks.invoke_table_row_callbacks::<StatModifier>(
            "stat_modifier",
            &self.stat_modifier,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Threat>("threat", &self.threat, event);
        callbacks.invoke_table_row_callbacks::<TickStats>("tick_stats", &self.tick_stats, event);
    }
}

#[doc(hidden)]
#[derive(Debug)]
pub struct RemoteModule;

impl __sdk::InModule for RemoteModule {
    type Module = Self;
}

/// The `reducers` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each reducer defined by the module.
pub struct RemoteReducers {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteReducers {
    type Module = RemoteModule;
}

/// The `procedures` field of [`DbConnection`] and other [`DbContext`] types,
/// with methods provided by extension traits for each procedure defined by the module.
pub struct RemoteProcedures {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteProcedures {
    type Module = RemoteModule;
}

/// The `db` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each table defined by the module.
pub struct RemoteTables {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteTables {
    type Module = RemoteModule;
}

/// A connection to a remote module, including a materialized view of a subset of the database.
///
/// Connect to a remote module by calling [`DbConnection::builder`]
/// and using the [`__sdk::DbConnectionBuilder`] builder-pattern constructor.
///
/// You must explicitly advance the connection by calling any one of:
///
/// - [`DbConnection::frame_tick`].
#[cfg_attr(not(target_arch = "wasm32"), doc = "- [`DbConnection::run_threaded`].")]
#[cfg_attr(
    target_arch = "wasm32",
    doc = "- [`DbConnection::run_background_task`]."
)]
/// - [`DbConnection::run_async`].
/// - [`DbConnection::advance_one_message`].
#[cfg_attr(
    not(target_arch = "wasm32"),
    doc = "- [`DbConnection::advance_one_message_blocking`]."
)]
/// - [`DbConnection::advance_one_message_async`].
///
/// Which of these methods you should call depends on the specific needs of your application,
/// but you must call one of them, or else the connection will never progress.
pub struct DbConnection {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    #[doc(hidden)]

    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,

    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for DbConnection {
    type Module = RemoteModule;
}

impl __sdk::DbContext for DbConnection {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl DbConnection {
    /// Builder-pattern constructor for a connection to a remote module.
    ///
    /// See [`__sdk::DbConnectionBuilder`] for required and optional configuration for the new connection.
    pub fn builder() -> __sdk::DbConnectionBuilder<RemoteModule> {
        __sdk::DbConnectionBuilder::new()
    }

    /// If any WebSocket messages are waiting, process one of them.
    ///
    /// Returns `true` if a message was processed, or `false` if the queue is empty.
    /// Callers should invoke this message in a loop until it returns `false`
    /// or for as much time is available to process messages.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::frame_tick`] each frame
    /// to fully exhaust the queue whenever time is available.
    pub fn advance_one_message(&self) -> __sdk::Result<bool> {
        self.imp.advance_one_message()
    }

    /// Process one WebSocket message, potentially blocking the current thread until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_threaded`] to spawn a thread
    /// which advances the connection automatically.
    #[cfg(not(target_arch = "wasm32"))]
    pub fn advance_one_message_blocking(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_blocking()
    }

    /// Process one WebSocket message, `await`ing until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_async`] to run an `async` loop
    /// which advances the connection when polled.
    pub async fn advance_one_message_async(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_async().await
    }

    /// Process all WebSocket messages waiting in the queue,
    /// then return without `await`ing or blocking the current thread.
    pub fn frame_tick(&self) -> __sdk::Result<()> {
        self.imp.frame_tick()
    }

    /// Spawn a thread which processes WebSocket messages as they are received.
    #[cfg(not(target_arch = "wasm32"))]
    pub fn run_threaded(&self) -> std::thread::JoinHandle<()> {
        self.imp.run_threaded()
    }

    /// Spawn a background task which processes WebSocket messages as they are received.
    #[cfg(target_arch = "wasm32")]
    pub fn run_background_task(&self) {
        self.imp.run_background_task()
    }

    /// Run an `async` loop which processes WebSocket messages when polled.
    pub async fn run_async(&self) -> __sdk::Result<()> {
        self.imp.run_async().await
    }
}

impl __sdk::DbConnection for DbConnection {
    fn new(imp: __sdk::DbContextImpl<RemoteModule>) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

/// A handle on a subscribed query.
// TODO: Document this better after implementing the new subscription API.
#[derive(Clone)]
pub struct SubscriptionHandle {
    imp: __sdk::SubscriptionHandleImpl<RemoteModule>,
}

impl __sdk::InModule for SubscriptionHandle {
    type Module = RemoteModule;
}

impl __sdk::SubscriptionHandle for SubscriptionHandle {
    fn new(imp: __sdk::SubscriptionHandleImpl<RemoteModule>) -> Self {
        Self { imp }
    }

    /// Returns true if this subscription has been terminated due to an unsubscribe call or an error.
    fn is_ended(&self) -> bool {
        self.imp.is_ended()
    }

    /// Returns true if this subscription has been applied and has not yet been unsubscribed.
    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    /// Unsubscribe from the query controlled by this `SubscriptionHandle`,
    /// then run `on_end` when its rows are removed from the client cache.
    fn unsubscribe_then(self, on_end: __sdk::OnEndedCallback<RemoteModule>) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(Some(on_end))
    }

    fn unsubscribe(self) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(None)
    }
}

/// Alias trait for a [`__sdk::DbContext`] connected to this module,
/// with that trait's associated types bounded to this module's concrete types.
///
/// Users can use this trait as a boundary on definitions which should accept
/// either a [`DbConnection`] or an [`EventContext`] and operate on either.
pub trait RemoteDbContext:
    __sdk::DbContext<
    DbView = RemoteTables,
    Reducers = RemoteReducers,
    SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
>
{
}
impl<
        Ctx: __sdk::DbContext<
            DbView = RemoteTables,
            Reducers = RemoteReducers,
            SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
        >,
    > RemoteDbContext for Ctx
{
}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::Event`],
/// passed to [`__sdk::Table::on_insert`], [`__sdk::Table::on_delete`] and [`__sdk::TableWithPrimaryKey::on_update`] callbacks.
pub struct EventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: __sdk::Event<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for EventContext {
    type Event = __sdk::Event<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for EventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for EventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::EventContext for EventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::ReducerEvent`],
/// passed to on-reducer callbacks.
pub struct ReducerEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: __sdk::ReducerEvent<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ReducerEventContext {
    type Event = __sdk::ReducerEvent<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ReducerEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ReducerEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ReducerEventContext for ReducerEventContext {}

/// An [`__sdk::DbContext`] passed to procedure callbacks.
pub struct ProcedureEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ProcedureEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for ProcedureEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ProcedureEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ProcedureEventContext for ProcedureEventContext {}

/// An [`__sdk::DbContext`] passed to [`__sdk::SubscriptionBuilder::on_applied`] and [`SubscriptionHandle::unsubscribe_then`] callbacks.
pub struct SubscriptionEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for SubscriptionEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for SubscriptionEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for SubscriptionEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::SubscriptionEventContext for SubscriptionEventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::Error`],
/// passed to [`__sdk::DbConnectionBuilder::on_disconnect`], [`__sdk::DbConnectionBuilder::on_connect_error`] and [`__sdk::SubscriptionBuilder::on_error`] callbacks.
pub struct ErrorContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: Option<__sdk::Error>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ErrorContext {
    type Event = Option<__sdk::Error>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ErrorContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ErrorContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ErrorContext for ErrorContext {}

impl __sdk::SpacetimeModule for RemoteModule {
    type DbConnection = DbConnection;
    type EventContext = EventContext;
    type ReducerEventContext = ReducerEventContext;
    type ProcedureEventContext = ProcedureEventContext;
    type SubscriptionEventContext = SubscriptionEventContext;
    type ErrorContext = ErrorContext;
    type Reducer = Reducer;
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;
    type DbUpdate = DbUpdate;
    type AppliedDiff<'r> = AppliedDiff<'r>;
    type SubscriptionHandle = SubscriptionHandle;
    type QueryBuilder = __sdk::QueryBuilder;

    fn register_tables(client_cache: &mut __sdk::ClientCache<Self>) {
        active_status_table::register_table(client_cache);
        aoe_region_table::register_table(client_cache);
        boss_state_table::register_table(client_cache);
        cast_ended_table::register_table(client_cache);
        cast_state_table::register_table(client_cache);
        cooldown_table::register_table(client_cache);
        crowd_control_table::register_table(client_cache);
        damage_event_table::register_table(client_cache);
        entity_stats_table::register_table(client_cache);
        equipment_table::register_table(client_cache);
        game_entity_table::register_table(client_cache);
        hotbar_table::register_table(client_cache);
        inventory_table::register_table(client_cache);
        known_ancient_language_table::register_table(client_cache);
        known_glyphs_table::register_table(client_cache);
        periodic_effect_table::register_table(client_cache);
        player_table::register_table(client_cache);
        player_message_table::register_table(client_cache);
        player_stats_table::register_table(client_cache);
        projectile_table::register_table(client_cache);
        prop_override_table::register_table(client_cache);
        resonance_table::register_table(client_cache);
        spell_visual_effect_table::register_table(client_cache);
        stat_modifier_table::register_table(client_cache);
        threat_table::register_table(client_cache);
        tick_stats_table::register_table(client_cache);
    }
    const ALL_TABLE_NAMES: &'static [&'static str] = &[
        "active_status",
        "aoe_region",
        "boss_state",
        "cast_ended",
        "cast_state",
        "cooldown",
        "crowd_control",
        "damage_event",
        "entity_stats",
        "equipment",
        "game_entity",
        "hotbar",
        "inventory",
        "known_ancient_language",
        "known_glyphs",
        "periodic_effect",
        "player",
        "player_message",
        "player_stats",
        "projectile",
        "prop_override",
        "resonance",
        "spell_visual_effect",
        "stat_modifier",
        "threat",
        "tick_stats",
    ];
}
