// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct MoveItemArgs {
    pub from: u8,
    pub to: u8,
}

impl From<MoveItemArgs> for super::Reducer {
    fn from(args: MoveItemArgs) -> Self {
        Self::MoveItem {
            from: args.from,
            to: args.to,
        }
    }
}

impl __sdk::InModule for MoveItemArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `move_item`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait move_item {
    /// Request that the remote module invoke the reducer `move_item` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`move_item:move_item_then`] to run a callback after the reducer completes.
    fn move_item(&self, from: u8, to: u8) -> __sdk::Result<()> {
        self.move_item_then(from, to, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `move_item` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn move_item_then(
        &self,
        from: u8,
        to: u8,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl move_item for super::RemoteReducers {
    fn move_item_then(
        &self,
        from: u8,
        to: u8,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(MoveItemArgs { from, to }, callback)
    }
}
