// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PartyMemberRow {
    pub character_id: __sdk::Uuid,
    pub party_id: u64,
    pub joined_at: __sdk::Timestamp,
}

impl __sdk::InModule for PartyMemberRow {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `PartyMemberRow`.
///
/// Provides typed access to columns for query building.
pub struct PartyMemberRowCols {
    pub character_id: __sdk::__query_builder::Col<PartyMemberRow, __sdk::Uuid>,
    pub party_id: __sdk::__query_builder::Col<PartyMemberRow, u64>,
    pub joined_at: __sdk::__query_builder::Col<PartyMemberRow, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for PartyMemberRow {
    type Cols = PartyMemberRowCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PartyMemberRowCols {
            character_id: __sdk::__query_builder::Col::new(table_name, "character_id"),
            party_id: __sdk::__query_builder::Col::new(table_name, "party_id"),
            joined_at: __sdk::__query_builder::Col::new(table_name, "joined_at"),
        }
    }
}

/// Indexed column accessor struct for the table `PartyMemberRow`.
///
/// Provides typed access to indexed columns for query building.
pub struct PartyMemberRowIxCols {
    pub character_id: __sdk::__query_builder::IxCol<PartyMemberRow, __sdk::Uuid>,
    pub party_id: __sdk::__query_builder::IxCol<PartyMemberRow, u64>,
}

impl __sdk::__query_builder::HasIxCols for PartyMemberRow {
    type IxCols = PartyMemberRowIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PartyMemberRowIxCols {
            character_id: __sdk::__query_builder::IxCol::new(table_name, "character_id"),
            party_id: __sdk::__query_builder::IxCol::new(table_name, "party_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for PartyMemberRow {}
