// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PartyRow {
    pub party_id: u64,
    pub leader: u64,
    pub created_at: __sdk::Timestamp,
}

impl __sdk::InModule for PartyRow {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `PartyRow`.
///
/// Provides typed access to columns for query building.
pub struct PartyRowCols {
    pub party_id: __sdk::__query_builder::Col<PartyRow, u64>,
    pub leader: __sdk::__query_builder::Col<PartyRow, u64>,
    pub created_at: __sdk::__query_builder::Col<PartyRow, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for PartyRow {
    type Cols = PartyRowCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PartyRowCols {
            party_id: __sdk::__query_builder::Col::new(table_name, "party_id"),
            leader: __sdk::__query_builder::Col::new(table_name, "leader"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
        }
    }
}

/// Indexed column accessor struct for the table `PartyRow`.
///
/// Provides typed access to indexed columns for query building.
pub struct PartyRowIxCols {
    pub party_id: __sdk::__query_builder::IxCol<PartyRow, u64>,
    pub leader: __sdk::__query_builder::IxCol<PartyRow, u64>,
}

impl __sdk::__query_builder::HasIxCols for PartyRow {
    type IxCols = PartyRowIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PartyRowIxCols {
            party_id: __sdk::__query_builder::IxCol::new(table_name, "party_id"),
            leader: __sdk::__query_builder::IxCol::new(table_name, "leader"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for PartyRow {}
