// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct PlaceBuyOrderArgs {
    pub npc_entity_id: u64,
    pub item_id: String,
    pub price: u64,
}

impl From<PlaceBuyOrderArgs> for super::Reducer {
    fn from(args: PlaceBuyOrderArgs) -> Self {
        Self::PlaceBuyOrder {
            npc_entity_id: args.npc_entity_id,
            item_id: args.item_id,
            price: args.price,
        }
    }
}

impl __sdk::InModule for PlaceBuyOrderArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `place_buy_order`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait place_buy_order {
    /// Request that the remote module invoke the reducer `place_buy_order` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`place_buy_order:place_buy_order_then`] to run a callback after the reducer completes.
    fn place_buy_order(
        &self,
        npc_entity_id: u64,
        item_id: String,
        price: u64,
    ) -> __sdk::Result<()> {
        self.place_buy_order_then(npc_entity_id, item_id, price, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `place_buy_order` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn place_buy_order_then(
        &self,
        npc_entity_id: u64,
        item_id: String,
        price: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl place_buy_order for super::RemoteReducers {
    fn place_buy_order_then(
        &self,
        npc_entity_id: u64,
        item_id: String,
        price: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            PlaceBuyOrderArgs {
                npc_entity_id,
                item_id,
                price,
            },
            callback,
        )
    }
}
