// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::player_message_event_type::PlayerMessageEvent;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `player_message`.
///
/// Obtain a handle from the [`PlayerMessageTableAccess::player_message`] method on [`super::RemoteTables`],
/// like `ctx.db.player_message()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.player_message().on_insert(...)`.
pub struct PlayerMessageTableHandle<'ctx> {
    imp: __sdk::TableHandle<PlayerMessageEvent>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `player_message`.
pub struct PlayerMessageTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for PlayerMessageTableAccessor {
    type Row = PlayerMessageEvent;
    type Handle<'db> = PlayerMessageTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.player_message()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `player_message`.
///
/// Implemented for [`super::RemoteTables`].
pub trait PlayerMessageTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`PlayerMessageTableHandle`], which mediates access to the table `player_message`.
    fn player_message(&self) -> PlayerMessageTableHandle<'_>;
}

impl PlayerMessageTableAccess for super::RemoteTables {
    fn player_message(&self) -> PlayerMessageTableHandle<'_> {
        PlayerMessageTableHandle {
            imp: self.imp.get_table::<PlayerMessageEvent>("player_message"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct PlayerMessageInsertCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for PlayerMessageTableHandle<'ctx> {
    type Row = PlayerMessageEvent;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = PlayerMessageEvent> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::EventTable for PlayerMessageTableHandle<'ctx> {
    type Row = PlayerMessageEvent;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = PlayerMessageEvent> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = PlayerMessageInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PlayerMessageInsertCallbackId {
        PlayerMessageInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PlayerMessageInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for PlayerMessageTableHandle<'ctx> {
    type InsertCallbackId = PlayerMessageInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PlayerMessageInsertCallbackId {
        PlayerMessageInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PlayerMessageInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<PlayerMessageEvent>("player_message");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<PlayerMessageEvent>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<PlayerMessageEvent>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `PlayerMessageEvent`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait player_messageQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `PlayerMessageEvent`.
    fn player_message(&self) -> __sdk::__query_builder::Table<PlayerMessageEvent>;
}

impl player_messageQueryTableAccess for __sdk::QueryTableAccessor {
    fn player_message(&self) -> __sdk::__query_builder::Table<PlayerMessageEvent> {
        __sdk::__query_builder::Table::new("player_message")
    }
}
