// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::player_stats_type::PlayerStats;
use super::stats_row_type::StatsRow;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `player_stats`.
///
/// Obtain a handle from the [`PlayerStatsTableAccess::player_stats`] method on [`super::RemoteTables`],
/// like `ctx.db.player_stats()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.player_stats().on_insert(...)`.
pub struct PlayerStatsTableHandle<'ctx> {
    imp: __sdk::TableHandle<PlayerStats>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `player_stats`.
pub struct PlayerStatsTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for PlayerStatsTableAccessor {
    type Row = PlayerStats;
    type Handle<'db> = PlayerStatsTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.player_stats()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `player_stats`.
///
/// Implemented for [`super::RemoteTables`].
pub trait PlayerStatsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`PlayerStatsTableHandle`], which mediates access to the table `player_stats`.
    fn player_stats(&self) -> PlayerStatsTableHandle<'_>;
}

impl PlayerStatsTableAccess for super::RemoteTables {
    fn player_stats(&self) -> PlayerStatsTableHandle<'_> {
        PlayerStatsTableHandle {
            imp: self.imp.get_table::<PlayerStats>("player_stats"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct PlayerStatsInsertCallbackId(__sdk::CallbackId);
pub struct PlayerStatsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for PlayerStatsTableHandle<'ctx> {
    type Row = PlayerStats;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = PlayerStats> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for PlayerStatsTableHandle<'ctx> {
    type Row = PlayerStats;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = PlayerStats> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = PlayerStatsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PlayerStatsInsertCallbackId {
        PlayerStatsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PlayerStatsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = PlayerStatsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PlayerStatsDeleteCallbackId {
        PlayerStatsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PlayerStatsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for PlayerStatsTableHandle<'ctx> {
    type InsertCallbackId = PlayerStatsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PlayerStatsInsertCallbackId {
        PlayerStatsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PlayerStatsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for PlayerStatsTableHandle<'ctx> {
    type DeleteCallbackId = PlayerStatsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PlayerStatsDeleteCallbackId {
        PlayerStatsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PlayerStatsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct PlayerStatsUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for PlayerStatsTableHandle<'ctx> {
    type UpdateCallbackId = PlayerStatsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PlayerStatsUpdateCallbackId {
        PlayerStatsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PlayerStatsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for PlayerStatsTableHandle<'ctx> {
    type UpdateCallbackId = PlayerStatsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PlayerStatsUpdateCallbackId {
        PlayerStatsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PlayerStatsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<PlayerStats>("player_stats");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<PlayerStats>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<PlayerStats>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `PlayerStats`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait player_statsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `PlayerStats`.
    fn player_stats(&self) -> __sdk::__query_builder::Table<PlayerStats>;
}

impl player_statsQueryTableAccess for __sdk::QueryTableAccessor {
    fn player_stats(&self) -> __sdk::__query_builder::Table<PlayerStats> {
        __sdk::__query_builder::Table::new("player_stats")
    }
}
