// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::effect_payload_row_type::EffectPayloadRow;
use super::vec_3_row_type::Vec3Row;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Projectile {
    pub id: u64,
    pub caster: u64,
    pub spell_id: String,
    pub position: Vec3Row,
    pub target_entity: Option<u64>,
    pub target_position: Option<Vec3Row>,
    pub speed: f32,
    pub effects: Vec<EffectPayloadRow>,
    pub hit_radius: f32,
    pub remaining_seconds: f32,
}

impl __sdk::InModule for Projectile {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Projectile`.
///
/// Provides typed access to columns for query building.
pub struct ProjectileCols {
    pub id: __sdk::__query_builder::Col<Projectile, u64>,
    pub caster: __sdk::__query_builder::Col<Projectile, u64>,
    pub spell_id: __sdk::__query_builder::Col<Projectile, String>,
    pub position: __sdk::__query_builder::Col<Projectile, Vec3Row>,
    pub target_entity: __sdk::__query_builder::Col<Projectile, Option<u64>>,
    pub target_position: __sdk::__query_builder::Col<Projectile, Option<Vec3Row>>,
    pub speed: __sdk::__query_builder::Col<Projectile, f32>,
    pub effects: __sdk::__query_builder::Col<Projectile, Vec<EffectPayloadRow>>,
    pub hit_radius: __sdk::__query_builder::Col<Projectile, f32>,
    pub remaining_seconds: __sdk::__query_builder::Col<Projectile, f32>,
}

impl __sdk::__query_builder::HasCols for Projectile {
    type Cols = ProjectileCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ProjectileCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            caster: __sdk::__query_builder::Col::new(table_name, "caster"),
            spell_id: __sdk::__query_builder::Col::new(table_name, "spell_id"),
            position: __sdk::__query_builder::Col::new(table_name, "position"),
            target_entity: __sdk::__query_builder::Col::new(table_name, "target_entity"),
            target_position: __sdk::__query_builder::Col::new(table_name, "target_position"),
            speed: __sdk::__query_builder::Col::new(table_name, "speed"),
            effects: __sdk::__query_builder::Col::new(table_name, "effects"),
            hit_radius: __sdk::__query_builder::Col::new(table_name, "hit_radius"),
            remaining_seconds: __sdk::__query_builder::Col::new(table_name, "remaining_seconds"),
        }
    }
}

/// Indexed column accessor struct for the table `Projectile`.
///
/// Provides typed access to indexed columns for query building.
pub struct ProjectileIxCols {
    pub id: __sdk::__query_builder::IxCol<Projectile, u64>,
}

impl __sdk::__query_builder::HasIxCols for Projectile {
    type IxCols = ProjectileIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ProjectileIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Projectile {}
