// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ReleaseCastArgs {
    pub spell_id: String,
}

impl From<ReleaseCastArgs> for super::Reducer {
    fn from(args: ReleaseCastArgs) -> Self {
        Self::ReleaseCast {
            spell_id: args.spell_id,
        }
    }
}

impl __sdk::InModule for ReleaseCastArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `release_cast`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait release_cast {
    /// Request that the remote module invoke the reducer `release_cast` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`release_cast:release_cast_then`] to run a callback after the reducer completes.
    fn release_cast(&self, spell_id: String) -> __sdk::Result<()> {
        self.release_cast_then(spell_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `release_cast` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn release_cast_then(
        &self,
        spell_id: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl release_cast for super::RemoteReducers {
    fn release_cast_then(
        &self,
        spell_id: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(ReleaseCastArgs { spell_id }, callback)
    }
}
