// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::resonance_type::Resonance;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `resonance`.
///
/// Obtain a handle from the [`ResonanceTableAccess::resonance`] method on [`super::RemoteTables`],
/// like `ctx.db.resonance()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.resonance().on_insert(...)`.
pub struct ResonanceTableHandle<'ctx> {
    imp: __sdk::TableHandle<Resonance>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `resonance`.
pub struct ResonanceTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for ResonanceTableAccessor {
    type Row = Resonance;
    type Handle<'db> = ResonanceTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.resonance()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `resonance`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ResonanceTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ResonanceTableHandle`], which mediates access to the table `resonance`.
    fn resonance(&self) -> ResonanceTableHandle<'_>;
}

impl ResonanceTableAccess for super::RemoteTables {
    fn resonance(&self) -> ResonanceTableHandle<'_> {
        ResonanceTableHandle {
            imp: self.imp.get_table::<Resonance>("resonance"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ResonanceInsertCallbackId(__sdk::CallbackId);
pub struct ResonanceDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for ResonanceTableHandle<'ctx> {
    type Row = Resonance;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Resonance> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for ResonanceTableHandle<'ctx> {
    type Row = Resonance;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Resonance> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ResonanceInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ResonanceInsertCallbackId {
        ResonanceInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ResonanceInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ResonanceDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ResonanceDeleteCallbackId {
        ResonanceDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ResonanceDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for ResonanceTableHandle<'ctx> {
    type InsertCallbackId = ResonanceInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ResonanceInsertCallbackId {
        ResonanceInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ResonanceInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for ResonanceTableHandle<'ctx> {
    type DeleteCallbackId = ResonanceDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ResonanceDeleteCallbackId {
        ResonanceDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ResonanceDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct ResonanceUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ResonanceTableHandle<'ctx> {
    type UpdateCallbackId = ResonanceUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ResonanceUpdateCallbackId {
        ResonanceUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ResonanceUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for ResonanceTableHandle<'ctx> {
    type UpdateCallbackId = ResonanceUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ResonanceUpdateCallbackId {
        ResonanceUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ResonanceUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `resonance`,
/// which allows point queries on the field of the same name
/// via the [`ResonanceIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.resonance().id().find(...)`.
pub struct ResonanceIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Resonance, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ResonanceTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `resonance`.
    pub fn id(&self) -> ResonanceIdUnique<'ctx> {
        ResonanceIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ResonanceIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Resonance> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Resonance>("resonance");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Resonance>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Resonance>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Resonance`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait resonanceQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Resonance`.
    fn resonance(&self) -> __sdk::__query_builder::Table<Resonance>;
}

impl resonanceQueryTableAccess for __sdk::QueryTableAccessor {
    fn resonance(&self) -> __sdk::__query_builder::Table<Resonance> {
        __sdk::__query_builder::Table::new("resonance")
    }
}
