// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RevokeApiKeyArgs {
    pub id: __sdk::Uuid,
}

impl From<RevokeApiKeyArgs> for super::Reducer {
    fn from(args: RevokeApiKeyArgs) -> Self {
        Self::RevokeApiKey { id: args.id }
    }
}

impl __sdk::InModule for RevokeApiKeyArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `revoke_api_key`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait revoke_api_key {
    /// Request that the remote module invoke the reducer `revoke_api_key` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`revoke_api_key:revoke_api_key_then`] to run a callback after the reducer completes.
    fn revoke_api_key(&self, id: __sdk::Uuid) -> __sdk::Result<()> {
        self.revoke_api_key_then(id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `revoke_api_key` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn revoke_api_key_then(
        &self,
        id: __sdk::Uuid,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl revoke_api_key for super::RemoteReducers {
    fn revoke_api_key_then(
        &self,
        id: __sdk::Uuid,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(RevokeApiKeyArgs { id }, callback)
    }
}
