// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::session_type::Session;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `session`.
///
/// Obtain a handle from the [`SessionTableAccess::session`] method on [`super::RemoteTables`],
/// like `ctx.db.session()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.session().on_insert(...)`.
pub struct SessionTableHandle<'ctx> {
    imp: __sdk::TableHandle<Session>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `session`.
pub struct SessionTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for SessionTableAccessor {
    type Row = Session;
    type Handle<'db> = SessionTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.session()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `session`.
///
/// Implemented for [`super::RemoteTables`].
pub trait SessionTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`SessionTableHandle`], which mediates access to the table `session`.
    fn session(&self) -> SessionTableHandle<'_>;
}

impl SessionTableAccess for super::RemoteTables {
    fn session(&self) -> SessionTableHandle<'_> {
        SessionTableHandle {
            imp: self.imp.get_table::<Session>("session"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct SessionInsertCallbackId(__sdk::CallbackId);
pub struct SessionDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for SessionTableHandle<'ctx> {
    type Row = Session;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Session> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for SessionTableHandle<'ctx> {
    type Row = Session;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Session> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = SessionInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SessionInsertCallbackId {
        SessionInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: SessionInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = SessionDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SessionDeleteCallbackId {
        SessionDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: SessionDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for SessionTableHandle<'ctx> {
    type InsertCallbackId = SessionInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SessionInsertCallbackId {
        SessionInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: SessionInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for SessionTableHandle<'ctx> {
    type DeleteCallbackId = SessionDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SessionDeleteCallbackId {
        SessionDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: SessionDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct SessionUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for SessionTableHandle<'ctx> {
    type UpdateCallbackId = SessionUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> SessionUpdateCallbackId {
        SessionUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: SessionUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for SessionTableHandle<'ctx> {
    type UpdateCallbackId = SessionUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> SessionUpdateCallbackId {
        SessionUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: SessionUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `identity` unique index on the table `session`,
/// which allows point queries on the field of the same name
/// via the [`SessionIdentityUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.session().identity().find(...)`.
pub struct SessionIdentityUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Session, __sdk::Identity>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> SessionTableHandle<'ctx> {
    /// Get a handle on the `identity` unique index on the table `session`.
    pub fn identity(&self) -> SessionIdentityUnique<'ctx> {
        SessionIdentityUnique {
            imp: self
                .imp
                .get_unique_constraint::<__sdk::Identity>("identity"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> SessionIdentityUnique<'ctx> {
    /// Find the subscribed row whose `identity` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &__sdk::Identity) -> Option<Session> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Session>("session");
    _table.add_unique_constraint::<__sdk::Identity>("identity", |row| &row.identity);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Session>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Session>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Session`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait sessionQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Session`.
    fn session(&self) -> __sdk::__query_builder::Table<Session>;
}

impl sessionQueryTableAccess for __sdk::QueryTableAccessor {
    fn session(&self) -> __sdk::__query_builder::Table<Session> {
        __sdk::__query_builder::Table::new("session")
    }
}
