// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Session {
    pub identity: __sdk::Identity,
    pub account_id: u64,
    pub character_id: Option<__sdk::Uuid>,
    pub authenticated_at: __sdk::Timestamp,
}

impl __sdk::InModule for Session {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Session`.
///
/// Provides typed access to columns for query building.
pub struct SessionCols {
    pub identity: __sdk::__query_builder::Col<Session, __sdk::Identity>,
    pub account_id: __sdk::__query_builder::Col<Session, u64>,
    pub character_id: __sdk::__query_builder::Col<Session, Option<__sdk::Uuid>>,
    pub authenticated_at: __sdk::__query_builder::Col<Session, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for Session {
    type Cols = SessionCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SessionCols {
            identity: __sdk::__query_builder::Col::new(table_name, "identity"),
            account_id: __sdk::__query_builder::Col::new(table_name, "account_id"),
            character_id: __sdk::__query_builder::Col::new(table_name, "character_id"),
            authenticated_at: __sdk::__query_builder::Col::new(table_name, "authenticated_at"),
        }
    }
}

/// Indexed column accessor struct for the table `Session`.
///
/// Provides typed access to indexed columns for query building.
pub struct SessionIxCols {
    pub account_id: __sdk::__query_builder::IxCol<Session, u64>,
    pub character_id: __sdk::__query_builder::IxCol<Session, Option<__sdk::Uuid>>,
    pub identity: __sdk::__query_builder::IxCol<Session, __sdk::Identity>,
}

impl __sdk::__query_builder::HasIxCols for Session {
    type IxCols = SessionIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SessionIxCols {
            account_id: __sdk::__query_builder::IxCol::new(table_name, "account_id"),
            character_id: __sdk::__query_builder::IxCol::new(table_name, "character_id"),
            identity: __sdk::__query_builder::IxCol::new(table_name, "identity"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Session {}
