// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetInscriptionArgs {
    pub slot: String,
    pub essence: Option<String>,
    pub modifiers: Vec<String>,
    pub ancient_word: Option<String>,
}

impl From<SetInscriptionArgs> for super::Reducer {
    fn from(args: SetInscriptionArgs) -> Self {
        Self::SetInscription {
            slot: args.slot,
            essence: args.essence,
            modifiers: args.modifiers,
            ancient_word: args.ancient_word,
        }
    }
}

impl __sdk::InModule for SetInscriptionArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_inscription`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_inscription {
    /// Request that the remote module invoke the reducer `set_inscription` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`set_inscription:set_inscription_then`] to run a callback after the reducer completes.
    fn set_inscription(
        &self,
        slot: String,
        essence: Option<String>,
        modifiers: Vec<String>,
        ancient_word: Option<String>,
    ) -> __sdk::Result<()> {
        self.set_inscription_then(slot, essence, modifiers, ancient_word, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `set_inscription` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn set_inscription_then(
        &self,
        slot: String,
        essence: Option<String>,
        modifiers: Vec<String>,
        ancient_word: Option<String>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl set_inscription for super::RemoteReducers {
    fn set_inscription_then(
        &self,
        slot: String,
        essence: Option<String>,
        modifiers: Vec<String>,
        ancient_word: Option<String>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            SetInscriptionArgs {
                slot,
                essence,
                modifiers,
                ancient_word,
            },
            callback,
        )
    }
}
