// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetAbilitySelectionArgs {
    pub slot: String,
    pub ability_id: String,
}

impl From<SetAbilitySelectionArgs> for super::Reducer {
    fn from(args: SetAbilitySelectionArgs) -> Self {
        Self::SetAbilitySelection {
            slot: args.slot,
            ability_id: args.ability_id,
        }
    }
}

impl __sdk::InModule for SetAbilitySelectionArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_ability_selection`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_ability_selection {
    /// Request that the remote module invoke the reducer `set_ability_selection` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`set_ability_selection:set_ability_selection_then`] to run a callback after the reducer completes.
    fn set_ability_selection(&self, slot: String, ability_id: String) -> __sdk::Result<()> {
        self.set_ability_selection_then(slot, ability_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `set_ability_selection` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn set_ability_selection_then(
        &self,
        slot: String,
        ability_id: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl set_ability_selection for super::RemoteReducers {
    fn set_ability_selection_then(
        &self,
        slot: String,
        ability_id: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(SetAbilitySelectionArgs { slot, ability_id }, callback)
    }
}
