// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetArmorInscriptionArgs {
    pub slot: String,
    pub root_word: Option<String>,
    pub secondary_words: Vec<String>,
}

impl From<SetArmorInscriptionArgs> for super::Reducer {
    fn from(args: SetArmorInscriptionArgs) -> Self {
        Self::SetArmorInscription {
            slot: args.slot,
            root_word: args.root_word,
            secondary_words: args.secondary_words,
        }
    }
}

impl __sdk::InModule for SetArmorInscriptionArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_armor_inscription`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_armor_inscription {
    /// Request that the remote module invoke the reducer `set_armor_inscription` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`set_armor_inscription:set_armor_inscription_then`] to run a callback after the reducer completes.
    fn set_armor_inscription(
        &self,
        slot: String,
        root_word: Option<String>,
        secondary_words: Vec<String>,
    ) -> __sdk::Result<()> {
        self.set_armor_inscription_then(slot, root_word, secondary_words, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `set_armor_inscription` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn set_armor_inscription_then(
        &self,
        slot: String,
        root_word: Option<String>,
        secondary_words: Vec<String>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl set_armor_inscription for super::RemoteReducers {
    fn set_armor_inscription_then(
        &self,
        slot: String,
        root_word: Option<String>,
        secondary_words: Vec<String>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            SetArmorInscriptionArgs {
                slot,
                root_word,
                secondary_words,
            },
            callback,
        )
    }
}
