// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::spell_visual_effect_event_type::SpellVisualEffectEvent;
use super::vec_3_row_type::Vec3Row;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `spell_visual_effect`.
///
/// Obtain a handle from the [`SpellVisualEffectTableAccess::spell_visual_effect`] method on [`super::RemoteTables`],
/// like `ctx.db.spell_visual_effect()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.spell_visual_effect().on_insert(...)`.
pub struct SpellVisualEffectTableHandle<'ctx> {
    imp: __sdk::TableHandle<SpellVisualEffectEvent>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `spell_visual_effect`.
pub struct SpellVisualEffectTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for SpellVisualEffectTableAccessor {
    type Row = SpellVisualEffectEvent;
    type Handle<'db> = SpellVisualEffectTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.spell_visual_effect()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `spell_visual_effect`.
///
/// Implemented for [`super::RemoteTables`].
pub trait SpellVisualEffectTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`SpellVisualEffectTableHandle`], which mediates access to the table `spell_visual_effect`.
    fn spell_visual_effect(&self) -> SpellVisualEffectTableHandle<'_>;
}

impl SpellVisualEffectTableAccess for super::RemoteTables {
    fn spell_visual_effect(&self) -> SpellVisualEffectTableHandle<'_> {
        SpellVisualEffectTableHandle {
            imp: self
                .imp
                .get_table::<SpellVisualEffectEvent>("spell_visual_effect"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct SpellVisualEffectInsertCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for SpellVisualEffectTableHandle<'ctx> {
    type Row = SpellVisualEffectEvent;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = SpellVisualEffectEvent> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::EventTable for SpellVisualEffectTableHandle<'ctx> {
    type Row = SpellVisualEffectEvent;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = SpellVisualEffectEvent> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = SpellVisualEffectInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SpellVisualEffectInsertCallbackId {
        SpellVisualEffectInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: SpellVisualEffectInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for SpellVisualEffectTableHandle<'ctx> {
    type InsertCallbackId = SpellVisualEffectInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SpellVisualEffectInsertCallbackId {
        SpellVisualEffectInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: SpellVisualEffectInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<SpellVisualEffectEvent>("spell_visual_effect");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<SpellVisualEffectEvent>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<SpellVisualEffectEvent>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `SpellVisualEffectEvent`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait spell_visual_effectQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `SpellVisualEffectEvent`.
    fn spell_visual_effect(&self) -> __sdk::__query_builder::Table<SpellVisualEffectEvent>;
}

impl spell_visual_effectQueryTableAccess for __sdk::QueryTableAccessor {
    fn spell_visual_effect(&self) -> __sdk::__query_builder::Table<SpellVisualEffectEvent> {
        __sdk::__query_builder::Table::new("spell_visual_effect")
    }
}
