// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::vec_3_row_type::Vec3Row;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SpellVisualEffectEvent {
    pub spell_id: String,
    pub start: Vec3Row,
    pub end: Vec3Row,
}

impl __sdk::InModule for SpellVisualEffectEvent {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `SpellVisualEffectEvent`.
///
/// Provides typed access to columns for query building.
pub struct SpellVisualEffectEventCols {
    pub spell_id: __sdk::__query_builder::Col<SpellVisualEffectEvent, String>,
    pub start: __sdk::__query_builder::Col<SpellVisualEffectEvent, Vec3Row>,
    pub end: __sdk::__query_builder::Col<SpellVisualEffectEvent, Vec3Row>,
}

impl __sdk::__query_builder::HasCols for SpellVisualEffectEvent {
    type Cols = SpellVisualEffectEventCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SpellVisualEffectEventCols {
            spell_id: __sdk::__query_builder::Col::new(table_name, "spell_id"),
            start: __sdk::__query_builder::Col::new(table_name, "start"),
            end: __sdk::__query_builder::Col::new(table_name, "end"),
        }
    }
}

/// Indexed column accessor struct for the table `SpellVisualEffectEvent`.
///
/// Provides typed access to indexed columns for query building.
pub struct SpellVisualEffectEventIxCols {}

impl __sdk::__query_builder::HasIxCols for SpellVisualEffectEvent {
    type IxCols = SpellVisualEffectEventIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SpellVisualEffectEventIxCols {}
    }
}
