// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct StatModifier {
    pub id: u64,
    pub entity_id: u64,
    pub field: String,
    pub is_multiplicative: bool,
    pub amount: f32,
    pub remaining_seconds: Option<f32>,
}

impl __sdk::InModule for StatModifier {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `StatModifier`.
///
/// Provides typed access to columns for query building.
pub struct StatModifierCols {
    pub id: __sdk::__query_builder::Col<StatModifier, u64>,
    pub entity_id: __sdk::__query_builder::Col<StatModifier, u64>,
    pub field: __sdk::__query_builder::Col<StatModifier, String>,
    pub is_multiplicative: __sdk::__query_builder::Col<StatModifier, bool>,
    pub amount: __sdk::__query_builder::Col<StatModifier, f32>,
    pub remaining_seconds: __sdk::__query_builder::Col<StatModifier, Option<f32>>,
}

impl __sdk::__query_builder::HasCols for StatModifier {
    type Cols = StatModifierCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        StatModifierCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
            field: __sdk::__query_builder::Col::new(table_name, "field"),
            is_multiplicative: __sdk::__query_builder::Col::new(table_name, "is_multiplicative"),
            amount: __sdk::__query_builder::Col::new(table_name, "amount"),
            remaining_seconds: __sdk::__query_builder::Col::new(table_name, "remaining_seconds"),
        }
    }
}

/// Indexed column accessor struct for the table `StatModifier`.
///
/// Provides typed access to indexed columns for query building.
pub struct StatModifierIxCols {
    pub entity_id: __sdk::__query_builder::IxCol<StatModifier, u64>,
    pub id: __sdk::__query_builder::IxCol<StatModifier, u64>,
}

impl __sdk::__query_builder::HasIxCols for StatModifier {
    type IxCols = StatModifierIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        StatModifierIxCols {
            entity_id: __sdk::__query_builder::IxCol::new(table_name, "entity_id"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for StatModifier {}
