[package]
name = "bevy_lightyear_game"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[features]
default = ["client"]
client = [
    "bevy/default",
    "dep:bevymmo_client",
    "dep:bevymmo_presentation",
]

[dependencies]
bevy = { workspace = true }
lightyear = { workspace = true }
serde = { workspace = true }
clap = { workspace = true }
config = { workspace = true }
bevymmo_shared = { path = "../../crates/shared" }
bevymmo_client = { path = "../../crates/client", optional = true }
bevymmo_presentation = { path = "../../crates/presentation", optional = true }

[[bin]]
name = "game"
path = "src/main.rs"

[lints]
workspace = true
