[package]
name = "bevy_lightyear_game"
version = "0.1.0"
edition = "2021"

[features]
default = [
    "client",
    "editor",
    "server",
    "netcode",
    "udp",
    "interpolation",
    "prediction",
    "replication",
    "input_native",
]
client = [
    "lightyear/client",
    "bevy/default",
    "dep:bevymmo_client",
    "dep:bevymmo_presentation",
]
editor = ["client", "dep:bevymmo_editor"]
server = ["lightyear/server"]
netcode = ["lightyear/netcode"]
udp = ["lightyear/udp"]
interpolation = ["lightyear/interpolation"]
prediction = ["lightyear/prediction"]
replication = ["lightyear/replication"]
input_native = ["lightyear/input_native"]

[dependencies]
bevy = { workspace = true }
lightyear = { workspace = true }
serde = { workspace = true }
clap = { workspace = true }
config = { workspace = true }
sea-orm = { workspace = true }
sea-orm-migration = { workspace = true }
tokio = { workspace = true }
uuid = { workspace = true }
bevymmo_shared = { path = "../../crates/shared" }
bevymmo_server = { path = "../../crates/server" }
bevymmo_client = { path = "../../crates/client", optional = true }
bevymmo_presentation = { path = "../../crates/presentation", optional = true }
bevymmo_editor = { path = "../../crates/editor", optional = true }

[[bin]]
name = "game"
path = "src/main.rs"
