[package]
name = "bevymmo_client"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
bevy = { workspace = true, features = ["default"] }
lightyear = { workspace = true }
bevymmo_shared = { path = "../shared" }

[lints]
workspace = true
