// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct AccountEconomy {
    pub account_id: u64,
    pub fee_bps: u16,
}

impl __sdk::InModule for AccountEconomy {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `AccountEconomy`.
///
/// Provides typed access to columns for query building.
pub struct AccountEconomyCols {
    pub account_id: __sdk::__query_builder::Col<AccountEconomy, u64>,
    pub fee_bps: __sdk::__query_builder::Col<AccountEconomy, u16>,
}

impl __sdk::__query_builder::HasCols for AccountEconomy {
    type Cols = AccountEconomyCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        AccountEconomyCols {
            account_id: __sdk::__query_builder::Col::new(table_name, "account_id"),
            fee_bps: __sdk::__query_builder::Col::new(table_name, "fee_bps"),
        }
    }
}

/// Indexed column accessor struct for the table `AccountEconomy`.
///
/// Provides typed access to indexed columns for query building.
pub struct AccountEconomyIxCols {
    pub account_id: __sdk::__query_builder::IxCol<AccountEconomy, u64>,
}

impl __sdk::__query_builder::HasIxCols for AccountEconomy {
    type IxCols = AccountEconomyIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        AccountEconomyIxCols {
            account_id: __sdk::__query_builder::IxCol::new(table_name, "account_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for AccountEconomy {}
