// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::account_economy_type::AccountEconomy;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `account_economy`.
///
/// Obtain a handle from the [`AccountEconomyTableAccess::account_economy`] method on [`super::RemoteTables`],
/// like `ctx.db.account_economy()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.account_economy().on_insert(...)`.
pub struct AccountEconomyTableHandle<'ctx> {
    imp: __sdk::TableHandle<AccountEconomy>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `account_economy`.
pub struct AccountEconomyTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for AccountEconomyTableAccessor {
    type Row = AccountEconomy;
    type Handle<'db> = AccountEconomyTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.account_economy()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `account_economy`.
///
/// Implemented for [`super::RemoteTables`].
pub trait AccountEconomyTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`AccountEconomyTableHandle`], which mediates access to the table `account_economy`.
    fn account_economy(&self) -> AccountEconomyTableHandle<'_>;
}

impl AccountEconomyTableAccess for super::RemoteTables {
    fn account_economy(&self) -> AccountEconomyTableHandle<'_> {
        AccountEconomyTableHandle {
            imp: self.imp.get_table::<AccountEconomy>("account_economy"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct AccountEconomyInsertCallbackId(__sdk::CallbackId);
pub struct AccountEconomyDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for AccountEconomyTableHandle<'ctx> {
    type Row = AccountEconomy;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = AccountEconomy> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for AccountEconomyTableHandle<'ctx> {
    type Row = AccountEconomy;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = AccountEconomy> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = AccountEconomyInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AccountEconomyInsertCallbackId {
        AccountEconomyInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: AccountEconomyInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = AccountEconomyDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AccountEconomyDeleteCallbackId {
        AccountEconomyDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: AccountEconomyDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for AccountEconomyTableHandle<'ctx> {
    type InsertCallbackId = AccountEconomyInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AccountEconomyInsertCallbackId {
        AccountEconomyInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: AccountEconomyInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for AccountEconomyTableHandle<'ctx> {
    type DeleteCallbackId = AccountEconomyDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AccountEconomyDeleteCallbackId {
        AccountEconomyDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: AccountEconomyDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct AccountEconomyUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for AccountEconomyTableHandle<'ctx> {
    type UpdateCallbackId = AccountEconomyUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> AccountEconomyUpdateCallbackId {
        AccountEconomyUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: AccountEconomyUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for AccountEconomyTableHandle<'ctx> {
    type UpdateCallbackId = AccountEconomyUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> AccountEconomyUpdateCallbackId {
        AccountEconomyUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: AccountEconomyUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `account_id` unique index on the table `account_economy`,
/// which allows point queries on the field of the same name
/// via the [`AccountEconomyAccountIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.account_economy().account_id().find(...)`.
pub struct AccountEconomyAccountIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<AccountEconomy, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> AccountEconomyTableHandle<'ctx> {
    /// Get a handle on the `account_id` unique index on the table `account_economy`.
    pub fn account_id(&self) -> AccountEconomyAccountIdUnique<'ctx> {
        AccountEconomyAccountIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("account_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> AccountEconomyAccountIdUnique<'ctx> {
    /// Find the subscribed row whose `account_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<AccountEconomy> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<AccountEconomy>("account_economy");
    _table.add_unique_constraint::<u64>("account_id", |row| &row.account_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<AccountEconomy>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<AccountEconomy>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `AccountEconomy`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait account_economyQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `AccountEconomy`.
    fn account_economy(&self) -> __sdk::__query_builder::Table<AccountEconomy>;
}

impl account_economyQueryTableAccess for __sdk::QueryTableAccessor {
    fn account_economy(&self) -> __sdk::__query_builder::Table<AccountEconomy> {
        __sdk::__query_builder::Table::new("account_economy")
    }
}
