// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::crowd_control_kind_row_type::CrowdControlKindRow;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ActiveStatus {
    pub id: u64,
    pub entity_id: u64,
    pub status_id: String,
    pub source: Option<u64>,
    pub stacks: u16,
    pub potency: f32,
    pub remaining_seconds: f32,
    pub total_seconds: f32,
    pub control_kind: Option<CrowdControlKindRow>,
}

impl __sdk::InModule for ActiveStatus {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `ActiveStatus`.
///
/// Provides typed access to columns for query building.
pub struct ActiveStatusCols {
    pub id: __sdk::__query_builder::Col<ActiveStatus, u64>,
    pub entity_id: __sdk::__query_builder::Col<ActiveStatus, u64>,
    pub status_id: __sdk::__query_builder::Col<ActiveStatus, String>,
    pub source: __sdk::__query_builder::Col<ActiveStatus, Option<u64>>,
    pub stacks: __sdk::__query_builder::Col<ActiveStatus, u16>,
    pub potency: __sdk::__query_builder::Col<ActiveStatus, f32>,
    pub remaining_seconds: __sdk::__query_builder::Col<ActiveStatus, f32>,
    pub total_seconds: __sdk::__query_builder::Col<ActiveStatus, f32>,
    pub control_kind: __sdk::__query_builder::Col<ActiveStatus, Option<CrowdControlKindRow>>,
}

impl __sdk::__query_builder::HasCols for ActiveStatus {
    type Cols = ActiveStatusCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ActiveStatusCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
            status_id: __sdk::__query_builder::Col::new(table_name, "status_id"),
            source: __sdk::__query_builder::Col::new(table_name, "source"),
            stacks: __sdk::__query_builder::Col::new(table_name, "stacks"),
            potency: __sdk::__query_builder::Col::new(table_name, "potency"),
            remaining_seconds: __sdk::__query_builder::Col::new(table_name, "remaining_seconds"),
            total_seconds: __sdk::__query_builder::Col::new(table_name, "total_seconds"),
            control_kind: __sdk::__query_builder::Col::new(table_name, "control_kind"),
        }
    }
}

/// Indexed column accessor struct for the table `ActiveStatus`.
///
/// Provides typed access to indexed columns for query building.
pub struct ActiveStatusIxCols {
    pub entity_id: __sdk::__query_builder::IxCol<ActiveStatus, u64>,
    pub id: __sdk::__query_builder::IxCol<ActiveStatus, u64>,
}

impl __sdk::__query_builder::HasIxCols for ActiveStatus {
    type IxCols = ActiveStatusIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ActiveStatusIxCols {
            entity_id: __sdk::__query_builder::IxCol::new(table_name, "entity_id"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ActiveStatus {}
