// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::active_status_type::ActiveStatus;
use super::crowd_control_kind_row_type::CrowdControlKindRow;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `active_status`.
///
/// Obtain a handle from the [`ActiveStatusTableAccess::active_status`] method on [`super::RemoteTables`],
/// like `ctx.db.active_status()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.active_status().on_insert(...)`.
pub struct ActiveStatusTableHandle<'ctx> {
    imp: __sdk::TableHandle<ActiveStatus>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `active_status`.
pub struct ActiveStatusTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for ActiveStatusTableAccessor {
    type Row = ActiveStatus;
    type Handle<'db> = ActiveStatusTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.active_status()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `active_status`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ActiveStatusTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ActiveStatusTableHandle`], which mediates access to the table `active_status`.
    fn active_status(&self) -> ActiveStatusTableHandle<'_>;
}

impl ActiveStatusTableAccess for super::RemoteTables {
    fn active_status(&self) -> ActiveStatusTableHandle<'_> {
        ActiveStatusTableHandle {
            imp: self.imp.get_table::<ActiveStatus>("active_status"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ActiveStatusInsertCallbackId(__sdk::CallbackId);
pub struct ActiveStatusDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for ActiveStatusTableHandle<'ctx> {
    type Row = ActiveStatus;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ActiveStatus> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for ActiveStatusTableHandle<'ctx> {
    type Row = ActiveStatus;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ActiveStatus> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ActiveStatusInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ActiveStatusInsertCallbackId {
        ActiveStatusInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ActiveStatusInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ActiveStatusDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ActiveStatusDeleteCallbackId {
        ActiveStatusDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ActiveStatusDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for ActiveStatusTableHandle<'ctx> {
    type InsertCallbackId = ActiveStatusInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ActiveStatusInsertCallbackId {
        ActiveStatusInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ActiveStatusInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for ActiveStatusTableHandle<'ctx> {
    type DeleteCallbackId = ActiveStatusDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ActiveStatusDeleteCallbackId {
        ActiveStatusDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ActiveStatusDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct ActiveStatusUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ActiveStatusTableHandle<'ctx> {
    type UpdateCallbackId = ActiveStatusUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ActiveStatusUpdateCallbackId {
        ActiveStatusUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ActiveStatusUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for ActiveStatusTableHandle<'ctx> {
    type UpdateCallbackId = ActiveStatusUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ActiveStatusUpdateCallbackId {
        ActiveStatusUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ActiveStatusUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `active_status`,
/// which allows point queries on the field of the same name
/// via the [`ActiveStatusIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.active_status().id().find(...)`.
pub struct ActiveStatusIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<ActiveStatus, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ActiveStatusTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `active_status`.
    pub fn id(&self) -> ActiveStatusIdUnique<'ctx> {
        ActiveStatusIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ActiveStatusIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<ActiveStatus> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<ActiveStatus>("active_status");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<ActiveStatus>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<ActiveStatus>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `ActiveStatus`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait active_statusQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `ActiveStatus`.
    fn active_status(&self) -> __sdk::__query_builder::Table<ActiveStatus>;
}

impl active_statusQueryTableAccess for __sdk::QueryTableAccessor {
    fn active_status(&self) -> __sdk::__query_builder::Table<ActiveStatus> {
        __sdk::__query_builder::Table::new("active_status")
    }
}
