// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ApiKeyMeta {
    pub id: __sdk::Uuid,
    pub name: String,
    pub prefix: String,
    pub created_at: __sdk::Timestamp,
    pub last_used_at: Option<__sdk::Timestamp>,
}

impl __sdk::InModule for ApiKeyMeta {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `ApiKeyMeta`.
///
/// Provides typed access to columns for query building.
pub struct ApiKeyMetaCols {
    pub id: __sdk::__query_builder::Col<ApiKeyMeta, __sdk::Uuid>,
    pub name: __sdk::__query_builder::Col<ApiKeyMeta, String>,
    pub prefix: __sdk::__query_builder::Col<ApiKeyMeta, String>,
    pub created_at: __sdk::__query_builder::Col<ApiKeyMeta, __sdk::Timestamp>,
    pub last_used_at: __sdk::__query_builder::Col<ApiKeyMeta, Option<__sdk::Timestamp>>,
}

impl __sdk::__query_builder::HasCols for ApiKeyMeta {
    type Cols = ApiKeyMetaCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ApiKeyMetaCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            prefix: __sdk::__query_builder::Col::new(table_name, "prefix"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            last_used_at: __sdk::__query_builder::Col::new(table_name, "last_used_at"),
        }
    }
}
