// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AwardResonanceXpArgs {
    pub root_word_id: String,
    pub xp_amount: u64,
}

impl From<AwardResonanceXpArgs> for super::Reducer {
    fn from(args: AwardResonanceXpArgs) -> Self {
        Self::AwardResonanceXp {
            root_word_id: args.root_word_id,
            xp_amount: args.xp_amount,
        }
    }
}

impl __sdk::InModule for AwardResonanceXpArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `award_resonance_xp`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait award_resonance_xp {
    /// Request that the remote module invoke the reducer `award_resonance_xp` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`award_resonance_xp:award_resonance_xp_then`] to run a callback after the reducer completes.
    fn award_resonance_xp(&self, root_word_id: String, xp_amount: u64) -> __sdk::Result<()> {
        self.award_resonance_xp_then(root_word_id, xp_amount, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `award_resonance_xp` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn award_resonance_xp_then(
        &self,
        root_word_id: String,
        xp_amount: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl award_resonance_xp for super::RemoteReducers {
    fn award_resonance_xp_then(
        &self,
        root_word_id: String,
        xp_amount: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            AwardResonanceXpArgs {
                root_word_id,
                xp_amount,
            },
            callback,
        )
    }
}
