// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::cast_ended_event_type::CastEndedEvent;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `cast_ended`.
///
/// Obtain a handle from the [`CastEndedTableAccess::cast_ended`] method on [`super::RemoteTables`],
/// like `ctx.db.cast_ended()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.cast_ended().on_insert(...)`.
pub struct CastEndedTableHandle<'ctx> {
    imp: __sdk::TableHandle<CastEndedEvent>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `cast_ended`.
pub struct CastEndedTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for CastEndedTableAccessor {
    type Row = CastEndedEvent;
    type Handle<'db> = CastEndedTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.cast_ended()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `cast_ended`.
///
/// Implemented for [`super::RemoteTables`].
pub trait CastEndedTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`CastEndedTableHandle`], which mediates access to the table `cast_ended`.
    fn cast_ended(&self) -> CastEndedTableHandle<'_>;
}

impl CastEndedTableAccess for super::RemoteTables {
    fn cast_ended(&self) -> CastEndedTableHandle<'_> {
        CastEndedTableHandle {
            imp: self.imp.get_table::<CastEndedEvent>("cast_ended"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct CastEndedInsertCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for CastEndedTableHandle<'ctx> {
    type Row = CastEndedEvent;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = CastEndedEvent> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::EventTable for CastEndedTableHandle<'ctx> {
    type Row = CastEndedEvent;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = CastEndedEvent> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = CastEndedInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CastEndedInsertCallbackId {
        CastEndedInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: CastEndedInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for CastEndedTableHandle<'ctx> {
    type InsertCallbackId = CastEndedInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CastEndedInsertCallbackId {
        CastEndedInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: CastEndedInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<CastEndedEvent>("cast_ended");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<CastEndedEvent>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<CastEndedEvent>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `CastEndedEvent`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait cast_endedQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `CastEndedEvent`.
    fn cast_ended(&self) -> __sdk::__query_builder::Table<CastEndedEvent>;
}

impl cast_endedQueryTableAccess for __sdk::QueryTableAccessor {
    fn cast_ended(&self) -> __sdk::__query_builder::Table<CastEndedEvent> {
        __sdk::__query_builder::Table::new("cast_ended")
    }
}
