// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct CastEndedEvent {
    pub entity_id: u64,
    pub spell_id: String,
    pub interrupted: bool,
}

impl __sdk::InModule for CastEndedEvent {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `CastEndedEvent`.
///
/// Provides typed access to columns for query building.
pub struct CastEndedEventCols {
    pub entity_id: __sdk::__query_builder::Col<CastEndedEvent, u64>,
    pub spell_id: __sdk::__query_builder::Col<CastEndedEvent, String>,
    pub interrupted: __sdk::__query_builder::Col<CastEndedEvent, bool>,
}

impl __sdk::__query_builder::HasCols for CastEndedEvent {
    type Cols = CastEndedEventCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        CastEndedEventCols {
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
            spell_id: __sdk::__query_builder::Col::new(table_name, "spell_id"),
            interrupted: __sdk::__query_builder::Col::new(table_name, "interrupted"),
        }
    }
}

/// Indexed column accessor struct for the table `CastEndedEvent`.
///
/// Provides typed access to indexed columns for query building.
pub struct CastEndedEventIxCols {}

impl __sdk::__query_builder::HasIxCols for CastEndedEvent {
    type IxCols = CastEndedEventIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        CastEndedEventIxCols {}
    }
}
