// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::character_wallet_type::CharacterWallet;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `character_wallet`.
///
/// Obtain a handle from the [`CharacterWalletTableAccess::character_wallet`] method on [`super::RemoteTables`],
/// like `ctx.db.character_wallet()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.character_wallet().on_insert(...)`.
pub struct CharacterWalletTableHandle<'ctx> {
    imp: __sdk::TableHandle<CharacterWallet>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `character_wallet`.
pub struct CharacterWalletTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for CharacterWalletTableAccessor {
    type Row = CharacterWallet;
    type Handle<'db> = CharacterWalletTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.character_wallet()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `character_wallet`.
///
/// Implemented for [`super::RemoteTables`].
pub trait CharacterWalletTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`CharacterWalletTableHandle`], which mediates access to the table `character_wallet`.
    fn character_wallet(&self) -> CharacterWalletTableHandle<'_>;
}

impl CharacterWalletTableAccess for super::RemoteTables {
    fn character_wallet(&self) -> CharacterWalletTableHandle<'_> {
        CharacterWalletTableHandle {
            imp: self.imp.get_table::<CharacterWallet>("character_wallet"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct CharacterWalletInsertCallbackId(__sdk::CallbackId);
pub struct CharacterWalletDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for CharacterWalletTableHandle<'ctx> {
    type Row = CharacterWallet;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = CharacterWallet> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for CharacterWalletTableHandle<'ctx> {
    type Row = CharacterWallet;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = CharacterWallet> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = CharacterWalletInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CharacterWalletInsertCallbackId {
        CharacterWalletInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: CharacterWalletInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = CharacterWalletDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CharacterWalletDeleteCallbackId {
        CharacterWalletDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: CharacterWalletDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for CharacterWalletTableHandle<'ctx> {
    type InsertCallbackId = CharacterWalletInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CharacterWalletInsertCallbackId {
        CharacterWalletInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: CharacterWalletInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for CharacterWalletTableHandle<'ctx> {
    type DeleteCallbackId = CharacterWalletDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CharacterWalletDeleteCallbackId {
        CharacterWalletDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: CharacterWalletDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct CharacterWalletUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for CharacterWalletTableHandle<'ctx> {
    type UpdateCallbackId = CharacterWalletUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> CharacterWalletUpdateCallbackId {
        CharacterWalletUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: CharacterWalletUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for CharacterWalletTableHandle<'ctx> {
    type UpdateCallbackId = CharacterWalletUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> CharacterWalletUpdateCallbackId {
        CharacterWalletUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: CharacterWalletUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<CharacterWallet>("character_wallet");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<CharacterWallet>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<CharacterWallet>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `CharacterWallet`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait character_walletQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `CharacterWallet`.
    fn character_wallet(&self) -> __sdk::__query_builder::Table<CharacterWallet>;
}

impl character_walletQueryTableAccess for __sdk::QueryTableAccessor {
    fn character_wallet(&self) -> __sdk::__query_builder::Table<CharacterWallet> {
        __sdk::__query_builder::Table::new("character_wallet")
    }
}
