// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct CharacterWallet {
    pub character_id: __sdk::Uuid,
    pub gold: u64,
}

impl __sdk::InModule for CharacterWallet {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `CharacterWallet`.
///
/// Provides typed access to columns for query building.
pub struct CharacterWalletCols {
    pub character_id: __sdk::__query_builder::Col<CharacterWallet, __sdk::Uuid>,
    pub gold: __sdk::__query_builder::Col<CharacterWallet, u64>,
}

impl __sdk::__query_builder::HasCols for CharacterWallet {
    type Cols = CharacterWalletCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        CharacterWalletCols {
            character_id: __sdk::__query_builder::Col::new(table_name, "character_id"),
            gold: __sdk::__query_builder::Col::new(table_name, "gold"),
        }
    }
}

/// Indexed column accessor struct for the table `CharacterWallet`.
///
/// Provides typed access to indexed columns for query building.
pub struct CharacterWalletIxCols {
    pub character_id: __sdk::__query_builder::IxCol<CharacterWallet, __sdk::Uuid>,
}

impl __sdk::__query_builder::HasIxCols for CharacterWallet {
    type IxCols = CharacterWalletIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        CharacterWalletIxCols {
            character_id: __sdk::__query_builder::IxCol::new(table_name, "character_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for CharacterWallet {}
