// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Cooldown {
    pub id: u64,
    pub entity_id: u64,
    pub ability_id: String,
    pub elapsed_seconds: f32,
    pub duration_seconds: f32,
}

impl __sdk::InModule for Cooldown {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Cooldown`.
///
/// Provides typed access to columns for query building.
pub struct CooldownCols {
    pub id: __sdk::__query_builder::Col<Cooldown, u64>,
    pub entity_id: __sdk::__query_builder::Col<Cooldown, u64>,
    pub ability_id: __sdk::__query_builder::Col<Cooldown, String>,
    pub elapsed_seconds: __sdk::__query_builder::Col<Cooldown, f32>,
    pub duration_seconds: __sdk::__query_builder::Col<Cooldown, f32>,
}

impl __sdk::__query_builder::HasCols for Cooldown {
    type Cols = CooldownCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        CooldownCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
            ability_id: __sdk::__query_builder::Col::new(table_name, "ability_id"),
            elapsed_seconds: __sdk::__query_builder::Col::new(table_name, "elapsed_seconds"),
            duration_seconds: __sdk::__query_builder::Col::new(table_name, "duration_seconds"),
        }
    }
}

/// Indexed column accessor struct for the table `Cooldown`.
///
/// Provides typed access to indexed columns for query building.
pub struct CooldownIxCols {
    pub id: __sdk::__query_builder::IxCol<Cooldown, u64>,
}

impl __sdk::__query_builder::HasIxCols for Cooldown {
    type IxCols = CooldownIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        CooldownIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Cooldown {}
