// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::cooldown_type::Cooldown;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `cooldown`.
///
/// Obtain a handle from the [`CooldownTableAccess::cooldown`] method on [`super::RemoteTables`],
/// like `ctx.db.cooldown()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.cooldown().on_insert(...)`.
pub struct CooldownTableHandle<'ctx> {
    imp: __sdk::TableHandle<Cooldown>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `cooldown`.
pub struct CooldownTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for CooldownTableAccessor {
    type Row = Cooldown;
    type Handle<'db> = CooldownTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.cooldown()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `cooldown`.
///
/// Implemented for [`super::RemoteTables`].
pub trait CooldownTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`CooldownTableHandle`], which mediates access to the table `cooldown`.
    fn cooldown(&self) -> CooldownTableHandle<'_>;
}

impl CooldownTableAccess for super::RemoteTables {
    fn cooldown(&self) -> CooldownTableHandle<'_> {
        CooldownTableHandle {
            imp: self.imp.get_table::<Cooldown>("cooldown"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct CooldownInsertCallbackId(__sdk::CallbackId);
pub struct CooldownDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for CooldownTableHandle<'ctx> {
    type Row = Cooldown;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Cooldown> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for CooldownTableHandle<'ctx> {
    type Row = Cooldown;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Cooldown> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = CooldownInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CooldownInsertCallbackId {
        CooldownInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: CooldownInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = CooldownDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CooldownDeleteCallbackId {
        CooldownDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: CooldownDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for CooldownTableHandle<'ctx> {
    type InsertCallbackId = CooldownInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CooldownInsertCallbackId {
        CooldownInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: CooldownInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for CooldownTableHandle<'ctx> {
    type DeleteCallbackId = CooldownDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CooldownDeleteCallbackId {
        CooldownDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: CooldownDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct CooldownUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for CooldownTableHandle<'ctx> {
    type UpdateCallbackId = CooldownUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> CooldownUpdateCallbackId {
        CooldownUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: CooldownUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for CooldownTableHandle<'ctx> {
    type UpdateCallbackId = CooldownUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> CooldownUpdateCallbackId {
        CooldownUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: CooldownUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `cooldown`,
/// which allows point queries on the field of the same name
/// via the [`CooldownIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.cooldown().id().find(...)`.
pub struct CooldownIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Cooldown, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> CooldownTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `cooldown`.
    pub fn id(&self) -> CooldownIdUnique<'ctx> {
        CooldownIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> CooldownIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Cooldown> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Cooldown>("cooldown");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Cooldown>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Cooldown>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Cooldown`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait cooldownQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Cooldown`.
    fn cooldown(&self) -> __sdk::__query_builder::Table<Cooldown>;
}

impl cooldownQueryTableAccess for __sdk::QueryTableAccessor {
    fn cooldown(&self) -> __sdk::__query_builder::Table<Cooldown> {
        __sdk::__query_builder::Table::new("cooldown")
    }
}
