// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::vec_3_row_type::Vec3Row;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct CraftSession {
    pub entity_id: u64,
    pub npc_entity_id: u64,
    pub item_id: String,
    pub quantity: u32,
    pub elapsed_seconds: f32,
    pub required_seconds: f32,
    pub start_position: Vec3Row,
}

impl __sdk::InModule for CraftSession {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `CraftSession`.
///
/// Provides typed access to columns for query building.
pub struct CraftSessionCols {
    pub entity_id: __sdk::__query_builder::Col<CraftSession, u64>,
    pub npc_entity_id: __sdk::__query_builder::Col<CraftSession, u64>,
    pub item_id: __sdk::__query_builder::Col<CraftSession, String>,
    pub quantity: __sdk::__query_builder::Col<CraftSession, u32>,
    pub elapsed_seconds: __sdk::__query_builder::Col<CraftSession, f32>,
    pub required_seconds: __sdk::__query_builder::Col<CraftSession, f32>,
    pub start_position: __sdk::__query_builder::Col<CraftSession, Vec3Row>,
}

impl __sdk::__query_builder::HasCols for CraftSession {
    type Cols = CraftSessionCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        CraftSessionCols {
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
            npc_entity_id: __sdk::__query_builder::Col::new(table_name, "npc_entity_id"),
            item_id: __sdk::__query_builder::Col::new(table_name, "item_id"),
            quantity: __sdk::__query_builder::Col::new(table_name, "quantity"),
            elapsed_seconds: __sdk::__query_builder::Col::new(table_name, "elapsed_seconds"),
            required_seconds: __sdk::__query_builder::Col::new(table_name, "required_seconds"),
            start_position: __sdk::__query_builder::Col::new(table_name, "start_position"),
        }
    }
}

/// Indexed column accessor struct for the table `CraftSession`.
///
/// Provides typed access to indexed columns for query building.
pub struct CraftSessionIxCols {
    pub entity_id: __sdk::__query_builder::IxCol<CraftSession, u64>,
}

impl __sdk::__query_builder::HasIxCols for CraftSession {
    type IxCols = CraftSessionIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        CraftSessionIxCols {
            entity_id: __sdk::__query_builder::IxCol::new(table_name, "entity_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for CraftSession {}
