// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CreateApiKeyArgs {
    pub id: __sdk::Uuid,
    pub name: String,
    pub prefix: String,
    pub secret: String,
}

impl From<CreateApiKeyArgs> for super::Reducer {
    fn from(args: CreateApiKeyArgs) -> Self {
        Self::CreateApiKey {
            id: args.id,
            name: args.name,
            prefix: args.prefix,
            secret: args.secret,
        }
    }
}

impl __sdk::InModule for CreateApiKeyArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `create_api_key`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait create_api_key {
    /// Request that the remote module invoke the reducer `create_api_key` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`create_api_key:create_api_key_then`] to run a callback after the reducer completes.
    fn create_api_key(
        &self,
        id: __sdk::Uuid,
        name: String,
        prefix: String,
        secret: String,
    ) -> __sdk::Result<()> {
        self.create_api_key_then(id, name, prefix, secret, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `create_api_key` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn create_api_key_then(
        &self,
        id: __sdk::Uuid,
        name: String,
        prefix: String,
        secret: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl create_api_key for super::RemoteReducers {
    fn create_api_key_then(
        &self,
        id: __sdk::Uuid,
        name: String,
        prefix: String,
        secret: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            CreateApiKeyArgs {
                id,
                name,
                prefix,
                secret,
            },
            callback,
        )
    }
}
