// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct DestroyItemArgs {
    pub instance_id: u64,
}

impl From<DestroyItemArgs> for super::Reducer {
    fn from(args: DestroyItemArgs) -> Self {
        Self::DestroyItem {
            instance_id: args.instance_id,
        }
    }
}

impl __sdk::InModule for DestroyItemArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `destroy_item`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait destroy_item {
    /// Request that the remote module invoke the reducer `destroy_item` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`destroy_item:destroy_item_then`] to run a callback after the reducer completes.
    fn destroy_item(&self, instance_id: u64) -> __sdk::Result<()> {
        self.destroy_item_then(instance_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `destroy_item` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn destroy_item_then(
        &self,
        instance_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl destroy_item for super::RemoteReducers {
    fn destroy_item_then(
        &self,
        instance_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(DestroyItemArgs { instance_id }, callback)
    }
}
