// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::vec_3_row_type::Vec3Row;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct EidolonCastArgs {
    pub slot: String,
    pub target_entity: Option<u64>,
    pub target_position: Option<Vec3Row>,
}

impl From<EidolonCastArgs> for super::Reducer {
    fn from(args: EidolonCastArgs) -> Self {
        Self::EidolonCast {
            slot: args.slot,
            target_entity: args.target_entity,
            target_position: args.target_position,
        }
    }
}

impl __sdk::InModule for EidolonCastArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `eidolon_cast`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait eidolon_cast {
    /// Request that the remote module invoke the reducer `eidolon_cast` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`eidolon_cast:eidolon_cast_then`] to run a callback after the reducer completes.
    fn eidolon_cast(
        &self,
        slot: String,
        target_entity: Option<u64>,
        target_position: Option<Vec3Row>,
    ) -> __sdk::Result<()> {
        self.eidolon_cast_then(slot, target_entity, target_position, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `eidolon_cast` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn eidolon_cast_then(
        &self,
        slot: String,
        target_entity: Option<u64>,
        target_position: Option<Vec3Row>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl eidolon_cast for super::RemoteReducers {
    fn eidolon_cast_then(
        &self,
        slot: String,
        target_entity: Option<u64>,
        target_position: Option<Vec3Row>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            EidolonCastArgs {
                slot,
                target_entity,
                target_position,
            },
            callback,
        )
    }
}
