// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::entity_stats_type::EntityStats;
use super::stats_row_type::StatsRow;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `entity_stats`.
///
/// Obtain a handle from the [`EntityStatsTableAccess::entity_stats`] method on [`super::RemoteTables`],
/// like `ctx.db.entity_stats()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.entity_stats().on_insert(...)`.
pub struct EntityStatsTableHandle<'ctx> {
    imp: __sdk::TableHandle<EntityStats>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `entity_stats`.
pub struct EntityStatsTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for EntityStatsTableAccessor {
    type Row = EntityStats;
    type Handle<'db> = EntityStatsTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.entity_stats()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `entity_stats`.
///
/// Implemented for [`super::RemoteTables`].
pub trait EntityStatsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`EntityStatsTableHandle`], which mediates access to the table `entity_stats`.
    fn entity_stats(&self) -> EntityStatsTableHandle<'_>;
}

impl EntityStatsTableAccess for super::RemoteTables {
    fn entity_stats(&self) -> EntityStatsTableHandle<'_> {
        EntityStatsTableHandle {
            imp: self.imp.get_table::<EntityStats>("entity_stats"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct EntityStatsInsertCallbackId(__sdk::CallbackId);
pub struct EntityStatsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for EntityStatsTableHandle<'ctx> {
    type Row = EntityStats;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = EntityStats> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for EntityStatsTableHandle<'ctx> {
    type Row = EntityStats;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = EntityStats> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = EntityStatsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> EntityStatsInsertCallbackId {
        EntityStatsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: EntityStatsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = EntityStatsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> EntityStatsDeleteCallbackId {
        EntityStatsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: EntityStatsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for EntityStatsTableHandle<'ctx> {
    type InsertCallbackId = EntityStatsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> EntityStatsInsertCallbackId {
        EntityStatsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: EntityStatsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for EntityStatsTableHandle<'ctx> {
    type DeleteCallbackId = EntityStatsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> EntityStatsDeleteCallbackId {
        EntityStatsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: EntityStatsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct EntityStatsUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for EntityStatsTableHandle<'ctx> {
    type UpdateCallbackId = EntityStatsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> EntityStatsUpdateCallbackId {
        EntityStatsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: EntityStatsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for EntityStatsTableHandle<'ctx> {
    type UpdateCallbackId = EntityStatsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> EntityStatsUpdateCallbackId {
        EntityStatsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: EntityStatsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `entity_id` unique index on the table `entity_stats`,
/// which allows point queries on the field of the same name
/// via the [`EntityStatsEntityIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.entity_stats().entity_id().find(...)`.
pub struct EntityStatsEntityIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<EntityStats, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> EntityStatsTableHandle<'ctx> {
    /// Get a handle on the `entity_id` unique index on the table `entity_stats`.
    pub fn entity_id(&self) -> EntityStatsEntityIdUnique<'ctx> {
        EntityStatsEntityIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("entity_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> EntityStatsEntityIdUnique<'ctx> {
    /// Find the subscribed row whose `entity_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<EntityStats> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<EntityStats>("entity_stats");
    _table.add_unique_constraint::<u64>("entity_id", |row| &row.entity_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<EntityStats>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<EntityStats>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `EntityStats`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait entity_statsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `EntityStats`.
    fn entity_stats(&self) -> __sdk::__query_builder::Table<EntityStats>;
}

impl entity_statsQueryTableAccess for __sdk::QueryTableAccessor {
    fn entity_stats(&self) -> __sdk::__query_builder::Table<EntityStats> {
        __sdk::__query_builder::Table::new("entity_stats")
    }
}
