// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::color_row_type::ColorRow;
use super::entity_kind_row_type::EntityKindRow;
use super::entity_state_row_type::EntityStateRow;
use super::game_entity_type::GameEntity;
use super::vec_3_row_type::Vec3Row;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `game_entity`.
///
/// Obtain a handle from the [`GameEntityTableAccess::game_entity`] method on [`super::RemoteTables`],
/// like `ctx.db.game_entity()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.game_entity().on_insert(...)`.
pub struct GameEntityTableHandle<'ctx> {
    imp: __sdk::TableHandle<GameEntity>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `game_entity`.
pub struct GameEntityTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for GameEntityTableAccessor {
    type Row = GameEntity;
    type Handle<'db> = GameEntityTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.game_entity()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `game_entity`.
///
/// Implemented for [`super::RemoteTables`].
pub trait GameEntityTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`GameEntityTableHandle`], which mediates access to the table `game_entity`.
    fn game_entity(&self) -> GameEntityTableHandle<'_>;
}

impl GameEntityTableAccess for super::RemoteTables {
    fn game_entity(&self) -> GameEntityTableHandle<'_> {
        GameEntityTableHandle {
            imp: self.imp.get_table::<GameEntity>("game_entity"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct GameEntityInsertCallbackId(__sdk::CallbackId);
pub struct GameEntityDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for GameEntityTableHandle<'ctx> {
    type Row = GameEntity;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = GameEntity> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for GameEntityTableHandle<'ctx> {
    type Row = GameEntity;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = GameEntity> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = GameEntityInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameEntityInsertCallbackId {
        GameEntityInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GameEntityInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = GameEntityDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameEntityDeleteCallbackId {
        GameEntityDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GameEntityDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for GameEntityTableHandle<'ctx> {
    type InsertCallbackId = GameEntityInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameEntityInsertCallbackId {
        GameEntityInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GameEntityInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for GameEntityTableHandle<'ctx> {
    type DeleteCallbackId = GameEntityDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameEntityDeleteCallbackId {
        GameEntityDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GameEntityDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct GameEntityUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for GameEntityTableHandle<'ctx> {
    type UpdateCallbackId = GameEntityUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GameEntityUpdateCallbackId {
        GameEntityUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GameEntityUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for GameEntityTableHandle<'ctx> {
    type UpdateCallbackId = GameEntityUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GameEntityUpdateCallbackId {
        GameEntityUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GameEntityUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `entity_id` unique index on the table `game_entity`,
/// which allows point queries on the field of the same name
/// via the [`GameEntityEntityIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.game_entity().entity_id().find(...)`.
pub struct GameEntityEntityIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<GameEntity, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> GameEntityTableHandle<'ctx> {
    /// Get a handle on the `entity_id` unique index on the table `game_entity`.
    pub fn entity_id(&self) -> GameEntityEntityIdUnique<'ctx> {
        GameEntityEntityIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("entity_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> GameEntityEntityIdUnique<'ctx> {
    /// Find the subscribed row whose `entity_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<GameEntity> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<GameEntity>("game_entity");
    _table.add_unique_constraint::<u64>("entity_id", |row| &row.entity_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<GameEntity>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<GameEntity>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `GameEntity`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait game_entityQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `GameEntity`.
    fn game_entity(&self) -> __sdk::__query_builder::Table<GameEntity>;
}

impl game_entityQueryTableAccess for __sdk::QueryTableAccessor {
    fn game_entity(&self) -> __sdk::__query_builder::Table<GameEntity> {
        __sdk::__query_builder::Table::new("game_entity")
    }
}
