// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::color_row_type::ColorRow;
use super::entity_kind_row_type::EntityKindRow;
use super::entity_state_row_type::EntityStateRow;
use super::vec_3_row_type::Vec3Row;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct GameEntity {
    pub entity_id: u64,
    pub kind: EntityKindRow,
    pub owner_character_id: Option<u64>,
    pub display_name: String,
    pub color: ColorRow,
    pub position: Vec3Row,
    pub look: Vec3Row,
    pub move_target: Option<Vec3Row>,
    pub speed: f32,
    pub state: EntityStateRow,
    pub cell_x: i32,
    pub cell_z: i32,
    pub spawn_point: Vec3Row,
    pub respawn_in_seconds: Option<f32>,
}

impl __sdk::InModule for GameEntity {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `GameEntity`.
///
/// Provides typed access to columns for query building.
pub struct GameEntityCols {
    pub entity_id: __sdk::__query_builder::Col<GameEntity, u64>,
    pub kind: __sdk::__query_builder::Col<GameEntity, EntityKindRow>,
    pub owner_character_id: __sdk::__query_builder::Col<GameEntity, Option<u64>>,
    pub display_name: __sdk::__query_builder::Col<GameEntity, String>,
    pub color: __sdk::__query_builder::Col<GameEntity, ColorRow>,
    pub position: __sdk::__query_builder::Col<GameEntity, Vec3Row>,
    pub look: __sdk::__query_builder::Col<GameEntity, Vec3Row>,
    pub move_target: __sdk::__query_builder::Col<GameEntity, Option<Vec3Row>>,
    pub speed: __sdk::__query_builder::Col<GameEntity, f32>,
    pub state: __sdk::__query_builder::Col<GameEntity, EntityStateRow>,
    pub cell_x: __sdk::__query_builder::Col<GameEntity, i32>,
    pub cell_z: __sdk::__query_builder::Col<GameEntity, i32>,
    pub spawn_point: __sdk::__query_builder::Col<GameEntity, Vec3Row>,
    pub respawn_in_seconds: __sdk::__query_builder::Col<GameEntity, Option<f32>>,
}

impl __sdk::__query_builder::HasCols for GameEntity {
    type Cols = GameEntityCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        GameEntityCols {
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
            kind: __sdk::__query_builder::Col::new(table_name, "kind"),
            owner_character_id: __sdk::__query_builder::Col::new(table_name, "owner_character_id"),
            display_name: __sdk::__query_builder::Col::new(table_name, "display_name"),
            color: __sdk::__query_builder::Col::new(table_name, "color"),
            position: __sdk::__query_builder::Col::new(table_name, "position"),
            look: __sdk::__query_builder::Col::new(table_name, "look"),
            move_target: __sdk::__query_builder::Col::new(table_name, "move_target"),
            speed: __sdk::__query_builder::Col::new(table_name, "speed"),
            state: __sdk::__query_builder::Col::new(table_name, "state"),
            cell_x: __sdk::__query_builder::Col::new(table_name, "cell_x"),
            cell_z: __sdk::__query_builder::Col::new(table_name, "cell_z"),
            spawn_point: __sdk::__query_builder::Col::new(table_name, "spawn_point"),
            respawn_in_seconds: __sdk::__query_builder::Col::new(table_name, "respawn_in_seconds"),
        }
    }
}

/// Indexed column accessor struct for the table `GameEntity`.
///
/// Provides typed access to indexed columns for query building.
pub struct GameEntityIxCols {
    pub entity_id: __sdk::__query_builder::IxCol<GameEntity, u64>,
    pub owner_character_id: __sdk::__query_builder::IxCol<GameEntity, Option<u64>>,
}

impl __sdk::__query_builder::HasIxCols for GameEntity {
    type IxCols = GameEntityIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        GameEntityIxCols {
            entity_id: __sdk::__query_builder::IxCol::new(table_name, "entity_id"),
            owner_character_id: __sdk::__query_builder::IxCol::new(
                table_name,
                "owner_character_id",
            ),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for GameEntity {}
