// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::gather_yield_event_type::GatherYieldEvent;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `gather_yield`.
///
/// Obtain a handle from the [`GatherYieldTableAccess::gather_yield`] method on [`super::RemoteTables`],
/// like `ctx.db.gather_yield()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.gather_yield().on_insert(...)`.
pub struct GatherYieldTableHandle<'ctx> {
    imp: __sdk::TableHandle<GatherYieldEvent>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `gather_yield`.
pub struct GatherYieldTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for GatherYieldTableAccessor {
    type Row = GatherYieldEvent;
    type Handle<'db> = GatherYieldTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.gather_yield()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `gather_yield`.
///
/// Implemented for [`super::RemoteTables`].
pub trait GatherYieldTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`GatherYieldTableHandle`], which mediates access to the table `gather_yield`.
    fn gather_yield(&self) -> GatherYieldTableHandle<'_>;
}

impl GatherYieldTableAccess for super::RemoteTables {
    fn gather_yield(&self) -> GatherYieldTableHandle<'_> {
        GatherYieldTableHandle {
            imp: self.imp.get_table::<GatherYieldEvent>("gather_yield"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct GatherYieldInsertCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for GatherYieldTableHandle<'ctx> {
    type Row = GatherYieldEvent;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = GatherYieldEvent> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::EventTable for GatherYieldTableHandle<'ctx> {
    type Row = GatherYieldEvent;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = GatherYieldEvent> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = GatherYieldInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GatherYieldInsertCallbackId {
        GatherYieldInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GatherYieldInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for GatherYieldTableHandle<'ctx> {
    type InsertCallbackId = GatherYieldInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GatherYieldInsertCallbackId {
        GatherYieldInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GatherYieldInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<GatherYieldEvent>("gather_yield");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<GatherYieldEvent>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<GatherYieldEvent>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `GatherYieldEvent`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait gather_yieldQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `GatherYieldEvent`.
    fn gather_yield(&self) -> __sdk::__query_builder::Table<GatherYieldEvent>;
}

impl gather_yieldQueryTableAccess for __sdk::QueryTableAccessor {
    fn gather_yield(&self) -> __sdk::__query_builder::Table<GatherYieldEvent> {
        __sdk::__query_builder::Table::new("gather_yield")
    }
}
