// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::hotbar_row_type::HotbarRow;
use super::hotbar_type::Hotbar;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `hotbar`.
///
/// Obtain a handle from the [`HotbarTableAccess::hotbar`] method on [`super::RemoteTables`],
/// like `ctx.db.hotbar()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.hotbar().on_insert(...)`.
pub struct HotbarTableHandle<'ctx> {
    imp: __sdk::TableHandle<Hotbar>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `hotbar`.
pub struct HotbarTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for HotbarTableAccessor {
    type Row = Hotbar;
    type Handle<'db> = HotbarTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.hotbar()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `hotbar`.
///
/// Implemented for [`super::RemoteTables`].
pub trait HotbarTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`HotbarTableHandle`], which mediates access to the table `hotbar`.
    fn hotbar(&self) -> HotbarTableHandle<'_>;
}

impl HotbarTableAccess for super::RemoteTables {
    fn hotbar(&self) -> HotbarTableHandle<'_> {
        HotbarTableHandle {
            imp: self.imp.get_table::<Hotbar>("hotbar"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct HotbarInsertCallbackId(__sdk::CallbackId);
pub struct HotbarDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for HotbarTableHandle<'ctx> {
    type Row = Hotbar;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Hotbar> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for HotbarTableHandle<'ctx> {
    type Row = Hotbar;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Hotbar> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = HotbarInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> HotbarInsertCallbackId {
        HotbarInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: HotbarInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = HotbarDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> HotbarDeleteCallbackId {
        HotbarDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: HotbarDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for HotbarTableHandle<'ctx> {
    type InsertCallbackId = HotbarInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> HotbarInsertCallbackId {
        HotbarInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: HotbarInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for HotbarTableHandle<'ctx> {
    type DeleteCallbackId = HotbarDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> HotbarDeleteCallbackId {
        HotbarDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: HotbarDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct HotbarUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for HotbarTableHandle<'ctx> {
    type UpdateCallbackId = HotbarUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> HotbarUpdateCallbackId {
        HotbarUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: HotbarUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for HotbarTableHandle<'ctx> {
    type UpdateCallbackId = HotbarUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> HotbarUpdateCallbackId {
        HotbarUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: HotbarUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `character_id` unique index on the table `hotbar`,
/// which allows point queries on the field of the same name
/// via the [`HotbarCharacterIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.hotbar().character_id().find(...)`.
pub struct HotbarCharacterIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Hotbar, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> HotbarTableHandle<'ctx> {
    /// Get a handle on the `character_id` unique index on the table `hotbar`.
    pub fn character_id(&self) -> HotbarCharacterIdUnique<'ctx> {
        HotbarCharacterIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("character_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> HotbarCharacterIdUnique<'ctx> {
    /// Find the subscribed row whose `character_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Hotbar> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Hotbar>("hotbar");
    _table.add_unique_constraint::<u64>("character_id", |row| &row.character_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Hotbar>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Hotbar>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Hotbar`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait hotbarQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Hotbar`.
    fn hotbar(&self) -> __sdk::__query_builder::Table<Hotbar>;
}

impl hotbarQueryTableAccess for __sdk::QueryTableAccessor {
    fn hotbar(&self) -> __sdk::__query_builder::Table<Hotbar> {
        __sdk::__query_builder::Table::new("hotbar")
    }
}
