// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::item_instance_row_type::ItemInstanceRow;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct InventoryTable {
    pub character_id: u64,
    pub slots: Vec<Option<ItemInstanceRow>>,
}

impl __sdk::InModule for InventoryTable {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `InventoryTable`.
///
/// Provides typed access to columns for query building.
pub struct InventoryTableCols {
    pub character_id: __sdk::__query_builder::Col<InventoryTable, u64>,
    pub slots: __sdk::__query_builder::Col<InventoryTable, Vec<Option<ItemInstanceRow>>>,
}

impl __sdk::__query_builder::HasCols for InventoryTable {
    type Cols = InventoryTableCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        InventoryTableCols {
            character_id: __sdk::__query_builder::Col::new(table_name, "character_id"),
            slots: __sdk::__query_builder::Col::new(table_name, "slots"),
        }
    }
}

/// Indexed column accessor struct for the table `InventoryTable`.
///
/// Provides typed access to indexed columns for query building.
pub struct InventoryTableIxCols {
    pub character_id: __sdk::__query_builder::IxCol<InventoryTable, u64>,
}

impl __sdk::__query_builder::HasIxCols for InventoryTable {
    type IxCols = InventoryTableIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        InventoryTableIxCols {
            character_id: __sdk::__query_builder::IxCol::new(table_name, "character_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for InventoryTable {}
