// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::known_ancient_language_table_type::KnownAncientLanguageTable;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `known_ancient_language`.
///
/// Obtain a handle from the [`KnownAncientLanguageTableAccess::known_ancient_language`] method on [`super::RemoteTables`],
/// like `ctx.db.known_ancient_language()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.known_ancient_language().on_insert(...)`.
pub struct KnownAncientLanguageTableHandle<'ctx> {
    imp: __sdk::TableHandle<KnownAncientLanguageTable>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `known_ancient_language`.
pub struct KnownAncientLanguageTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for KnownAncientLanguageTableAccessor {
    type Row = KnownAncientLanguageTable;
    type Handle<'db> = KnownAncientLanguageTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.known_ancient_language()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `known_ancient_language`.
///
/// Implemented for [`super::RemoteTables`].
pub trait KnownAncientLanguageTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`KnownAncientLanguageTableHandle`], which mediates access to the table `known_ancient_language`.
    fn known_ancient_language(&self) -> KnownAncientLanguageTableHandle<'_>;
}

impl KnownAncientLanguageTableAccess for super::RemoteTables {
    fn known_ancient_language(&self) -> KnownAncientLanguageTableHandle<'_> {
        KnownAncientLanguageTableHandle {
            imp: self
                .imp
                .get_table::<KnownAncientLanguageTable>("known_ancient_language"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct KnownAncientLanguageInsertCallbackId(__sdk::CallbackId);
pub struct KnownAncientLanguageDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for KnownAncientLanguageTableHandle<'ctx> {
    type Row = KnownAncientLanguageTable;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = KnownAncientLanguageTable> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for KnownAncientLanguageTableHandle<'ctx> {
    type Row = KnownAncientLanguageTable;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = KnownAncientLanguageTable> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = KnownAncientLanguageInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> KnownAncientLanguageInsertCallbackId {
        KnownAncientLanguageInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: KnownAncientLanguageInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = KnownAncientLanguageDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> KnownAncientLanguageDeleteCallbackId {
        KnownAncientLanguageDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: KnownAncientLanguageDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for KnownAncientLanguageTableHandle<'ctx> {
    type InsertCallbackId = KnownAncientLanguageInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> KnownAncientLanguageInsertCallbackId {
        KnownAncientLanguageInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: KnownAncientLanguageInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for KnownAncientLanguageTableHandle<'ctx> {
    type DeleteCallbackId = KnownAncientLanguageDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> KnownAncientLanguageDeleteCallbackId {
        KnownAncientLanguageDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: KnownAncientLanguageDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct KnownAncientLanguageUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for KnownAncientLanguageTableHandle<'ctx> {
    type UpdateCallbackId = KnownAncientLanguageUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> KnownAncientLanguageUpdateCallbackId {
        KnownAncientLanguageUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: KnownAncientLanguageUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for KnownAncientLanguageTableHandle<'ctx> {
    type UpdateCallbackId = KnownAncientLanguageUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> KnownAncientLanguageUpdateCallbackId {
        KnownAncientLanguageUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: KnownAncientLanguageUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `character_id` unique index on the table `known_ancient_language`,
/// which allows point queries on the field of the same name
/// via the [`KnownAncientLanguageCharacterIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.known_ancient_language().character_id().find(...)`.
pub struct KnownAncientLanguageCharacterIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<KnownAncientLanguageTable, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> KnownAncientLanguageTableHandle<'ctx> {
    /// Get a handle on the `character_id` unique index on the table `known_ancient_language`.
    pub fn character_id(&self) -> KnownAncientLanguageCharacterIdUnique<'ctx> {
        KnownAncientLanguageCharacterIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("character_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> KnownAncientLanguageCharacterIdUnique<'ctx> {
    /// Find the subscribed row whose `character_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<KnownAncientLanguageTable> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table =
        client_cache.get_or_make_table::<KnownAncientLanguageTable>("known_ancient_language");
    _table.add_unique_constraint::<u64>("character_id", |row| &row.character_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<KnownAncientLanguageTable>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<KnownAncientLanguageTable>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `KnownAncientLanguageTable`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait known_ancient_languageQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `KnownAncientLanguageTable`.
    fn known_ancient_language(&self) -> __sdk::__query_builder::Table<KnownAncientLanguageTable>;
}

impl known_ancient_languageQueryTableAccess for __sdk::QueryTableAccessor {
    fn known_ancient_language(&self) -> __sdk::__query_builder::Table<KnownAncientLanguageTable> {
        __sdk::__query_builder::Table::new("known_ancient_language")
    }
}
