// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::market_buy_order_type::MarketBuyOrder;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `market_buy_order`.
///
/// Obtain a handle from the [`MarketBuyOrderTableAccess::market_buy_order`] method on [`super::RemoteTables`],
/// like `ctx.db.market_buy_order()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.market_buy_order().on_insert(...)`.
pub struct MarketBuyOrderTableHandle<'ctx> {
    imp: __sdk::TableHandle<MarketBuyOrder>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `market_buy_order`.
pub struct MarketBuyOrderTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for MarketBuyOrderTableAccessor {
    type Row = MarketBuyOrder;
    type Handle<'db> = MarketBuyOrderTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.market_buy_order()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `market_buy_order`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MarketBuyOrderTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MarketBuyOrderTableHandle`], which mediates access to the table `market_buy_order`.
    fn market_buy_order(&self) -> MarketBuyOrderTableHandle<'_>;
}

impl MarketBuyOrderTableAccess for super::RemoteTables {
    fn market_buy_order(&self) -> MarketBuyOrderTableHandle<'_> {
        MarketBuyOrderTableHandle {
            imp: self.imp.get_table::<MarketBuyOrder>("market_buy_order"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MarketBuyOrderInsertCallbackId(__sdk::CallbackId);
pub struct MarketBuyOrderDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for MarketBuyOrderTableHandle<'ctx> {
    type Row = MarketBuyOrder;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = MarketBuyOrder> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for MarketBuyOrderTableHandle<'ctx> {
    type Row = MarketBuyOrder;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = MarketBuyOrder> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MarketBuyOrderInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MarketBuyOrderInsertCallbackId {
        MarketBuyOrderInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MarketBuyOrderInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MarketBuyOrderDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MarketBuyOrderDeleteCallbackId {
        MarketBuyOrderDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MarketBuyOrderDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for MarketBuyOrderTableHandle<'ctx> {
    type InsertCallbackId = MarketBuyOrderInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MarketBuyOrderInsertCallbackId {
        MarketBuyOrderInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MarketBuyOrderInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for MarketBuyOrderTableHandle<'ctx> {
    type DeleteCallbackId = MarketBuyOrderDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MarketBuyOrderDeleteCallbackId {
        MarketBuyOrderDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MarketBuyOrderDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct MarketBuyOrderUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for MarketBuyOrderTableHandle<'ctx> {
    type UpdateCallbackId = MarketBuyOrderUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> MarketBuyOrderUpdateCallbackId {
        MarketBuyOrderUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: MarketBuyOrderUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for MarketBuyOrderTableHandle<'ctx> {
    type UpdateCallbackId = MarketBuyOrderUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> MarketBuyOrderUpdateCallbackId {
        MarketBuyOrderUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: MarketBuyOrderUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `market_buy_order`,
/// which allows point queries on the field of the same name
/// via the [`MarketBuyOrderIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.market_buy_order().id().find(...)`.
pub struct MarketBuyOrderIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<MarketBuyOrder, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> MarketBuyOrderTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `market_buy_order`.
    pub fn id(&self) -> MarketBuyOrderIdUnique<'ctx> {
        MarketBuyOrderIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> MarketBuyOrderIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<MarketBuyOrder> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<MarketBuyOrder>("market_buy_order");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<MarketBuyOrder>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<MarketBuyOrder>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `MarketBuyOrder`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait market_buy_orderQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `MarketBuyOrder`.
    fn market_buy_order(&self) -> __sdk::__query_builder::Table<MarketBuyOrder>;
}

impl market_buy_orderQueryTableAccess for __sdk::QueryTableAccessor {
    fn market_buy_order(&self) -> __sdk::__query_builder::Table<MarketBuyOrder> {
        __sdk::__query_builder::Table::new("market_buy_order")
    }
}
