// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct MarketBuyOrder {
    pub id: u64,
    pub market_id: String,
    pub buyer_character_id: __sdk::Uuid,
    pub item_id: String,
    pub price_gold: u64,
    pub created_at: __sdk::Timestamp,
}

impl __sdk::InModule for MarketBuyOrder {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `MarketBuyOrder`.
///
/// Provides typed access to columns for query building.
pub struct MarketBuyOrderCols {
    pub id: __sdk::__query_builder::Col<MarketBuyOrder, u64>,
    pub market_id: __sdk::__query_builder::Col<MarketBuyOrder, String>,
    pub buyer_character_id: __sdk::__query_builder::Col<MarketBuyOrder, __sdk::Uuid>,
    pub item_id: __sdk::__query_builder::Col<MarketBuyOrder, String>,
    pub price_gold: __sdk::__query_builder::Col<MarketBuyOrder, u64>,
    pub created_at: __sdk::__query_builder::Col<MarketBuyOrder, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for MarketBuyOrder {
    type Cols = MarketBuyOrderCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        MarketBuyOrderCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            market_id: __sdk::__query_builder::Col::new(table_name, "market_id"),
            buyer_character_id: __sdk::__query_builder::Col::new(table_name, "buyer_character_id"),
            item_id: __sdk::__query_builder::Col::new(table_name, "item_id"),
            price_gold: __sdk::__query_builder::Col::new(table_name, "price_gold"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
        }
    }
}

/// Indexed column accessor struct for the table `MarketBuyOrder`.
///
/// Provides typed access to indexed columns for query building.
pub struct MarketBuyOrderIxCols {
    pub buyer_character_id: __sdk::__query_builder::IxCol<MarketBuyOrder, __sdk::Uuid>,
    pub id: __sdk::__query_builder::IxCol<MarketBuyOrder, u64>,
}

impl __sdk::__query_builder::HasIxCols for MarketBuyOrder {
    type IxCols = MarketBuyOrderIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        MarketBuyOrderIxCols {
            buyer_character_id: __sdk::__query_builder::IxCol::new(
                table_name,
                "buyer_character_id",
            ),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for MarketBuyOrder {}
