// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::market_type::Market;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `market`.
///
/// Obtain a handle from the [`MarketTableAccess::market`] method on [`super::RemoteTables`],
/// like `ctx.db.market()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.market().on_insert(...)`.
pub struct MarketTableHandle<'ctx> {
    imp: __sdk::TableHandle<Market>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `market`.
pub struct MarketTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for MarketTableAccessor {
    type Row = Market;
    type Handle<'db> = MarketTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.market()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `market`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MarketTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MarketTableHandle`], which mediates access to the table `market`.
    fn market(&self) -> MarketTableHandle<'_>;
}

impl MarketTableAccess for super::RemoteTables {
    fn market(&self) -> MarketTableHandle<'_> {
        MarketTableHandle {
            imp: self.imp.get_table::<Market>("market"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MarketInsertCallbackId(__sdk::CallbackId);
pub struct MarketDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for MarketTableHandle<'ctx> {
    type Row = Market;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Market> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for MarketTableHandle<'ctx> {
    type Row = Market;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Market> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MarketInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MarketInsertCallbackId {
        MarketInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MarketInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MarketDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MarketDeleteCallbackId {
        MarketDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MarketDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for MarketTableHandle<'ctx> {
    type InsertCallbackId = MarketInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MarketInsertCallbackId {
        MarketInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MarketInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for MarketTableHandle<'ctx> {
    type DeleteCallbackId = MarketDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MarketDeleteCallbackId {
        MarketDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MarketDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct MarketUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for MarketTableHandle<'ctx> {
    type UpdateCallbackId = MarketUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> MarketUpdateCallbackId {
        MarketUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: MarketUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for MarketTableHandle<'ctx> {
    type UpdateCallbackId = MarketUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> MarketUpdateCallbackId {
        MarketUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: MarketUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `market`,
/// which allows point queries on the field of the same name
/// via the [`MarketIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.market().id().find(...)`.
pub struct MarketIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Market, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> MarketTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `market`.
    pub fn id(&self) -> MarketIdUnique<'ctx> {
        MarketIdUnique {
            imp: self.imp.get_unique_constraint::<String>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> MarketIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<Market> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Market>("market");
    _table.add_unique_constraint::<String>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Market>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Market>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Market`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait marketQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Market`.
    fn market(&self) -> __sdk::__query_builder::Table<Market>;
}

impl marketQueryTableAccess for __sdk::QueryTableAccessor {
    fn market(&self) -> __sdk::__query_builder::Table<Market> {
        __sdk::__query_builder::Table::new("market")
    }
}
