// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PeriodicEffect {
    pub id: u64,
    pub entity_id: u64,
    pub source: Option<u64>,
    pub amount_per_tick: f32,
    pub tick_interval_seconds: f32,
    pub origin_status_instance_id: Option<u64>,
    pub since_last_tick: f32,
    pub remaining_seconds: f32,
}

impl __sdk::InModule for PeriodicEffect {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `PeriodicEffect`.
///
/// Provides typed access to columns for query building.
pub struct PeriodicEffectCols {
    pub id: __sdk::__query_builder::Col<PeriodicEffect, u64>,
    pub entity_id: __sdk::__query_builder::Col<PeriodicEffect, u64>,
    pub source: __sdk::__query_builder::Col<PeriodicEffect, Option<u64>>,
    pub amount_per_tick: __sdk::__query_builder::Col<PeriodicEffect, f32>,
    pub tick_interval_seconds: __sdk::__query_builder::Col<PeriodicEffect, f32>,
    pub origin_status_instance_id: __sdk::__query_builder::Col<PeriodicEffect, Option<u64>>,
    pub since_last_tick: __sdk::__query_builder::Col<PeriodicEffect, f32>,
    pub remaining_seconds: __sdk::__query_builder::Col<PeriodicEffect, f32>,
}

impl __sdk::__query_builder::HasCols for PeriodicEffect {
    type Cols = PeriodicEffectCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PeriodicEffectCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
            source: __sdk::__query_builder::Col::new(table_name, "source"),
            amount_per_tick: __sdk::__query_builder::Col::new(table_name, "amount_per_tick"),
            tick_interval_seconds: __sdk::__query_builder::Col::new(
                table_name,
                "tick_interval_seconds",
            ),
            origin_status_instance_id: __sdk::__query_builder::Col::new(
                table_name,
                "origin_status_instance_id",
            ),
            since_last_tick: __sdk::__query_builder::Col::new(table_name, "since_last_tick"),
            remaining_seconds: __sdk::__query_builder::Col::new(table_name, "remaining_seconds"),
        }
    }
}

/// Indexed column accessor struct for the table `PeriodicEffect`.
///
/// Provides typed access to indexed columns for query building.
pub struct PeriodicEffectIxCols {
    pub entity_id: __sdk::__query_builder::IxCol<PeriodicEffect, u64>,
    pub id: __sdk::__query_builder::IxCol<PeriodicEffect, u64>,
}

impl __sdk::__query_builder::HasIxCols for PeriodicEffect {
    type IxCols = PeriodicEffectIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PeriodicEffectIxCols {
            entity_id: __sdk::__query_builder::IxCol::new(table_name, "entity_id"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for PeriodicEffect {}
