// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::periodic_effect_type::PeriodicEffect;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `periodic_effect`.
///
/// Obtain a handle from the [`PeriodicEffectTableAccess::periodic_effect`] method on [`super::RemoteTables`],
/// like `ctx.db.periodic_effect()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.periodic_effect().on_insert(...)`.
pub struct PeriodicEffectTableHandle<'ctx> {
    imp: __sdk::TableHandle<PeriodicEffect>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `periodic_effect`.
pub struct PeriodicEffectTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for PeriodicEffectTableAccessor {
    type Row = PeriodicEffect;
    type Handle<'db> = PeriodicEffectTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.periodic_effect()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `periodic_effect`.
///
/// Implemented for [`super::RemoteTables`].
pub trait PeriodicEffectTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`PeriodicEffectTableHandle`], which mediates access to the table `periodic_effect`.
    fn periodic_effect(&self) -> PeriodicEffectTableHandle<'_>;
}

impl PeriodicEffectTableAccess for super::RemoteTables {
    fn periodic_effect(&self) -> PeriodicEffectTableHandle<'_> {
        PeriodicEffectTableHandle {
            imp: self.imp.get_table::<PeriodicEffect>("periodic_effect"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct PeriodicEffectInsertCallbackId(__sdk::CallbackId);
pub struct PeriodicEffectDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for PeriodicEffectTableHandle<'ctx> {
    type Row = PeriodicEffect;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = PeriodicEffect> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for PeriodicEffectTableHandle<'ctx> {
    type Row = PeriodicEffect;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = PeriodicEffect> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = PeriodicEffectInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PeriodicEffectInsertCallbackId {
        PeriodicEffectInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PeriodicEffectInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = PeriodicEffectDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PeriodicEffectDeleteCallbackId {
        PeriodicEffectDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PeriodicEffectDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for PeriodicEffectTableHandle<'ctx> {
    type InsertCallbackId = PeriodicEffectInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PeriodicEffectInsertCallbackId {
        PeriodicEffectInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PeriodicEffectInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for PeriodicEffectTableHandle<'ctx> {
    type DeleteCallbackId = PeriodicEffectDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PeriodicEffectDeleteCallbackId {
        PeriodicEffectDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PeriodicEffectDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct PeriodicEffectUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for PeriodicEffectTableHandle<'ctx> {
    type UpdateCallbackId = PeriodicEffectUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PeriodicEffectUpdateCallbackId {
        PeriodicEffectUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PeriodicEffectUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for PeriodicEffectTableHandle<'ctx> {
    type UpdateCallbackId = PeriodicEffectUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PeriodicEffectUpdateCallbackId {
        PeriodicEffectUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PeriodicEffectUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `periodic_effect`,
/// which allows point queries on the field of the same name
/// via the [`PeriodicEffectIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.periodic_effect().id().find(...)`.
pub struct PeriodicEffectIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<PeriodicEffect, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> PeriodicEffectTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `periodic_effect`.
    pub fn id(&self) -> PeriodicEffectIdUnique<'ctx> {
        PeriodicEffectIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> PeriodicEffectIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<PeriodicEffect> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<PeriodicEffect>("periodic_effect");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<PeriodicEffect>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<PeriodicEffect>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `PeriodicEffect`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait periodic_effectQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `PeriodicEffect`.
    fn periodic_effect(&self) -> __sdk::__query_builder::Table<PeriodicEffect>;
}

impl periodic_effectQueryTableAccess for __sdk::QueryTableAccessor {
    fn periodic_effect(&self) -> __sdk::__query_builder::Table<PeriodicEffect> {
        __sdk::__query_builder::Table::new("periodic_effect")
    }
}
