// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PlayerMessageEvent {
    pub target: Option<__sdk::Identity>,
    pub text: String,
}

impl __sdk::InModule for PlayerMessageEvent {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `PlayerMessageEvent`.
///
/// Provides typed access to columns for query building.
pub struct PlayerMessageEventCols {
    pub target: __sdk::__query_builder::Col<PlayerMessageEvent, Option<__sdk::Identity>>,
    pub text: __sdk::__query_builder::Col<PlayerMessageEvent, String>,
}

impl __sdk::__query_builder::HasCols for PlayerMessageEvent {
    type Cols = PlayerMessageEventCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PlayerMessageEventCols {
            target: __sdk::__query_builder::Col::new(table_name, "target"),
            text: __sdk::__query_builder::Col::new(table_name, "text"),
        }
    }
}

/// Indexed column accessor struct for the table `PlayerMessageEvent`.
///
/// Provides typed access to indexed columns for query building.
pub struct PlayerMessageEventIxCols {}

impl __sdk::__query_builder::HasIxCols for PlayerMessageEvent {
    type IxCols = PlayerMessageEventIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PlayerMessageEventIxCols {}
    }
}
