// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::stats_row_type::StatsRow;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PlayerStats {
    pub character_id: __sdk::Uuid,
    pub stats: StatsRow,
}

impl __sdk::InModule for PlayerStats {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `PlayerStats`.
///
/// Provides typed access to columns for query building.
pub struct PlayerStatsCols {
    pub character_id: __sdk::__query_builder::Col<PlayerStats, __sdk::Uuid>,
    pub stats: __sdk::__query_builder::Col<PlayerStats, StatsRow>,
}

impl __sdk::__query_builder::HasCols for PlayerStats {
    type Cols = PlayerStatsCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PlayerStatsCols {
            character_id: __sdk::__query_builder::Col::new(table_name, "character_id"),
            stats: __sdk::__query_builder::Col::new(table_name, "stats"),
        }
    }
}

/// Indexed column accessor struct for the table `PlayerStats`.
///
/// Provides typed access to indexed columns for query building.
pub struct PlayerStatsIxCols {
    pub character_id: __sdk::__query_builder::IxCol<PlayerStats, __sdk::Uuid>,
}

impl __sdk::__query_builder::HasIxCols for PlayerStats {
    type IxCols = PlayerStatsIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PlayerStatsIxCols {
            character_id: __sdk::__query_builder::IxCol::new(table_name, "character_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for PlayerStats {}
