// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::vec_3_row_type::Vec3Row;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PropOverride {
    pub id: u64,
    pub map_id: String,
    pub prop_id: String,
    pub position: Option<Vec3Row>,
    pub rotation_y: Option<f32>,
    pub scale: Option<Vec3Row>,
    pub removed: bool,
}

impl __sdk::InModule for PropOverride {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `PropOverride`.
///
/// Provides typed access to columns for query building.
pub struct PropOverrideCols {
    pub id: __sdk::__query_builder::Col<PropOverride, u64>,
    pub map_id: __sdk::__query_builder::Col<PropOverride, String>,
    pub prop_id: __sdk::__query_builder::Col<PropOverride, String>,
    pub position: __sdk::__query_builder::Col<PropOverride, Option<Vec3Row>>,
    pub rotation_y: __sdk::__query_builder::Col<PropOverride, Option<f32>>,
    pub scale: __sdk::__query_builder::Col<PropOverride, Option<Vec3Row>>,
    pub removed: __sdk::__query_builder::Col<PropOverride, bool>,
}

impl __sdk::__query_builder::HasCols for PropOverride {
    type Cols = PropOverrideCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PropOverrideCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            map_id: __sdk::__query_builder::Col::new(table_name, "map_id"),
            prop_id: __sdk::__query_builder::Col::new(table_name, "prop_id"),
            position: __sdk::__query_builder::Col::new(table_name, "position"),
            rotation_y: __sdk::__query_builder::Col::new(table_name, "rotation_y"),
            scale: __sdk::__query_builder::Col::new(table_name, "scale"),
            removed: __sdk::__query_builder::Col::new(table_name, "removed"),
        }
    }
}

/// Indexed column accessor struct for the table `PropOverride`.
///
/// Provides typed access to indexed columns for query building.
pub struct PropOverrideIxCols {
    pub id: __sdk::__query_builder::IxCol<PropOverride, u64>,
    pub map_id: __sdk::__query_builder::IxCol<PropOverride, String>,
}

impl __sdk::__query_builder::HasIxCols for PropOverride {
    type IxCols = PropOverrideIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PropOverrideIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            map_id: __sdk::__query_builder::IxCol::new(table_name, "map_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for PropOverride {}
