// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::prop_override_type::PropOverride;
use super::vec_3_row_type::Vec3Row;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `prop_override`.
///
/// Obtain a handle from the [`PropOverrideTableAccess::prop_override`] method on [`super::RemoteTables`],
/// like `ctx.db.prop_override()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.prop_override().on_insert(...)`.
pub struct PropOverrideTableHandle<'ctx> {
    imp: __sdk::TableHandle<PropOverride>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `prop_override`.
pub struct PropOverrideTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for PropOverrideTableAccessor {
    type Row = PropOverride;
    type Handle<'db> = PropOverrideTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.prop_override()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `prop_override`.
///
/// Implemented for [`super::RemoteTables`].
pub trait PropOverrideTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`PropOverrideTableHandle`], which mediates access to the table `prop_override`.
    fn prop_override(&self) -> PropOverrideTableHandle<'_>;
}

impl PropOverrideTableAccess for super::RemoteTables {
    fn prop_override(&self) -> PropOverrideTableHandle<'_> {
        PropOverrideTableHandle {
            imp: self.imp.get_table::<PropOverride>("prop_override"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct PropOverrideInsertCallbackId(__sdk::CallbackId);
pub struct PropOverrideDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for PropOverrideTableHandle<'ctx> {
    type Row = PropOverride;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = PropOverride> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for PropOverrideTableHandle<'ctx> {
    type Row = PropOverride;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = PropOverride> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = PropOverrideInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PropOverrideInsertCallbackId {
        PropOverrideInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PropOverrideInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = PropOverrideDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PropOverrideDeleteCallbackId {
        PropOverrideDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PropOverrideDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for PropOverrideTableHandle<'ctx> {
    type InsertCallbackId = PropOverrideInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PropOverrideInsertCallbackId {
        PropOverrideInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PropOverrideInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for PropOverrideTableHandle<'ctx> {
    type DeleteCallbackId = PropOverrideDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PropOverrideDeleteCallbackId {
        PropOverrideDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PropOverrideDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct PropOverrideUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for PropOverrideTableHandle<'ctx> {
    type UpdateCallbackId = PropOverrideUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PropOverrideUpdateCallbackId {
        PropOverrideUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PropOverrideUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for PropOverrideTableHandle<'ctx> {
    type UpdateCallbackId = PropOverrideUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PropOverrideUpdateCallbackId {
        PropOverrideUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PropOverrideUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `prop_override`,
/// which allows point queries on the field of the same name
/// via the [`PropOverrideIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.prop_override().id().find(...)`.
pub struct PropOverrideIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<PropOverride, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> PropOverrideTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `prop_override`.
    pub fn id(&self) -> PropOverrideIdUnique<'ctx> {
        PropOverrideIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> PropOverrideIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<PropOverride> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<PropOverride>("prop_override");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<PropOverride>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<PropOverride>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `PropOverride`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait prop_overrideQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `PropOverride`.
    fn prop_override(&self) -> __sdk::__query_builder::Table<PropOverride>;
}

impl prop_overrideQueryTableAccess for __sdk::QueryTableAccessor {
    fn prop_override(&self) -> __sdk::__query_builder::Table<PropOverride> {
        __sdk::__query_builder::Table::new("prop_override")
    }
}
