// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetHotbarSpellArgs {
    pub slot: String,
    pub spell_id: Option<String>,
}

impl From<SetHotbarSpellArgs> for super::Reducer {
    fn from(args: SetHotbarSpellArgs) -> Self {
        Self::SetHotbarSpell {
            slot: args.slot,
            spell_id: args.spell_id,
        }
    }
}

impl __sdk::InModule for SetHotbarSpellArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_hotbar_spell`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_hotbar_spell {
    /// Request that the remote module invoke the reducer `set_hotbar_spell` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`set_hotbar_spell:set_hotbar_spell_then`] to run a callback after the reducer completes.
    fn set_hotbar_spell(&self, slot: String, spell_id: Option<String>) -> __sdk::Result<()> {
        self.set_hotbar_spell_then(slot, spell_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `set_hotbar_spell` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn set_hotbar_spell_then(
        &self,
        slot: String,
        spell_id: Option<String>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl set_hotbar_spell for super::RemoteReducers {
    fn set_hotbar_spell_then(
        &self,
        slot: String,
        spell_id: Option<String>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(SetHotbarSpellArgs { slot, spell_id }, callback)
    }
}
