// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetRootInscriptionArgs {
    pub root_word: Option<String>,
    pub primary_words: Vec<String>,
    pub secondary_words: Vec<String>,
    pub ultimate_words: Vec<String>,
}

impl From<SetRootInscriptionArgs> for super::Reducer {
    fn from(args: SetRootInscriptionArgs) -> Self {
        Self::SetRootInscription {
            root_word: args.root_word,
            primary_words: args.primary_words,
            secondary_words: args.secondary_words,
            ultimate_words: args.ultimate_words,
        }
    }
}

impl __sdk::InModule for SetRootInscriptionArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_root_inscription`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_root_inscription {
    /// Request that the remote module invoke the reducer `set_root_inscription` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`set_root_inscription:set_root_inscription_then`] to run a callback after the reducer completes.
    fn set_root_inscription(
        &self,
        root_word: Option<String>,
        primary_words: Vec<String>,
        secondary_words: Vec<String>,
        ultimate_words: Vec<String>,
    ) -> __sdk::Result<()> {
        self.set_root_inscription_then(
            root_word,
            primary_words,
            secondary_words,
            ultimate_words,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `set_root_inscription` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn set_root_inscription_then(
        &self,
        root_word: Option<String>,
        primary_words: Vec<String>,
        secondary_words: Vec<String>,
        ultimate_words: Vec<String>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl set_root_inscription for super::RemoteReducers {
    fn set_root_inscription_then(
        &self,
        root_word: Option<String>,
        primary_words: Vec<String>,
        secondary_words: Vec<String>,
        ultimate_words: Vec<String>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            SetRootInscriptionArgs {
                root_word,
                primary_words,
                secondary_words,
                ultimate_words,
            },
            callback,
        )
    }
}
