// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SplitItemArgs {
    pub slot_index: u8,
    pub amount: u32,
}

impl From<SplitItemArgs> for super::Reducer {
    fn from(args: SplitItemArgs) -> Self {
        Self::SplitItem {
            slot_index: args.slot_index,
            amount: args.amount,
        }
    }
}

impl __sdk::InModule for SplitItemArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `split_item`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait split_item {
    /// Request that the remote module invoke the reducer `split_item` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`split_item:split_item_then`] to run a callback after the reducer completes.
    fn split_item(&self, slot_index: u8, amount: u32) -> __sdk::Result<()> {
        self.split_item_then(slot_index, amount, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `split_item` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn split_item_then(
        &self,
        slot_index: u8,
        amount: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl split_item for super::RemoteReducers {
    fn split_item_then(
        &self,
        slot_index: u8,
        amount: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(SplitItemArgs { slot_index, amount }, callback)
    }
}
