// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct StartGatherArgs {
    pub node_entity_id: u64,
}

impl From<StartGatherArgs> for super::Reducer {
    fn from(args: StartGatherArgs) -> Self {
        Self::StartGather {
            node_entity_id: args.node_entity_id,
        }
    }
}

impl __sdk::InModule for StartGatherArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `start_gather`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait start_gather {
    /// Request that the remote module invoke the reducer `start_gather` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`start_gather:start_gather_then`] to run a callback after the reducer completes.
    fn start_gather(&self, node_entity_id: u64) -> __sdk::Result<()> {
        self.start_gather_then(node_entity_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `start_gather` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn start_gather_then(
        &self,
        node_entity_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl start_gather for super::RemoteReducers {
    fn start_gather_then(
        &self,
        node_entity_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(StartGatherArgs { node_entity_id }, callback)
    }
}
