// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct StartCraftArgs {
    pub npc_entity_id: u64,
    pub item_id: String,
    pub quantity: u32,
}

impl From<StartCraftArgs> for super::Reducer {
    fn from(args: StartCraftArgs) -> Self {
        Self::StartCraft {
            npc_entity_id: args.npc_entity_id,
            item_id: args.item_id,
            quantity: args.quantity,
        }
    }
}

impl __sdk::InModule for StartCraftArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `start_craft`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait start_craft {
    /// Request that the remote module invoke the reducer `start_craft` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`start_craft:start_craft_then`] to run a callback after the reducer completes.
    fn start_craft(&self, npc_entity_id: u64, item_id: String, quantity: u32) -> __sdk::Result<()> {
        self.start_craft_then(npc_entity_id, item_id, quantity, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `start_craft` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn start_craft_then(
        &self,
        npc_entity_id: u64,
        item_id: String,
        quantity: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl start_craft for super::RemoteReducers {
    fn start_craft_then(
        &self,
        npc_entity_id: u64,
        item_id: String,
        quantity: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            StartCraftArgs {
                npc_entity_id,
                item_id,
                quantity,
            },
            callback,
        )
    }
}
