// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::modifier_kind_row_type::ModifierKindRow;
use super::stat_modifier_type::StatModifier;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `stat_modifier`.
///
/// Obtain a handle from the [`StatModifierTableAccess::stat_modifier`] method on [`super::RemoteTables`],
/// like `ctx.db.stat_modifier()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.stat_modifier().on_insert(...)`.
pub struct StatModifierTableHandle<'ctx> {
    imp: __sdk::TableHandle<StatModifier>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `stat_modifier`.
pub struct StatModifierTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for StatModifierTableAccessor {
    type Row = StatModifier;
    type Handle<'db> = StatModifierTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.stat_modifier()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `stat_modifier`.
///
/// Implemented for [`super::RemoteTables`].
pub trait StatModifierTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`StatModifierTableHandle`], which mediates access to the table `stat_modifier`.
    fn stat_modifier(&self) -> StatModifierTableHandle<'_>;
}

impl StatModifierTableAccess for super::RemoteTables {
    fn stat_modifier(&self) -> StatModifierTableHandle<'_> {
        StatModifierTableHandle {
            imp: self.imp.get_table::<StatModifier>("stat_modifier"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct StatModifierInsertCallbackId(__sdk::CallbackId);
pub struct StatModifierDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for StatModifierTableHandle<'ctx> {
    type Row = StatModifier;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = StatModifier> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for StatModifierTableHandle<'ctx> {
    type Row = StatModifier;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = StatModifier> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = StatModifierInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> StatModifierInsertCallbackId {
        StatModifierInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: StatModifierInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = StatModifierDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> StatModifierDeleteCallbackId {
        StatModifierDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: StatModifierDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for StatModifierTableHandle<'ctx> {
    type InsertCallbackId = StatModifierInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> StatModifierInsertCallbackId {
        StatModifierInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: StatModifierInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for StatModifierTableHandle<'ctx> {
    type DeleteCallbackId = StatModifierDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> StatModifierDeleteCallbackId {
        StatModifierDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: StatModifierDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct StatModifierUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for StatModifierTableHandle<'ctx> {
    type UpdateCallbackId = StatModifierUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> StatModifierUpdateCallbackId {
        StatModifierUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: StatModifierUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for StatModifierTableHandle<'ctx> {
    type UpdateCallbackId = StatModifierUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> StatModifierUpdateCallbackId {
        StatModifierUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: StatModifierUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `stat_modifier`,
/// which allows point queries on the field of the same name
/// via the [`StatModifierIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.stat_modifier().id().find(...)`.
pub struct StatModifierIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<StatModifier, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> StatModifierTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `stat_modifier`.
    pub fn id(&self) -> StatModifierIdUnique<'ctx> {
        StatModifierIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> StatModifierIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<StatModifier> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<StatModifier>("stat_modifier");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<StatModifier>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<StatModifier>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `StatModifier`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait stat_modifierQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `StatModifier`.
    fn stat_modifier(&self) -> __sdk::__query_builder::Table<StatModifier>;
}

impl stat_modifierQueryTableAccess for __sdk::QueryTableAccessor {
    fn stat_modifier(&self) -> __sdk::__query_builder::Table<StatModifier> {
        __sdk::__query_builder::Table::new("stat_modifier")
    }
}
