// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct StopGatherArgs {}

impl From<StopGatherArgs> for super::Reducer {
    fn from(args: StopGatherArgs) -> Self {
        Self::StopGather
    }
}

impl __sdk::InModule for StopGatherArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `stop_gather`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait stop_gather {
    /// Request that the remote module invoke the reducer `stop_gather` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`stop_gather:stop_gather_then`] to run a callback after the reducer completes.
    fn stop_gather(&self) -> __sdk::Result<()> {
        self.stop_gather_then(|_, _| {})
    }

    /// Request that the remote module invoke the reducer `stop_gather` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn stop_gather_then(
        &self,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl stop_gather for super::RemoteReducers {
    fn stop_gather_then(
        &self,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(StopGatherArgs {}, callback)
    }
}
