// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::threat_type::Threat;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `threat`.
///
/// Obtain a handle from the [`ThreatTableAccess::threat`] method on [`super::RemoteTables`],
/// like `ctx.db.threat()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.threat().on_insert(...)`.
pub struct ThreatTableHandle<'ctx> {
    imp: __sdk::TableHandle<Threat>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `threat`.
pub struct ThreatTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for ThreatTableAccessor {
    type Row = Threat;
    type Handle<'db> = ThreatTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.threat()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `threat`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ThreatTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ThreatTableHandle`], which mediates access to the table `threat`.
    fn threat(&self) -> ThreatTableHandle<'_>;
}

impl ThreatTableAccess for super::RemoteTables {
    fn threat(&self) -> ThreatTableHandle<'_> {
        ThreatTableHandle {
            imp: self.imp.get_table::<Threat>("threat"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ThreatInsertCallbackId(__sdk::CallbackId);
pub struct ThreatDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for ThreatTableHandle<'ctx> {
    type Row = Threat;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Threat> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for ThreatTableHandle<'ctx> {
    type Row = Threat;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Threat> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ThreatInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ThreatInsertCallbackId {
        ThreatInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ThreatInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ThreatDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ThreatDeleteCallbackId {
        ThreatDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ThreatDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for ThreatTableHandle<'ctx> {
    type InsertCallbackId = ThreatInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ThreatInsertCallbackId {
        ThreatInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ThreatInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for ThreatTableHandle<'ctx> {
    type DeleteCallbackId = ThreatDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ThreatDeleteCallbackId {
        ThreatDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ThreatDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct ThreatUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ThreatTableHandle<'ctx> {
    type UpdateCallbackId = ThreatUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ThreatUpdateCallbackId {
        ThreatUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ThreatUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for ThreatTableHandle<'ctx> {
    type UpdateCallbackId = ThreatUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ThreatUpdateCallbackId {
        ThreatUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ThreatUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `threat`,
/// which allows point queries on the field of the same name
/// via the [`ThreatIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.threat().id().find(...)`.
pub struct ThreatIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Threat, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ThreatTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `threat`.
    pub fn id(&self) -> ThreatIdUnique<'ctx> {
        ThreatIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ThreatIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Threat> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Threat>("threat");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Threat>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Threat>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Threat`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait threatQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Threat`.
    fn threat(&self) -> __sdk::__query_builder::Table<Threat>;
}

impl threatQueryTableAccess for __sdk::QueryTableAccessor {
    fn threat(&self) -> __sdk::__query_builder::Table<Threat> {
        __sdk::__query_builder::Table::new("threat")
    }
}
