// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Threat {
    pub id: u64,
    pub boss_entity: u64,
    pub target_entity: u64,
    pub amount: f32,
}

impl __sdk::InModule for Threat {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Threat`.
///
/// Provides typed access to columns for query building.
pub struct ThreatCols {
    pub id: __sdk::__query_builder::Col<Threat, u64>,
    pub boss_entity: __sdk::__query_builder::Col<Threat, u64>,
    pub target_entity: __sdk::__query_builder::Col<Threat, u64>,
    pub amount: __sdk::__query_builder::Col<Threat, f32>,
}

impl __sdk::__query_builder::HasCols for Threat {
    type Cols = ThreatCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ThreatCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            boss_entity: __sdk::__query_builder::Col::new(table_name, "boss_entity"),
            target_entity: __sdk::__query_builder::Col::new(table_name, "target_entity"),
            amount: __sdk::__query_builder::Col::new(table_name, "amount"),
        }
    }
}

/// Indexed column accessor struct for the table `Threat`.
///
/// Provides typed access to indexed columns for query building.
pub struct ThreatIxCols {
    pub boss_entity: __sdk::__query_builder::IxCol<Threat, u64>,
    pub id: __sdk::__query_builder::IxCol<Threat, u64>,
}

impl __sdk::__query_builder::HasIxCols for Threat {
    type IxCols = ThreatIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ThreatIxCols {
            boss_entity: __sdk::__query_builder::IxCol::new(table_name, "boss_entity"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Threat {}
