[package]
name = "bevymmo_presentation"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.19", default-features = true, features = ["serialize"] }
bevy_asset_loader = { version = "0.27", features = ["3d"] }
lightyear = { workspace = true }
bevymmo_shared = { path = "../shared" }
bevymmo_client = { path = "../client" }
serde = { workspace = true }
serde_json = { workspace = true }
dirs = { workspace = true }
