[package]
name = "bevymmo_shared"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { workspace = true }
lightyear = { workspace = true, features = [
    "interpolation",
    "prediction",
    "replication",
    "input_native",
] }
serde = { workspace = true }
config = { workspace = true }
ron = "0.10"
thiserror = "2"
gltf = { version = "1", default-features = false, features = ["utils", "names", "extras"] }
serde_json = "1"
bevymmo-props-macro = { path = "../bevymmo-props-macro" }

[dev-dependencies]
serde_json = "1"
